/**
 * Generic Connect-RPC MSW handler builder.
 *
 * Produces MSW `http.post(...)` handlers that match the URL path convention
 * used by Connect-RPC (both Connect and gRPC-Web protocols):
 *
 *     POST {baseUrl}/{ServiceTypeName}/{MethodName}
 *
 * Responses are serialized using `@bufbuild/protobuf`'s `toJson()` for
 * correct protobuf canonical JSON encoding (int64 as string, Timestamp
 * as RFC 3339, etc.).
 *
 * This module has zero knowledge of any specific product's protos -- it
 * operates on the generic `DescService` / `DescMethod` descriptors that
 * `@bufbuild/protobuf` code-generates for every service.
 */

/**
 * The minimal service descriptor shape needed to build Connect-RPC handlers.
 *
 * Matches `DescService` from `@bufbuild/protobuf` without requiring the
 * full type as a hard dependency — the package is a peer dependency.
 */
interface ServiceDescriptor {
  readonly typeName: string;
  readonly method: Record<string, MethodDescriptor>;
}

interface MethodDescriptor {
  readonly name: string;
  readonly output: { readonly typeName: string };
}

/**
 * Handler function invoked when a matching Connect-RPC request arrives.
 * Receives the parsed JSON request body and returns the response payload.
 * May be async.
 */
export type ConnectFixtureHandler = (
  input: unknown,
) => unknown | Promise<unknown>;

/**
 * Options for fine-tuning the generated MSW handler.
 */
export interface ConnectHandlerOptions {
  /** HTTP status code to return. Defaults to 200. */
  readonly status?: number;
  /** Extra response headers. */
  readonly headers?: Record<string, string>;
}

/**
 * Create an MSW handler for a Connect-RPC unary method.
 *
 * @param service - A protobuf service descriptor (`DescService` or `GenService`).
 *   These are the `const` values code-generated by `@bufbuild/protobuf`
 *   (e.g. `SessionQueryController`, `ApiKeyQueryController`).
 *
 * @param methodKey - The method name as it appears in the service descriptor's
 *   `method` record (e.g. `"get"`, `"list"`, `"findAll"`).
 *
 * @param handler - A function that receives the parsed JSON request body and
 *   returns the response payload. The returned value is serialized as JSON
 *   in the response. Use `@bufbuild/protobuf`'s `create()` + `toJson()` for
 *   type-safe, encoding-correct responses, or return a plain object for
 *   simple cases.
 *
 * @param options - Optional status code and headers overrides.
 *
 * @returns An MSW `HttpHandler` that intercepts POST requests matching
 *   the Connect-RPC URL pattern for the given service/method.
 */
export async function connectHandler(
  service: ServiceDescriptor,
  methodKey: string,
  handler: ConnectFixtureHandler,
  options?: ConnectHandlerOptions,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
): Promise<any> {
  const method = service.method[methodKey];
  if (!method) {
    const available = Object.keys(service.method).join(", ");
    throw new Error(
      `[scenar/preview/connect] Method "${methodKey}" not found on service ` +
      `"${service.typeName}". Available methods: ${available}`,
    );
  }

  const { http, HttpResponse } = await import("msw");

  const urlPattern = `*/${service.typeName}/${method.name}`;

  return http.post(urlPattern, async ({ request }) => {
    const body = await request.json().catch(() => ({}));
    const result = await handler(body);

    const status = options?.status ?? 200;
    const extraHeaders: Record<string, string> = {
      "content-type": "application/json",
      ...(options?.headers ?? {}),
    };

    // Protobuf int64 fields are typed as `bigint` in generated TS.
    // JSON.stringify cannot handle bigint natively; Connect-RPC encodes
    // int64 as JSON strings, so String(value) is protocol-correct.
    const jsonBody = JSON.stringify(result, (_key, value) =>
      typeof value === "bigint" ? String(value) : (value as unknown),
    );

    return new HttpResponse(jsonBody, { status, headers: extraHeaders });
  });
}

/**
 * Create MSW handlers for multiple Connect-RPC methods on the same service.
 *
 * Convenience wrapper over `connectHandler` for scenarios that mock
 * several methods at once.
 *
 * @example
 * ```ts
 * const handlers = await connectHandlers(SessionQueryController, {
 *   get: (req) => samples.session({ id: req.value }),
 *   list: () => ({ entries: [samples.session()] }),
 * });
 * ```
 */
export async function connectHandlers(
  service: ServiceDescriptor,
  methods: Record<string, ConnectFixtureHandler>,
  options?: ConnectHandlerOptions,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
): Promise<any[]> {
  const entries = Object.entries(methods);
  return Promise.all(
    entries.map(([key, fn]) => connectHandler(service, key, fn, options)),
  );
}
