// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/iam/v1/enum.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IamPermission defines the permissions checked by the authorization
// interceptor before an RPC handler executes.
//
// Each value maps to an FGA permission name (a computed relation derived
// from roles). Permissions are never directly assigned to principals —
// they are granted implicitly through role assignments.
//
// For assignable roles, see IamRole below.
// For structural FGA relations (organization, owner, etc.), those are
// internal wiring and not represented in this enum.
type IamPermission int32

const (
	IamPermission_unspecified IamPermission = 0
	// Standard CRUD permissions.
	IamPermission_can_view   IamPermission = 1
	IamPermission_can_edit   IamPermission = 2
	IamPermission_can_delete IamPermission = 3
	// Access management permissions.
	IamPermission_can_grant_access IamPermission = 4
	IamPermission_can_view_access  IamPermission = 5
	// Organization-level create permission for scenarios.
	IamPermission_can_create_scenario IamPermission = 6
	// Secret access permission (e.g. revealing an API key's secret once).
	IamPermission_can_read_secrets IamPermission = 16
	// Platform-level permissions.
	IamPermission_can_bootstrap_iam            IamPermission = 17
	IamPermission_can_manage_identity_accounts IamPermission = 18
	// Back-office access permission.
	IamPermission_login_to_back_office IamPermission = 20
)

// Enum value maps for IamPermission.
var (
	IamPermission_name = map[int32]string{
		0:  "unspecified",
		1:  "can_view",
		2:  "can_edit",
		3:  "can_delete",
		4:  "can_grant_access",
		5:  "can_view_access",
		6:  "can_create_scenario",
		16: "can_read_secrets",
		17: "can_bootstrap_iam",
		18: "can_manage_identity_accounts",
		20: "login_to_back_office",
	}
	IamPermission_value = map[string]int32{
		"unspecified":                  0,
		"can_view":                     1,
		"can_edit":                     2,
		"can_delete":                   3,
		"can_grant_access":             4,
		"can_view_access":              5,
		"can_create_scenario":          6,
		"can_read_secrets":             16,
		"can_bootstrap_iam":            17,
		"can_manage_identity_accounts": 18,
		"login_to_back_office":         20,
	}
)

func (x IamPermission) Enum() *IamPermission {
	p := new(IamPermission)
	*p = x
	return p
}

func (x IamPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IamPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_scenar_iam_v1_enum_proto_enumTypes[0].Descriptor()
}

func (IamPermission) Type() protoreflect.EnumType {
	return &file_ai_scenar_iam_v1_enum_proto_enumTypes[0]
}

func (x IamPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IamPermission.Descriptor instead.
func (IamPermission) EnumDescriptor() ([]byte, []int) {
	return file_ai_scenar_iam_v1_enum_proto_rawDescGZIP(), []int{0}
}

// IamRole defines the roles that can be assigned to principals on resources
// via IAM policies.
//
// Roles are human-assigned and represent a principal's relationship to a
// resource. They are distinct from permissions (which are computed from roles
// and checked by the authorization interceptor) and structural relations
// (which are internal FGA wiring like organization or owner links).
//
// Each ApiResourceKind declares which of these roles are grantable via
// the grantable_roles field in its AuthorizationConfig.
type IamRole int32

const (
	IamRole_iam_role_unspecified IamRole = 0
	// Full control of the resource. Typically assigned to the creator.
	IamRole_owner IamRole = 1
	// Administrative access. Grants most permissions except ownership transfer.
	IamRole_admin IamRole = 2
	// Membership-level access. Grants read and limited write permissions.
	IamRole_member IamRole = 3
	// Read-only access to the resource.
	IamRole_viewer IamRole = 4
)

// Enum value maps for IamRole.
var (
	IamRole_name = map[int32]string{
		0: "iam_role_unspecified",
		1: "owner",
		2: "admin",
		3: "member",
		4: "viewer",
	}
	IamRole_value = map[string]int32{
		"iam_role_unspecified": 0,
		"owner":                1,
		"admin":                2,
		"member":               3,
		"viewer":               4,
	}
)

func (x IamRole) Enum() *IamRole {
	p := new(IamRole)
	*p = x
	return p
}

func (x IamRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IamRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_scenar_iam_v1_enum_proto_enumTypes[1].Descriptor()
}

func (IamRole) Type() protoreflect.EnumType {
	return &file_ai_scenar_iam_v1_enum_proto_enumTypes[1]
}

func (x IamRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IamRole.Descriptor instead.
func (IamRole) EnumDescriptor() ([]byte, []int) {
	return file_ai_scenar_iam_v1_enum_proto_rawDescGZIP(), []int{1}
}

var File_ai_scenar_iam_v1_enum_proto protoreflect.FileDescriptor

const file_ai_scenar_iam_v1_enum_proto_rawDesc = "" +
	"\n" +
	"\x1bai/scenar/iam/v1/enum.proto\x12\x10ai.scenar.iam.v1*\xf9\x01\n" +
	"\rIamPermission\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\f\n" +
	"\bcan_view\x10\x01\x12\f\n" +
	"\bcan_edit\x10\x02\x12\x0e\n" +
	"\n" +
	"can_delete\x10\x03\x12\x14\n" +
	"\x10can_grant_access\x10\x04\x12\x13\n" +
	"\x0fcan_view_access\x10\x05\x12\x17\n" +
	"\x13can_create_scenario\x10\x06\x12\x14\n" +
	"\x10can_read_secrets\x10\x10\x12\x15\n" +
	"\x11can_bootstrap_iam\x10\x11\x12 \n" +
	"\x1ccan_manage_identity_accounts\x10\x12\x12\x18\n" +
	"\x14login_to_back_office\x10\x14*Q\n" +
	"\aIamRole\x12\x18\n" +
	"\x14iam_role_unspecified\x10\x00\x12\t\n" +
	"\x05owner\x10\x01\x12\t\n" +
	"\x05admin\x10\x02\x12\n" +
	"\n" +
	"\x06member\x10\x03\x12\n" +
	"\n" +
	"\x06viewer\x10\x04B\xc4\x01\n" +
	"\x14com.ai.scenar.iam.v1B\tEnumProtoP\x01Z>github.com/stigmer/scenar/apis/stubs/go/ai/scenar/iam/v1;iamv1\xa2\x02\x03ASI\xaa\x02\x10Ai.Scenar.Iam.V1\xca\x02\x10Ai\\Scenar\\Iam\\V1\xe2\x02\x1cAi\\Scenar\\Iam\\V1\\GPBMetadata\xea\x02\x13Ai::Scenar::Iam::V1b\x06proto3"

var (
	file_ai_scenar_iam_v1_enum_proto_rawDescOnce sync.Once
	file_ai_scenar_iam_v1_enum_proto_rawDescData []byte
)

func file_ai_scenar_iam_v1_enum_proto_rawDescGZIP() []byte {
	file_ai_scenar_iam_v1_enum_proto_rawDescOnce.Do(func() {
		file_ai_scenar_iam_v1_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_iam_v1_enum_proto_rawDesc), len(file_ai_scenar_iam_v1_enum_proto_rawDesc)))
	})
	return file_ai_scenar_iam_v1_enum_proto_rawDescData
}

var file_ai_scenar_iam_v1_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_scenar_iam_v1_enum_proto_goTypes = []any{
	(IamPermission)(0), // 0: ai.scenar.iam.v1.IamPermission
	(IamRole)(0),       // 1: ai.scenar.iam.v1.IamRole
}
var file_ai_scenar_iam_v1_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_iam_v1_enum_proto_init() }
func file_ai_scenar_iam_v1_enum_proto_init() {
	if File_ai_scenar_iam_v1_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_iam_v1_enum_proto_rawDesc), len(file_ai_scenar_iam_v1_enum_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_iam_v1_enum_proto_goTypes,
		DependencyIndexes: file_ai_scenar_iam_v1_enum_proto_depIdxs,
		EnumInfos:         file_ai_scenar_iam_v1_enum_proto_enumTypes,
	}.Build()
	File_ai_scenar_iam_v1_enum_proto = out.File
	file_ai_scenar_iam_v1_enum_proto_goTypes = nil
	file_ai_scenar_iam_v1_enum_proto_depIdxs = nil
}
