// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/tenancy/organization/v1/io.proto (package ai.scenar.tenancy.organization.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/tenancy/organization/v1/io.proto.
 */
export const file_ai_scenar_tenancy_organization_v1_io: GenFile = /*@__PURE__*/
  fileDesc("CiphaS9zY2VuYXIvdGVuYW5jeS9vcmdhbml6YXRpb24vdjEvaW8ucHJvdG8SIWFpLnNjZW5hci50ZW5hbmN5Lm9yZ2FuaXphdGlvbi52MSJKChhMaXN0T3JnYW5pemF0aW9uc1JlcXVlc3QSGgoJcGFnZV9zaXplGAEgASgFQge6SAQaAigAEhIKCnBhZ2VfdG9rZW4YAiABKAliBnByb3RvMw", [file_buf_validate_validate]);

/**
 * ListOrganizationsRequest is the input for the organization list query. Unlike
 * most resources, organizations are top-level tenants and are not scoped to a
 * parent org, so the request only carries pagination.
 *
 * Pagination is defined per-resource here (rather than in commons) until the
 * platform settles on a shared pagination contract; the field shape
 * (page_size / page_token / next_page_token) is the conventional cursor model
 * and is intended to migrate to commons unchanged when that contract lands.
 *
 * @generated from message ai.scenar.tenancy.organization.v1.ListOrganizationsRequest
 */
export type ListOrganizationsRequest = Message<"ai.scenar.tenancy.organization.v1.ListOrganizationsRequest"> & {
  /**
   * Maximum number of organizations to return in one page. When 0 or unset, the
   * server applies its default page size. The server may return fewer items
   * than requested.
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * Opaque cursor identifying the page to return. Empty fetches the first page.
   * Pass the next_page_token from the previous OrganizationList to continue.
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message ai.scenar.tenancy.organization.v1.ListOrganizationsRequest.
 * Use `create(ListOrganizationsRequestSchema)` to create a new message.
 */
export const ListOrganizationsRequestSchema: GenMessage<ListOrganizationsRequest> = /*@__PURE__*/
  messageDesc(file_ai_scenar_tenancy_organization_v1_io, 0);

