// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=js"
// @generated from file ai/scenar/tenancy/organization/v1/status.proto (package ai.scenar.tenancy.organization.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_ai_scenar_commons_apiresource_field_options } from "../../../commons/apiresource/field_options_pb.js";
import type { ApiResourceAudit } from "../../../commons/apiresource/status_pb.js";
import { file_ai_scenar_commons_apiresource_status } from "../../../commons/apiresource/status_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/tenancy/organization/v1/status.proto.
 */
export const file_ai_scenar_tenancy_organization_v1_status: GenFile = /*@__PURE__*/
  fileDesc("Ci5haS9zY2VuYXIvdGVuYW5jeS9vcmdhbml6YXRpb24vdjEvc3RhdHVzLnByb3RvEiFhaS5zY2VuYXIudGVuYW5jeS5vcmdhbml6YXRpb24udjEicAoST3JnYW5pemF0aW9uU3RhdHVzEhoKDG1lbWJlcl9jb3VudBgBIAEoBUIEyIUsARI+CgVhdWRpdBhjIAEoCzIvLmFpLnNjZW5hci5jb21tb25zLmFwaXJlc291cmNlLkFwaVJlc291cmNlQXVkaXRiBnByb3RvMw", [file_ai_scenar_commons_apiresource_field_options, file_ai_scenar_commons_apiresource_status]);

/**
 * OrganizationStatus is the observed state of an Organization resource — the
 * `status` block of the envelope (see api.proto). Every field here is computed
 * and managed by the system; clients never set status on create or update.
 *
 * @generated from message ai.scenar.tenancy.organization.v1.OrganizationStatus
 */
export type OrganizationStatus = Message<"ai.scenar.tenancy.organization.v1.OrganizationStatus"> & {
  /**
   * Number of members belonging to the organization. Computed by the backend
   * from the organization's membership records.
   *
   * @generated from field: int32 member_count = 1;
   */
  memberCount: number;

  /**
   * Standard creation/modification audit information. The high field number
   * keeps audit at a stable, conventional location and leaves room below for
   * future organization-specific status fields.
   *
   * Typed as ApiResourceAudit directly (not the ApiResourceAuditStatus
   * wrapper): the platform's audit reflection adapter locates this block by the
   * field name `audit` on the status message and requires its type to be
   * ApiResourceAudit. The wrapper is only used when a resource's entire status
   * field is the audit block.
   *
   * @generated from field: ai.scenar.commons.apiresource.ApiResourceAudit audit = 99;
   */
  audit?: ApiResourceAudit;
};

/**
 * Describes the message ai.scenar.tenancy.organization.v1.OrganizationStatus.
 * Use `create(OrganizationStatusSchema)` to create a new message.
 */
export const OrganizationStatusSchema: GenMessage<OrganizationStatus> = /*@__PURE__*/
  messageDesc(file_ai_scenar_tenancy_organization_v1_status, 0);

