# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/iam/iampolicy/v1/api.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/iam/iampolicy/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import metadata_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_metadata__pb2
from ai.scenar.commons.apiresource import status_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_status__pb2
from ai.scenar.iam.iampolicy.v1 import spec_pb2 as ai_dot_scenar_dot_iam_dot_iampolicy_dot_v1_dot_spec__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ai/scenar/iam/iampolicy/v1/api.proto\x12\x1a\x61i.scenar.iam.iampolicy.v1\x1a,ai/scenar/commons/apiresource/metadata.proto\x1a*ai/scenar/commons/apiresource/status.proto\x1a%ai/scenar/iam/iampolicy/v1/spec.proto\x1a\x1b\x62uf/validate/validate.proto\"\xbf\x02\n\tIamPolicy\x12\x38\n\x0b\x61pi_version\x18\x01 \x01(\tB\x17\xbaH\x14r\x12\n\x10iam.scenar.ai/v1R\napiVersion\x12$\n\x04kind\x18\x02 \x01(\tB\x10\xbaH\rr\x0b\n\tIamPolicyR\x04kind\x12N\n\x08metadata\x18\x03 \x01(\x0b\x32\x32.ai.scenar.commons.apiresource.ApiResourceMetadataR\x08metadata\x12=\n\x04spec\x18\x04 \x01(\x0b\x32).ai.scenar.iam.iampolicy.v1.IamPolicySpecR\x04spec\x12\x43\n\x06status\x18\x05 \x01(\x0b\x32+.ai.scenar.iam.iampolicy.v1.IamPolicyStatusR\x06status\"X\n\x0fIamPolicyStatus\x12\x45\n\x05\x61udit\x18\x01 \x01(\x0b\x32/.ai.scenar.commons.apiresource.ApiResourceAuditR\x05\x61uditb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.iam.iampolicy.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IAMPOLICY'].fields_by_name['api_version']._loaded_options = None
  _globals['_IAMPOLICY'].fields_by_name['api_version']._serialized_options = b'\272H\024r\022\n\020iam.scenar.ai/v1'
  _globals['_IAMPOLICY'].fields_by_name['kind']._loaded_options = None
  _globals['_IAMPOLICY'].fields_by_name['kind']._serialized_options = b'\272H\rr\013\n\tIamPolicy'
  _globals['_IAMPOLICY']._serialized_start=227
  _globals['_IAMPOLICY']._serialized_end=546
  _globals['_IAMPOLICYSTATUS']._serialized_start=548
  _globals['_IAMPOLICYSTATUS']._serialized_end=636
# @@protoc_insertion_point(module_scope)
