// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/deploy/v1/spec.proto (package ai.scenar.deploy.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_ai_scenar_commons_apiresource_field_options } from "../../commons/apiresource/field_options_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/deploy/v1/spec.proto.
 */
export const file_ai_scenar_deploy_v1_spec: GenFile = /*@__PURE__*/
  fileDesc("Ch5haS9zY2VuYXIvZGVwbG95L3YxL3NwZWMucHJvdG8SE2FpLnNjZW5hci5kZXBsb3kudjEiLgoKRGVwbG95U3BlYxIgCgtzY2VuYXJpb19pZBgBIAEoCUILukgEcgIQAdCFLAFiBnByb3RvMw", [file_ai_scenar_commons_apiresource_field_options, file_buf_validate_validate]);

/**
 * DeploySpec defines the desired state of a Deploy resource — the `spec` block
 * of the envelope (see api.proto).
 *
 * A deploy is a child of exactly one Scenario and is **immutable**: it captures
 * one publication of that scenario's bundle. The only author-determined input is
 * the parent scenario it belongs to; everything else about a deploy (its objects,
 * hashes, serving URL, and lifecycle state) is computed by the backend and lives
 * in DeployStatus.
 *
 * scenario_id doubles as the resource's authorization parent: the resource-kind
 * metadata declares deploy as PARENT-scoped to scenario via this field, so a
 * deploy inherits view/edit/delete from the scenario it snapshots.
 *
 * The inputs the two-phase upload session supplies at creation time (declared
 * object inventory, content hashes, source/CLI version) are added to this spec
 * alongside that session's command RPCs; the substrate models only the parent
 * link.
 *
 * @generated from message ai.scenar.deploy.v1.DeploySpec
 */
export type DeploySpec = Message<"ai.scenar.deploy.v1.DeploySpec"> & {
  /**
   * The Scenario this deploy snapshots. Required and immutable — a deploy can
   * never be reparented. This is the field the platform reads to resolve the
   * authorization parent (see the deploy kind's AuthorizationConfig).
   *
   * @generated from field: string scenario_id = 1;
   */
  scenarioId: string;
};

/**
 * Describes the message ai.scenar.deploy.v1.DeploySpec.
 * Use `create(DeploySpecSchema)` to create a new message.
 */
export const DeploySpecSchema: GenMessage<DeploySpec> = /*@__PURE__*/
  messageDesc(file_ai_scenar_deploy_v1_spec, 0);

