# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/scenario/v1/enum.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/scenario/v1/enum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ai/scenar/scenario/v1/enum.proto\x12\x15\x61i.scenar.scenario.v1*\x91\x01\n\nActionType\x12\x0f\n\x0bunspecified\x10\x00\x12\x0e\n\nset_cursor\x10\x01\x12\x10\n\x0c\x63lear_cursor\x10\x02\x12\t\n\x05\x63lick\x10\x03\x12\x08\n\x04type\x10\x04\x12\t\n\x05hover\x10\x05\x12\x08\n\x04\x64rag\x10\x06\x12\r\n\tscroll_to\x10\x07\x12\x17\n\x13viewport_transition\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.scenario.v1.enum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONTYPE']._serialized_start=60
  _globals['_ACTIONTYPE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
