# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/scenario/v1/io.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/scenario/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.rpc import pagination_pb2 as ai_dot_scenar_dot_commons_dot_rpc_dot_pagination__pb2
from ai.scenar.scenario.v1 import api_pb2 as ai_dot_scenar_dot_scenario_dot_v1_dot_api__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61i/scenar/scenario/v1/io.proto\x12\x15\x61i.scenar.scenario.v1\x1a&ai/scenar/commons/rpc/pagination.proto\x1a\x1f\x61i/scenar/scenario/v1/api.proto\x1a\x1b\x62uf/validate/validate.proto\"+\n\nScenarioId\x12\x1d\n\x05value\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x05value\"F\n\tScenarios\x12\x39\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1f.ai.scenar.scenario.v1.ScenarioR\x07\x65ntries\"]\n\x12ListScenariosInput\x12\x12\n\x04tags\x18\x01 \x03(\tR\x04tags\x12\x33\n\x04page\x18\x02 \x01(\x0b\x32\x1f.ai.scenar.commons.rpc.PageInfoR\x04page\"\x86\x01\n\x0bRenderInput\x12(\n\x0bscenario_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\nscenarioId\x12M\n\x06\x66ormat\x18\x02 \x01(\x0e\x32+.ai.scenar.scenario.v1.ScenarioOutputFormatB\x08\xbaH\x05\x82\x01\x02\x10\x01R\x06\x66ormat\"v\n\x0cRenderOutput\x12!\n\x0c\x61rtifact_url\x18\x01 \x01(\tR\x0b\x61rtifactUrl\x12\x43\n\x06\x66ormat\x18\x02 \x01(\x0e\x32+.ai.scenar.scenario.v1.ScenarioOutputFormatR\x06\x66ormat*[\n\x14ScenarioOutputFormat\x12\x1d\n\x19output_format_unspecified\x10\x00\x12\x15\n\x11interactive_embed\x10\x01\x12\r\n\tmp4_video\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.scenario.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENARIOID'].fields_by_name['value']._loaded_options = None
  _globals['_SCENARIOID'].fields_by_name['value']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_RENDERINPUT'].fields_by_name['scenario_id']._loaded_options = None
  _globals['_RENDERINPUT'].fields_by_name['scenario_id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_RENDERINPUT'].fields_by_name['format']._loaded_options = None
  _globals['_RENDERINPUT'].fields_by_name['format']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_SCENARIOOUTPUTFORMAT']._serialized_start=628
  _globals['_SCENARIOOUTPUTFORMAT']._serialized_end=719
  _globals['_SCENARIOID']._serialized_start=159
  _globals['_SCENARIOID']._serialized_end=202
  _globals['_SCENARIOS']._serialized_start=204
  _globals['_SCENARIOS']._serialized_end=274
  _globals['_LISTSCENARIOSINPUT']._serialized_start=276
  _globals['_LISTSCENARIOSINPUT']._serialized_end=369
  _globals['_RENDERINPUT']._serialized_start=372
  _globals['_RENDERINPUT']._serialized_end=506
  _globals['_RENDEROUTPUT']._serialized_start=508
  _globals['_RENDEROUTPUT']._serialized_end=626
# @@protoc_insertion_point(module_scope)
