# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/scenario/v1/io.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/scenario/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61i/scenar/scenario/v1/io.proto\x12\x15\x61i.scenar.scenario.v1\x1a\x1b\x62uf/validate/validate.proto\"u\n\x14ListScenariosRequest\x12\x18\n\x03org\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03org\x12$\n\tpage_size\x18\x02 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00R\x08pageSize\x12\x1d\n\npage_token\x18\x03 \x01(\tR\tpageTokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.scenario.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTSCENARIOSREQUEST'].fields_by_name['org']._loaded_options = None
  _globals['_LISTSCENARIOSREQUEST'].fields_by_name['org']._serialized_options = b'\272H\003\310\001\001'
  _globals['_LISTSCENARIOSREQUEST'].fields_by_name['page_size']._loaded_options = None
  _globals['_LISTSCENARIOSREQUEST'].fields_by_name['page_size']._serialized_options = b'\272H\004\032\002(\000'
  _globals['_LISTSCENARIOSREQUEST']._serialized_start=86
  _globals['_LISTSCENARIOSREQUEST']._serialized_end=203
# @@protoc_insertion_point(module_scope)
