# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/scenario/v1/query.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/scenario/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import io_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_io__pb2
from ai.scenar.commons.apiresource import rpc_service_options_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from ai.scenar.scenario.v1 import api_pb2 as ai_dot_scenar_dot_scenario_dot_v1_dot_api__pb2
from ai.scenar.scenario.v1 import io_pb2 as ai_dot_scenar_dot_scenario_dot_v1_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ai/scenar/scenario/v1/query.proto\x12\x15\x61i.scenar.scenario.v1\x1a&ai/scenar/commons/apiresource/io.proto\x1a\x37\x61i/scenar/commons/apiresource/rpc_service_options.proto\x1a\x1f\x61i/scenar/scenario/v1/api.proto\x1a\x1e\x61i/scenar/scenario/v1/io.proto2\xc1\x02\n\x17ScenarioQueryController\x12T\n\x03get\x12,.ai.scenar.commons.apiresource.ApiResourceId\x1a\x1f.ai.scenar.scenario.v1.Scenario\x12p\n\x0fgetByOrgAndSlug\x12<.ai.scenar.commons.apiresource.ApiResourceByOrgBySlugRequest\x1a\x1f.ai.scenar.scenario.v1.Scenario\x12X\n\x04list\x12+.ai.scenar.scenario.v1.ListScenariosRequest\x1a#.ai.scenar.scenario.v1.ScenarioList\x1a\x04\xa0\xff+\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.scenario.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENARIOQUERYCONTROLLER']._loaded_options = None
  _globals['_SCENARIOQUERYCONTROLLER']._serialized_options = b'\240\377+\001'
  _globals['_SCENARIOQUERYCONTROLLER']._serialized_start=223
  _globals['_SCENARIOQUERYCONTROLLER']._serialized_end=544
# @@protoc_insertion_point(module_scope)
