import * as path from "path";
import type { ScanResult } from "../../scanner/types.js";

/**
 * Render `views.generated.ts` — the auto-discovered component registry.
 * This file is always overwritten by `scenar install`.
 */
export function renderViewsGenerated(
  scanResult: ScanResult,
  outputDir: string,
): string {
  const components = scanResult.discovered;
  if (components.length === 0) {
    return [
      HEADER,
      "",
      "export const generatedViews = {} as const;",
      "",
    ].join("\n");
  }

  const imports: string[] = [];
  const entries: string[] = [];

  for (const comp of components) {
    const relPath = buildRelativeImport(comp.filePath, outputDir);
    if (comp.exportType === "default") {
      // Default imports bind to an arbitrary local name, so the (possibly
      // disambiguated) registry key is used directly.
      imports.push(`import ${comp.name} from "${relPath}";`);
    } else if (comp.name === comp.exportName) {
      imports.push(`import { ${comp.name} } from "${relPath}";`);
    } else {
      // Key was disambiguated away from the source export — alias on import.
      imports.push(`import { ${comp.exportName} as ${comp.name} } from "${relPath}";`);
    }
    entries.push(`  ${comp.name},`);
  }

  return [
    HEADER,
    "",
    ...imports,
    "",
    "export const generatedViews = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
}

function buildRelativeImport(
  absoluteFilePath: string,
  outputDir: string,
): string {
  let rel = path.relative(outputDir, absoluteFilePath);
  rel = rel.replace(/\.(tsx?|jsx?)$/, "");
  if (!rel.startsWith(".")) rel = "./" + rel;
  return rel;
}

const HEADER = `// AUTO-GENERATED by scenar install — do not edit.
// Re-run \`scenar install\` to update.
// To add components manually, use views.custom.tsx instead.`;
