/**
 * MSW service worker initializer.
 *
 * Generates `mockServiceWorker.js` in the project's public directory so
 * that `PreviewProvider` can intercept network requests in the browser.
 *
 * This is equivalent to running `npx msw init <publicDir>` but without
 * requiring MSW as a CLI dependency — we write a minimal service worker
 * script directly.
 */

import * as fs from "fs";
import * as path from "path";
import type { FrameworkType } from "./config.js";

const SERVICE_WORKER_FILENAME = "mockServiceWorker.js";

/**
 * Resolve the conventional public directory for a given framework.
 */
export function resolvePublicDir(
  projectRoot: string,
  framework: FrameworkType,
): string {
  switch (framework) {
    case "nextjs":
    case "vite":
    case "cra":
      return path.join(projectRoot, "public");
    case "remix":
      return path.join(projectRoot, "public");
    default:
      return path.join(projectRoot, "public");
  }
}

export interface InitMswResult {
  /** Absolute path to the written service worker file, or null if skipped. */
  readonly path: string | null;
  /** Whether the file was newly created vs already existed. */
  readonly status: "created" | "exists" | "error";
  /** Error message if status is "error". */
  readonly error?: string;
}

/**
 * Generate the MSW service worker in the project's public directory.
 *
 * If the file already exists, it is left untouched (user-owned pattern).
 * The service worker is generated by invoking MSW's CLI programmatically
 * via `npx msw init`. If MSW is not installed, a fallback minimal worker
 * script is written directly.
 *
 * @param projectRoot - Absolute path to the project root (where `public/` lives).
 * @param framework - Framework type for public directory resolution.
 */
export function initMswServiceWorker(
  projectRoot: string,
  framework: FrameworkType,
): InitMswResult {
  const publicDir = resolvePublicDir(projectRoot, framework);
  const workerPath = path.join(publicDir, SERVICE_WORKER_FILENAME);

  if (fs.existsSync(workerPath)) {
    return { path: workerPath, status: "exists" };
  }

  fs.mkdirSync(publicDir, { recursive: true });

  try {
    const { execSync } = require("child_process") as typeof import("child_process");
    execSync(`npx --yes msw init "${publicDir}" --save=false`, {
      stdio: "pipe",
      timeout: 30_000,
    });

    if (fs.existsSync(workerPath)) {
      return { path: workerPath, status: "created" };
    }
  } catch {
    // MSW CLI not available — fall through to fallback
  }

  try {
    fs.writeFileSync(workerPath, generateFallbackWorkerScript(), "utf-8");
    return { path: workerPath, status: "created" };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { path: null, status: "error", error: message };
  }
}

/**
 * Minimal service worker script that delegates to MSW's runtime.
 *
 * This is a stripped-down version of the worker that MSW generates via
 * `msw init`. It registers a fetch event listener that forwards
 * intercepted requests to the MSW client library running in the page.
 *
 * When MSW is installed and the full worker is available via `msw init`,
 * that version is preferred. This fallback covers the case where MSW
 * is only available at runtime (installed in the app) but not as a
 * CLI tool during `scenar preview init`.
 */
function generateFallbackWorkerScript(): string {
  return `\
/* eslint-disable */
/* tslint:disable */

/**
 * Mock Service Worker.
 * @see https://github.com/mswjs/msw
 * - Please do NOT modify this file.
 * - Please do NOT serve this file on production.
 *
 * Generated by scenar preview init.
 * This is a minimal fallback — run "npx msw init public/" for the full version.
 */

const PACKAGE_VERSION = "2.7.3";
const INTEGRITY_CHECKSUM = "disabled";
const IS_MOCKED_RESPONSE = Symbol("isMockedResponse");

self.addEventListener("install", function () {
  self.skipWaiting();
});

self.addEventListener("activate", function (event) {
  event.waitUntil(self.clients.claim());
});

self.addEventListener("message", async function (event) {
  const clientId = event.source.id;
  if (!clientId || !self.clients) return;

  const client = await self.clients.get(clientId);
  if (!client) return;

  const allClients = await self.clients.matchAll({ type: "window" });

  switch (event.data) {
    case "KEEPALIVE_REQUEST":
      sendToClient(client, { type: "KEEPALIVE_RESPONSE" });
      break;
    case "INTEGRITY_CHECK_REQUEST":
      sendToClient(client, {
        type: "INTEGRITY_CHECK_RESPONSE",
        payload: { packageVersion: PACKAGE_VERSION, checksum: INTEGRITY_CHECKSUM },
      });
      break;
    case "MOCK_ACTIVATE":
      activeClientIds.add(clientId);
      sendToClient(client, { type: "MOCKING_ENABLED", payload: true });
      break;
    case "MOCK_DEACTIVATE":
      activeClientIds.delete(clientId);
      break;
    case "CLIENT_CLOSED":
      activeClientIds.delete(clientId);
      const remainingClients = allClients.filter((c) => activeClientIds.has(c.id));
      if (remainingClients.length === 0) activeClientIds.clear();
      break;
  }
});

const activeClientIds = new Set();

self.addEventListener("fetch", function (event) {
  const { request } = event;

  if (request.mode === "navigate") return;

  if (activeClientIds.size === 0) return;

  const requestClone = request.clone();

  event.respondWith(
    handleRequest(event, requestClone).catch((error) => {
      console.error(
        "[MSW] Failed to mock a \\"" + request.method + "\\" request to \\"" + request.url + "\\":",
        error,
      );
      return fetch(request);
    }),
  );
});

async function handleRequest(event, request) {
  const client = await resolveMainClient(event);
  const requestId = crypto.randomUUID();
  const requestBody = ["GET", "HEAD"].includes(request.method)
    ? undefined
    : await request.text();

  sendToClient(
    client,
    {
      type: "REQUEST",
      payload: {
        id: requestId,
        url: request.url,
        method: request.method,
        headers: Object.fromEntries(request.headers.entries()),
        cache: request.cache,
        mode: request.mode,
        credentials: request.credentials,
        destination: request.destination,
        integrity: request.integrity,
        redirect: request.redirect,
        referrer: request.referrer,
        referrerPolicy: request.referrerPolicy,
        body: requestBody,
        keepalive: request.keepalive,
      },
    },
  );

  const responseEvent = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error("MSW: response timeout")), 5000);
    self.addEventListener("message", function handler(msgEvent) {
      if (
        msgEvent.data.type === "MOCK_RESPONSE" &&
        msgEvent.data.payload?.requestId === requestId
      ) {
        clearTimeout(timeout);
        self.removeEventListener("message", handler);
        resolve(msgEvent.data);
      }
    });
  });

  if (!responseEvent.payload || responseEvent.payload.type === "passthrough") {
    return fetch(request);
  }

  const { status, statusText, headers, body } = responseEvent.payload;
  const response = new Response(body, { status, statusText, headers });
  Object.defineProperty(response, IS_MOCKED_RESPONSE, { value: true, enumerable: true });
  return response;
}

function sendToClient(client, message) {
  client.postMessage(message);
}

async function resolveMainClient(event) {
  const client = await self.clients.get(event.clientId);
  if (activeClientIds.has(client?.id)) return client;

  const allClients = await self.clients.matchAll({ type: "window" });
  return allClients.filter((c) => activeClientIds.has(c.id))[0];
}
`;
}
