// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/commons/resource/kind.proto (package ai.scenar.commons.resource, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file ai/scenar/commons/resource/kind.proto.
 */
export const file_ai_scenar_commons_resource_kind: GenFile = /*@__PURE__*/
  fileDesc("CiVhaS9zY2VuYXIvY29tbW9ucy9yZXNvdXJjZS9raW5kLnByb3RvEhphaS5zY2VuYXIuY29tbW9ucy5yZXNvdXJjZSo7CgxSZXNvdXJjZUtpbmQSHQoZcmVzb3VyY2Vfa2luZF91bnNwZWNpZmllZBAAEgwKCHNjZW5hcmlvEAFiBnByb3RvMw");

/**
 * ResourceKind identifies the type of a Scenar resource.
 *
 * Used by service options (rpc_service_options.proto) to tag command
 * and query controllers with the resource they manage. Extensible as
 * Scenar adds new resource types beyond Scenario.
 *
 * @generated from enum ai.scenar.commons.resource.ResourceKind
 */
export enum ResourceKind {
  /**
   * Default value when no resource kind is set.
   *
   * @generated from enum value: resource_kind_unspecified = 0;
   */
  resource_kind_unspecified = 0,

  /**
   * A declarative scenario definition — steps, interactions,
   * viewport config, and narration scripts.
   *
   * @generated from enum value: scenario = 1;
   */
  scenario = 1,
}

/**
 * Describes the enum ai.scenar.commons.resource.ResourceKind.
 */
export const ResourceKindSchema: GenEnum<ResourceKind> = /*@__PURE__*/
  enumDesc(file_ai_scenar_commons_resource_kind, 0);

