// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/commons/resource/rpc_service_options.proto (package ai.scenar.commons.resource, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv1";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";
import type { ResourceKind } from "./kind_pb";
import { file_ai_scenar_commons_resource_kind } from "./kind_pb";
import type { ServiceOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file ai/scenar/commons/resource/rpc_service_options.proto.
 */
export const file_ai_scenar_commons_resource_rpc_service_options: GenFile = /*@__PURE__*/
  fileDesc("CjRhaS9zY2VuYXIvY29tbW9ucy9yZXNvdXJjZS9ycGNfc2VydmljZV9vcHRpb25zLnByb3RvEhphaS5zY2VuYXIuY29tbW9ucy5yZXNvdXJjZTpwCg1yZXNvdXJjZV9raW5kEh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zGNzHBSABKA4yKC5haS5zY2VuYXIuY29tbW9ucy5yZXNvdXJjZS5SZXNvdXJjZUtpbmRSDHJlc291cmNlS2luZGIGcHJvdG8z", [file_ai_scenar_commons_resource_kind, file_google_protobuf_descriptor]);

/**
 * @generated from extension: ai.scenar.commons.resource.ResourceKind resource_kind = 91100;
 */
export const resource_kind: GenExtension<ServiceOptions, ResourceKind> = /*@__PURE__*/
  extDesc(file_ai_scenar_commons_resource_rpc_service_options, 0);

