// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/scenario/v1/api.proto (package ai.scenar.scenario.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ResourceMetadata } from "../../commons/resource/metadata_pb";
import { file_ai_scenar_commons_resource_metadata } from "../../commons/resource/metadata_pb";
import type { ResourceAudit } from "../../commons/resource/status_pb";
import { file_ai_scenar_commons_resource_status } from "../../commons/resource/status_pb";
import type { ScenarioSpec } from "./spec_pb";
import { file_ai_scenar_scenario_v1_spec } from "./spec_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/scenario/v1/api.proto.
 */
export const file_ai_scenar_scenario_v1_api: GenFile = /*@__PURE__*/
  fileDesc("Ch9haS9zY2VuYXIvc2NlbmFyaW8vdjEvYXBpLnByb3RvEhVhaS5zY2VuYXIuc2NlbmFyaW8udjEihQIKCFNjZW5hcmlvEigKC2FwaV92ZXJzaW9uGAEgASgJQhO6SBByDgoMc2NlbmFyLmFpL3YxEh0KBGtpbmQYAiABKAlCD7pIDHIKCghTY2VuYXJpbxI+CghtZXRhZGF0YRgDIAEoCzIsLmFpLnNjZW5hci5jb21tb25zLnJlc291cmNlLlJlc291cmNlTWV0YWRhdGESOQoEc3BlYxgEIAEoCzIjLmFpLnNjZW5hci5zY2VuYXJpby52MS5TY2VuYXJpb1NwZWNCBrpIA8gBARI1CgZzdGF0dXMYBSABKAsyJS5haS5zY2VuYXIuc2NlbmFyaW8udjEuU2NlbmFyaW9TdGF0dXMikwEKDlNjZW5hcmlvU3RhdHVzEjgKBWF1ZGl0GGMgASgLMikuYWkuc2NlbmFyLmNvbW1vbnMucmVzb3VyY2UuUmVzb3VyY2VBdWRpdBI0ChBsYXN0X3JlbmRlcmVkX2F0GAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIRCgl2YWxpZGF0ZWQYAiABKAhiBnByb3RvMw", [file_ai_scenar_commons_resource_metadata, file_ai_scenar_commons_resource_status, file_ai_scenar_scenario_v1_spec, file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * Scenario is the top-level resource representing a declarative demo
 * definition. It follows a Kubernetes-inspired resource pattern with
 * api_version, kind, metadata, spec, and status fields.
 *
 * A Scenario fully describes a visual walkthrough: the ordered sequence
 * of component views, the cursor choreography within each step, viewport
 * configuration, and narration scripts. The same Scenario definition
 * drives both interactive web embeds (browser playback) and pixel-perfect
 * MP4 video exports (Remotion pipeline).
 *
 * Scenarios are authored in YAML or TypeScript (using generated types)
 * and validated against this proto schema. The ScenarioSpec is the core —
 * it defines what the viewer sees. Metadata provides identity and
 * categorization. Status tracks build-time state.
 *
 * Example YAML:
 *   apiVersion: scenar.ai/v1
 *   kind: Scenario
 *   metadata:
 *     name: API Key Setup
 *     slug: api-key-setup
 *     visibility: visibility_public
 *     tags: [quickstart, authentication]
 *   spec:
 *     viewport:
 *       width: 896
 *       height: 540
 *     steps:
 *       - view: new-session
 *         delay_ms: 0
 *         caption: "Start here"
 *       - view: settings-api-keys
 *         delay_ms: 1500
 *         caption: "Your API keys"
 *         interactions:
 *           - at_percent: 0.3
 *             type: hover
 *             target: create-api-key
 *
 * @generated from message ai.scenar.scenario.v1.Scenario
 */
export type Scenario = Message<"ai.scenar.scenario.v1.Scenario"> & {
  /**
   * API version for this resource type.
   *
   * @generated from field: string api_version = 1;
   */
  apiVersion: string;

  /**
   * Resource kind identifier.
   *
   * @generated from field: string kind = 2;
   */
  kind: string;

  /**
   * Standard resource metadata including name, slug, id, visibility,
   * labels, annotations, tags, and version information.
   *
   * @generated from field: ai.scenar.commons.resource.ResourceMetadata metadata = 3;
   */
  metadata?: ResourceMetadata;

  /**
   * The scenario definition — steps, interactions, and viewport config.
   *
   * @generated from field: ai.scenar.scenario.v1.ScenarioSpec spec = 4;
   */
  spec?: ScenarioSpec;

  /**
   * System-managed build state and audit trail. Populated by the
   * engine/pipeline, not by the scenario author.
   *
   * @generated from field: ai.scenar.scenario.v1.ScenarioStatus status = 5;
   */
  status?: ScenarioStatus;
};

/**
 * Describes the message ai.scenar.scenario.v1.Scenario.
 * Use `create(ScenarioSchema)` to create a new message.
 */
export const ScenarioSchema: GenMessage<Scenario> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_api, 0);

/**
 * ScenarioStatus contains system-managed state for a Scenario resource.
 * Populated by the engine or hosting service — not authored directly.
 *
 * Combines domain-specific fields (rendering state, validation) with
 * the standard audit trail (who created/updated and when).
 *
 * @generated from message ai.scenar.scenario.v1.ScenarioStatus
 */
export type ScenarioStatus = Message<"ai.scenar.scenario.v1.ScenarioStatus"> & {
  /**
   * Standard audit trail tracking creation and modification.
   *
   * @generated from field: ai.scenar.commons.resource.ResourceAudit audit = 99;
   */
  audit?: ResourceAudit;

  /**
   * Timestamp of the most recent render (interactive embed build or
   * video export). Used for cache invalidation and staleness detection.
   *
   * @generated from field: google.protobuf.Timestamp last_rendered_at = 1;
   */
  lastRenderedAt?: Timestamp;

  /**
   * Whether this scenario has been validated against the engine's
   * runtime requirements (all view identifiers resolve, interaction
   * targets exist, timing budgets are satisfied).
   *
   * @generated from field: bool validated = 2;
   */
  validated: boolean;
};

/**
 * Describes the message ai.scenar.scenario.v1.ScenarioStatus.
 * Use `create(ScenarioStatusSchema)` to create a new message.
 */
export const ScenarioStatusSchema: GenMessage<ScenarioStatus> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_api, 1);

