// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/scenario/v1/command.proto (package ai.scenar.scenario.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_ai_scenar_commons_resource_rpc_service_options } from "../../commons/resource/rpc_service_options_pb";
import type { ScenarioSchema } from "./api_pb";
import { file_ai_scenar_scenario_v1_api } from "./api_pb";
import type { RenderInputSchema, RenderOutputSchema, ScenarioIdSchema } from "./io_pb";
import { file_ai_scenar_scenario_v1_io } from "./io_pb";

/**
 * Describes the file ai/scenar/scenario/v1/command.proto.
 */
export const file_ai_scenar_scenario_v1_command: GenFile = /*@__PURE__*/
  fileDesc("CiNhaS9zY2VuYXIvc2NlbmFyaW8vdjEvY29tbWFuZC5wcm90bxIVYWkuc2NlbmFyLnNjZW5hcmlvLnYxMtoCChlTY2VuYXJpb0NvbW1hbmRDb250cm9sbGVyEkoKBmNyZWF0ZRIfLmFpLnNjZW5hci5zY2VuYXJpby52MS5TY2VuYXJpbxofLmFpLnNjZW5hci5zY2VuYXJpby52MS5TY2VuYXJpbxJKCgZ1cGRhdGUSHy5haS5zY2VuYXIuc2NlbmFyaW8udjEuU2NlbmFyaW8aHy5haS5zY2VuYXIuc2NlbmFyaW8udjEuU2NlbmFyaW8STAoGZGVsZXRlEiEuYWkuc2NlbmFyLnNjZW5hcmlvLnYxLlNjZW5hcmlvSWQaHy5haS5zY2VuYXIuc2NlbmFyaW8udjEuU2NlbmFyaW8SUQoGcmVuZGVyEiIuYWkuc2NlbmFyLnNjZW5hcmlvLnYxLlJlbmRlcklucHV0GiMuYWkuc2NlbmFyLnNjZW5hcmlvLnYxLlJlbmRlck91dHB1dBoE4L0sAWIGcHJvdG8z", [file_ai_scenar_commons_resource_rpc_service_options, file_ai_scenar_scenario_v1_api, file_ai_scenar_scenario_v1_io]);

/**
 * ScenarioCommandController provides write operations for scenario resources.
 *
 * This service defines the API surface for a future hosted Scenar service.
 * In the initial local/build-time usage, scenarios are authored as YAML or
 * TypeScript files and processed by the Scenar CLI and SDK — these RPCs
 * are not called directly. The service contract is forward-looking so that
 * the transition from local tooling to a hosted platform is seamless.
 *
 * No authorization annotations are defined initially. When Scenar becomes
 * a hosted service, auth configuration will be added per-RPC.
 *
 * @generated from service ai.scenar.scenario.v1.ScenarioCommandController
 */
export const ScenarioCommandController: GenService<{
  /**
   * Create a new scenario.
   *
   * Accepts a full Scenario resource and returns the created resource
   * with system-populated fields (metadata.id, status).
   *
   * @generated from rpc ai.scenar.scenario.v1.ScenarioCommandController.create
   */
  create: {
    methodKind: "unary";
    input: typeof ScenarioSchema;
    output: typeof ScenarioSchema;
  },
  /**
   * Update an existing scenario.
   *
   * Accepts a full Scenario resource with the target metadata.id set.
   * Returns the updated resource. Only the spec and mutable metadata
   * fields (name, description, tags) can be changed.
   *
   * @generated from rpc ai.scenar.scenario.v1.ScenarioCommandController.update
   */
  update: {
    methodKind: "unary";
    input: typeof ScenarioSchema;
    output: typeof ScenarioSchema;
  },
  /**
   * Delete a scenario by its identifier.
   *
   * Returns the deleted resource for confirmation. Deletion is
   * permanent — there is no soft-delete or trash mechanism.
   *
   * @generated from rpc ai.scenar.scenario.v1.ScenarioCommandController.delete
   */
  delete: {
    methodKind: "unary";
    input: typeof ScenarioIdSchema;
    output: typeof ScenarioSchema;
  },
  /**
   * Render a scenario into the specified output format.
   *
   * For interactive_embed: produces a deployable web component bundle.
   * For mp4_video: produces a pixel-perfect video via the Remotion pipeline.
   *
   * This is a potentially long-running operation — video rendering
   * may take seconds to minutes depending on scenario length and
   * complexity. In a hosted service, this would return a job/operation
   * resource for polling. The initial contract uses a simple
   * request/response for simplicity.
   *
   * @generated from rpc ai.scenar.scenario.v1.ScenarioCommandController.render
   */
  render: {
    methodKind: "unary";
    input: typeof RenderInputSchema;
    output: typeof RenderOutputSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ai_scenar_scenario_v1_command, 0);

