// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/scenario/v1/io.proto (package ai.scenar.scenario.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PageInfo } from "../../commons/rpc/pagination_pb";
import { file_ai_scenar_commons_rpc_pagination } from "../../commons/rpc/pagination_pb";
import type { Scenario } from "./api_pb";
import { file_ai_scenar_scenario_v1_api } from "./api_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/scenario/v1/io.proto.
 */
export const file_ai_scenar_scenario_v1_io: GenFile = /*@__PURE__*/
  fileDesc("Ch5haS9zY2VuYXIvc2NlbmFyaW8vdjEvaW8ucHJvdG8SFWFpLnNjZW5hci5zY2VuYXJpby52MSIkCgpTY2VuYXJpb0lkEhYKBXZhbHVlGAEgASgJQge6SARyAhABIj0KCVNjZW5hcmlvcxIwCgdlbnRyaWVzGAEgAygLMh8uYWkuc2NlbmFyLnNjZW5hcmlvLnYxLlNjZW5hcmlvIlEKEkxpc3RTY2VuYXJpb3NJbnB1dBIMCgR0YWdzGAEgAygJEi0KBHBhZ2UYAiABKAsyHy5haS5zY2VuYXIuY29tbW9ucy5ycGMuUGFnZUluZm8icgoLUmVuZGVySW5wdXQSHAoLc2NlbmFyaW9faWQYASABKAlCB7pIBHICEAESRQoGZm9ybWF0GAIgASgOMisuYWkuc2NlbmFyLnNjZW5hcmlvLnYxLlNjZW5hcmlvT3V0cHV0Rm9ybWF0Qgi6SAWCAQIQASJhCgxSZW5kZXJPdXRwdXQSFAoMYXJ0aWZhY3RfdXJsGAEgASgJEjsKBmZvcm1hdBgCIAEoDjIrLmFpLnNjZW5hci5zY2VuYXJpby52MS5TY2VuYXJpb091dHB1dEZvcm1hdCpbChRTY2VuYXJpb091dHB1dEZvcm1hdBIdChlvdXRwdXRfZm9ybWF0X3Vuc3BlY2lmaWVkEAASFQoRaW50ZXJhY3RpdmVfZW1iZWQQARINCgltcDRfdmlkZW8QAmIGcHJvdG8z", [file_ai_scenar_commons_rpc_pagination, file_ai_scenar_scenario_v1_api, file_buf_validate_validate]);

/**
 * ScenarioId identifies a scenario by its unique identifier.
 *
 * @generated from message ai.scenar.scenario.v1.ScenarioId
 */
export type ScenarioId = Message<"ai.scenar.scenario.v1.ScenarioId"> & {
  /**
   * Unique identifier of the scenario resource.
   *
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message ai.scenar.scenario.v1.ScenarioId.
 * Use `create(ScenarioIdSchema)` to create a new message.
 */
export const ScenarioIdSchema: GenMessage<ScenarioId> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_io, 0);

/**
 * Scenarios contains a list of scenario resources.
 *
 * @generated from message ai.scenar.scenario.v1.Scenarios
 */
export type Scenarios = Message<"ai.scenar.scenario.v1.Scenarios"> & {
  /**
   * Scenario entries.
   *
   * @generated from field: repeated ai.scenar.scenario.v1.Scenario entries = 1;
   */
  entries: Scenario[];
};

/**
 * Describes the message ai.scenar.scenario.v1.Scenarios.
 * Use `create(ScenariosSchema)` to create a new message.
 */
export const ScenariosSchema: GenMessage<Scenarios> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_io, 1);

/**
 * ListScenariosInput specifies filters for listing scenarios.
 *
 * @generated from message ai.scenar.scenario.v1.ListScenariosInput
 */
export type ListScenariosInput = Message<"ai.scenar.scenario.v1.ListScenariosInput"> & {
  /**
   * Filter by tags. When non-empty, only scenarios matching ALL
   * specified tags are returned (AND semantics).
   *
   * @generated from field: repeated string tags = 1;
   */
  tags: string[];

  /**
   * Pagination parameters.
   *
   * @generated from field: ai.scenar.commons.rpc.PageInfo page = 2;
   */
  page?: PageInfo;
};

/**
 * Describes the message ai.scenar.scenario.v1.ListScenariosInput.
 * Use `create(ListScenariosInputSchema)` to create a new message.
 */
export const ListScenariosInputSchema: GenMessage<ListScenariosInput> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_io, 2);

/**
 * RenderInput specifies which scenario to render and in what format.
 *
 * @generated from message ai.scenar.scenario.v1.RenderInput
 */
export type RenderInput = Message<"ai.scenar.scenario.v1.RenderInput"> & {
  /**
   * Identifier of the scenario to render.
   *
   * @generated from field: string scenario_id = 1;
   */
  scenarioId: string;

  /**
   * Desired output format.
   *
   * @generated from field: ai.scenar.scenario.v1.ScenarioOutputFormat format = 2;
   */
  format: ScenarioOutputFormat;
};

/**
 * Describes the message ai.scenar.scenario.v1.RenderInput.
 * Use `create(RenderInputSchema)` to create a new message.
 */
export const RenderInputSchema: GenMessage<RenderInput> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_io, 3);

/**
 * RenderOutput contains the result of a render operation.
 *
 * @generated from message ai.scenar.scenario.v1.RenderOutput
 */
export type RenderOutput = Message<"ai.scenar.scenario.v1.RenderOutput"> & {
  /**
   * URL of the rendered artifact (e.g., a hosted interactive embed
   * or an MP4 video file).
   *
   * @generated from field: string artifact_url = 1;
   */
  artifactUrl: string;

  /**
   * The format of the rendered artifact.
   *
   * @generated from field: ai.scenar.scenario.v1.ScenarioOutputFormat format = 2;
   */
  format: ScenarioOutputFormat;
};

/**
 * Describes the message ai.scenar.scenario.v1.RenderOutput.
 * Use `create(RenderOutputSchema)` to create a new message.
 */
export const RenderOutputSchema: GenMessage<RenderOutput> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_io, 4);

/**
 * ScenarioOutputFormat specifies the output format for scenario rendering.
 *
 * @generated from enum ai.scenar.scenario.v1.ScenarioOutputFormat
 */
export enum ScenarioOutputFormat {
  /**
   * Default value. The service chooses the appropriate format.
   *
   * @generated from enum value: output_format_unspecified = 0;
   */
  output_format_unspecified = 0,

  /**
   * Interactive web embed — a live React component tree that the viewer
   * can play, pause, and scrub through. This is the primary format for
   * documentation sites and landing pages.
   *
   * @generated from enum value: interactive_embed = 1;
   */
  interactive_embed = 1,

  /**
   * Pixel-perfect MP4 video produced by the Remotion pipeline. Suitable
   * for social media, presentations, and contexts where interactive
   * embeds are not supported.
   *
   * @generated from enum value: mp4_video = 2;
   */
  mp4_video = 2,
}

/**
 * Describes the enum ai.scenar.scenario.v1.ScenarioOutputFormat.
 */
export const ScenarioOutputFormatSchema: GenEnum<ScenarioOutputFormat> = /*@__PURE__*/
  enumDesc(file_ai_scenar_scenario_v1_io, 0);

