// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file ai/scenar/scenario/v1/query.proto (package ai.scenar.scenario.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListScenariosInput, ScenarioId, Scenarios } from "./io_pb.js";
import { Scenario } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ScenarioQueryController provides read operations for scenario resources.
 *
 * Like ScenarioCommandController, this service is forward-looking for a
 * future hosted Scenar platform. In local/build-time usage, scenario
 * lookup is handled by the SDK's scenario registry.
 *
 * @generated from service ai.scenar.scenario.v1.ScenarioQueryController
 */
export const ScenarioQueryController = {
  typeName: "ai.scenar.scenario.v1.ScenarioQueryController",
  methods: {
    /**
     * Get a scenario by its unique identifier.
     *
     * @generated from rpc ai.scenar.scenario.v1.ScenarioQueryController.get
     */
    get: {
      name: "get",
      I: ScenarioId,
      O: Scenario,
      kind: MethodKind.Unary,
    },
    /**
     * List scenarios with optional tag filtering and pagination.
     *
     * @generated from rpc ai.scenar.scenario.v1.ScenarioQueryController.list
     */
    list: {
      name: "list",
      I: ListScenariosInput,
      O: Scenarios,
      kind: MethodKind.Unary,
    },
  }
} as const;

