// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/scenario/v1/spec.proto (package ai.scenar.scenario.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ActionType } from "./enum_pb";
import { file_ai_scenar_scenario_v1_enum } from "./enum_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/scenario/v1/spec.proto.
 */
export const file_ai_scenar_scenario_v1_spec: GenFile = /*@__PURE__*/
  fileDesc("CiBhaS9zY2VuYXIvc2NlbmFyaW8vdjEvc3BlYy5wcm90bxIVYWkuc2NlbmFyLnNjZW5hcmlvLnYxIn0KDFNjZW5hcmlvU3BlYxI3Cgh2aWV3cG9ydBgBIAEoCzIlLmFpLnNjZW5hci5zY2VuYXJpby52MS5WaWV3cG9ydENvbmZpZxI0CgVzdGVwcxgCIAMoCzIbLmFpLnNjZW5hci5zY2VuYXJpby52MS5TdGVwQgi6SAWSAQIIASJBCg5WaWV3cG9ydENvbmZpZxIWCgV3aWR0aBgBIAEoBUIHukgEGgIgABIXCgZoZWlnaHQYAiABKAVCB7pIBBoCIAAiwgEKBFN0ZXASFQoEdmlldxgBIAEoCUIHukgEcgIQARIZCghkZWxheV9tcxgCIAEoBUIHukgEGgIoABIPCgdjYXB0aW9uGAMgASgJEhYKDm5hcnJhdGlvbl90ZXh0GAQgASgJEiYKBXByb3BzGAUgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBI3CgxpbnRlcmFjdGlvbnMYBiADKAsyIS5haS5zY2VuYXIuc2NlbmFyaW8udjEuU3RlcEFjdGlvbiKMBAoKU3RlcEFjdGlvbhIjCgphdF9wZXJjZW50GAEgASgCQg+6SAwKCh0AAIA/LQAAAAASOQoEdHlwZRgCIAEoDjIhLmFpLnNjZW5hci5zY2VuYXJpby52MS5BY3Rpb25UeXBlQgi6SAWCAQIQARIOCgZ0YXJnZXQYAyABKAkSOgoMY2xpY2tfY29uZmlnGAogASgLMiIuYWkuc2NlbmFyLnNjZW5hcmlvLnYxLkNsaWNrQ29uZmlnSAASOAoLdHlwZV9jb25maWcYCyABKAsyIS5haS5zY2VuYXIuc2NlbmFyaW8udjEuVHlwZUNvbmZpZ0gAEjoKDGhvdmVyX2NvbmZpZxgMIAEoCzIiLmFpLnNjZW5hci5zY2VuYXJpby52MS5Ib3ZlckNvbmZpZ0gAEjgKC2RyYWdfY29uZmlnGA0gASgLMiEuYWkuc2NlbmFyLnNjZW5hcmlvLnYxLkRyYWdDb25maWdIABJBChBzY3JvbGxfdG9fY29uZmlnGA4gASgLMiUuYWkuc2NlbmFyLnNjZW5hcmlvLnYxLlNjcm9sbFRvQ29uZmlnSAASVQoadmlld3BvcnRfdHJhbnNpdGlvbl9jb25maWcYDyABKAsyLy5haS5zY2VuYXIuc2NlbmFyaW8udjEuVmlld3BvcnRUcmFuc2l0aW9uQ29uZmlnSABCCAoGY29uZmlnIg0KC0NsaWNrQ29uZmlnIkMKClR5cGVDb25maWcSFQoEdGV4dBgBIAEoCUIHukgEcgIQARIeCg10eXBlX2RlbGF5X21zGAIgASgFQge6SAQaAigAIjEKC0hvdmVyQ29uZmlnEiIKEWhvdmVyX2R1cmF0aW9uX21zGAEgASgFQge6SAQaAigAIioKCkRyYWdDb25maWcSHAoLZHJhZ190YXJnZXQYASABKAlCB7pIBHICEAEiEAoOU2Nyb2xsVG9Db25maWciSQoYVmlld3BvcnRUcmFuc2l0aW9uQ29uZmlnEhUKDXZpZXdwb3J0X3pvb20YASABKAISFgoOdmlld3BvcnRfcmVzZXQYAiABKAhiBnByb3RvMw", [file_ai_scenar_scenario_v1_enum, file_buf_validate_validate, file_google_protobuf_struct]);

/**
 * ScenarioSpec defines the complete choreography of a scenario — the ordered
 * sequence of visual steps, timed cursor interactions within each step, and
 * the viewport dimensions for deterministic rendering.
 *
 * This is the core of Scenar. A ScenarioSpec fully describes what the viewer
 * sees: which component renders at each point in time, what the cursor does,
 * what text gets typed, and how the viewport transforms. The same spec drives
 * both interactive web embeds and pixel-perfect MP4 video exports.
 *
 * Example YAML:
 *   viewport:
 *     width: 896
 *     height: 540
 *   steps:
 *     - view: new-session
 *       delay_ms: 0
 *       caption: "Start here"
 *       narration_text: "Let's walk through the setup."
 *     - view: settings-api-keys
 *       delay_ms: 1500
 *       caption: "Your API keys"
 *       interactions:
 *         - at_percent: 0.3
 *           type: hover
 *           target: create-api-key
 *     - view: create-form
 *       delay_ms: 2500
 *       caption: "Name your key"
 *       interactions:
 *         - at_percent: 0.15
 *           type: type
 *           target: apikey-name-input
 *           type_config:
 *             text: "quickstart-key"
 *
 * @generated from message ai.scenar.scenario.v1.ScenarioSpec
 */
export type ScenarioSpec = Message<"ai.scenar.scenario.v1.ScenarioSpec"> & {
  /**
   * Canonical viewport dimensions for deterministic rendering.
   * When omitted, the engine uses its built-in defaults.
   *
   * @generated from field: ai.scenar.scenario.v1.ViewportConfig viewport = 1;
   */
  viewport?: ViewportConfig;

  /**
   * Ordered sequence of visual steps in the scenario timeline.
   * Step 0 is the initial state. Each subsequent step transitions
   * after its delay_ms elapses (or after the previous step's
   * narration audio completes, whichever is longer).
   *
   * @generated from field: repeated ai.scenar.scenario.v1.Step steps = 2;
   */
  steps: Step[];
};

/**
 * Describes the message ai.scenar.scenario.v1.ScenarioSpec.
 * Use `create(ScenarioSpecSchema)` to create a new message.
 */
export const ScenarioSpecSchema: GenMessage<ScenarioSpec> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 0);

/**
 * ViewportConfig defines the canonical pixel dimensions at which the scenario
 * renders internally. The engine applies CSS zoom to scale this fixed layout
 * into the available container width, guaranteeing that cursor positions,
 * scroll offsets, and interaction targets resolve against stable coordinates
 * regardless of the actual browser viewport.
 *
 * For video export, these dimensions define the virtual viewport within the
 * composition frame.
 *
 * @generated from message ai.scenar.scenario.v1.ViewportConfig
 */
export type ViewportConfig = Message<"ai.scenar.scenario.v1.ViewportConfig"> & {
  /**
   * Canonical width in pixels. The engine renders all content at this
   * width and applies CSS zoom to fit the container.
   *
   * Typical value: 896 (matches Tailwind max-w-4xl at 16px base).
   *
   * @generated from field: int32 width = 1;
   */
  width: number;

  /**
   * Canonical height in pixels. Controls the shell/container height
   * for content layout.
   *
   * Typical values: 540 for video (16:9 at 960x540), 380 for
   * interactive docs embeds.
   *
   * @generated from field: int32 height = 2;
   */
  height: number;
};

/**
 * Describes the message ai.scenar.scenario.v1.ViewportConfig.
 * Use `create(ViewportConfigSchema)` to create a new message.
 */
export const ViewportConfigSchema: GenMessage<ViewportConfig> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 1);

/**
 * Step represents a single point in the scenario timeline — a visual state
 * (which component renders) plus optional timed interactions (cursor actions,
 * typing, hovering, etc.) that occur while this step is active.
 *
 * Steps are rendered in order. The engine transitions to step N+1 after
 * max(step[N+1].delay_ms, narration_duration[N]) milliseconds. The first
 * step (index 0) renders immediately.
 *
 * The view field identifies which React component to render. The mapping
 * from view name to component is defined by the scenario author in their
 * render function — the engine treats it as an opaque string identifier.
 *
 * @generated from message ai.scenar.scenario.v1.Step
 */
export type Step = Message<"ai.scenar.scenario.v1.Step"> & {
  /**
   * Component identifier for this step. Maps to a React component via
   * the scenario's render function (e.g., "new-session", "settings-api-keys",
   * "create-form").
   *
   * The engine does not interpret this value — it passes it through to the
   * scenario's render function, which switches on it to render the
   * appropriate UI.
   *
   * @generated from field: string view = 1;
   */
  view: string;

  /**
   * Milliseconds to wait before transitioning to this step from the
   * previous one. Step 0 should use delay_ms: 0 (renders immediately).
   *
   * When narration is enabled, the actual transition time is
   * max(delay_ms, previous_step_narration_duration) — narration always
   * plays to completion before the next step begins.
   *
   * @generated from field: int32 delay_ms = 2;
   */
  delayMs: number;

  /**
   * Short label displayed below the demo content describing the current
   * action (e.g., "Click your profile", "Copy your API key"). Shown in
   * both interactive embeds and video exports.
   *
   * @generated from field: string caption = 3;
   */
  caption: string;

  /**
   * Narration script for text-to-speech generation. Consumed by the
   * build script to produce audio files — not rendered at runtime.
   *
   * When narration audio exists for this step, the engine uses the
   * audio clip duration (instead of the next step's delay_ms) for
   * step timing, ensuring the narration plays to completion.
   *
   * @generated from field: string narration_text = 4;
   */
  narrationText: string;

  /**
   * Opaque component-specific properties passed to the render function.
   * The engine does not inspect this value — it is forwarded as-is to
   * the React component identified by the view field.
   *
   * Use this for step-specific data that the component needs beyond
   * the view identifier (e.g., fixture data variations, UI state flags).
   * Most steps only need the view field and leave props empty.
   *
   * @generated from field: google.protobuf.Struct props = 5;
   */
  props?: JsonObject;

  /**
   * Timed interactions to execute while this step is active. Each
   * interaction fires at a specific point during the step's duration
   * (controlled by StepAction.at_percent).
   *
   * Interactions are executed in order. When multiple interactions
   * share the same at_percent, they fire in array order.
   *
   * To position the cursor when a step starts, add a set_cursor
   * interaction at at_percent: 0.0 — this keeps all cursor choreography
   * declarative and in one place.
   *
   * @generated from field: repeated ai.scenar.scenario.v1.StepAction interactions = 6;
   */
  interactions: StepAction[];
};

/**
 * Describes the message ai.scenar.scenario.v1.Step.
 * Use `create(StepSchema)` to create a new message.
 */
export const StepSchema: GenMessage<Step> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 2);

/**
 * StepAction defines a single timed interaction within a step — what the
 * cursor does, when it does it, and any action-specific configuration.
 *
 * The at_percent field controls timing: 0.0 fires at step start, 1.0 at
 * step end, 0.5 at the midpoint. The actual millisecond time is computed
 * from the step's duration (narration clip length or next step's delay_ms).
 *
 * The target field identifies the DOM element for cursor-based actions.
 * The engine resolves targets via data attributes (e.g., data-cursor-target
 * for cursor actions, data-scroll-target for scroll actions). The target
 * string is the attribute value, not a CSS selector.
 *
 * Example — hover at 30% of step duration:
 *   at_percent: 0.3
 *   type: hover
 *   target: "create-api-key"
 *   hover_config:
 *     hover_duration_ms: 1500
 *
 * @generated from message ai.scenar.scenario.v1.StepAction
 */
export type StepAction = Message<"ai.scenar.scenario.v1.StepAction"> & {
  /**
   * When to fire this action, as a fraction of the step's duration.
   *
   * 0.0 = step start, 1.0 = step end. The engine computes the real
   * millisecond time from the step's narration duration (if available)
   * or the next step's delay_ms (as fallback).
   *
   * Actions within a step are processed in order. When multiple actions
   * share the same at_percent, they fire sequentially in array order.
   *
   * @generated from field: float at_percent = 1;
   */
  atPercent: number;

  /**
   * The type of interaction to perform.
   *
   * @generated from field: ai.scenar.scenario.v1.ActionType type = 2;
   */
  type: ActionType;

  /**
   * Target element identifier for cursor-based actions. The engine
   * resolves this to a DOM element via data attributes.
   *
   * Required for: set_cursor, click, type, hover, drag (source),
   * scroll_to, viewport_transition.
   * Ignored for: clear_cursor.
   *
   * @generated from field: string target = 3;
   */
  target: string;

  /**
   * Action-specific configuration. Only action types that require
   * additional parameters use the config oneof — simple actions
   * (set_cursor, clear_cursor, click, scroll_to) leave it unset.
   *
   * @generated from oneof ai.scenar.scenario.v1.StepAction.config
   */
  config: {
    /**
     * Configuration for click actions. Currently empty — the click
     * target is StepAction.target. Reserved for future click options
     * (e.g., double-click, right-click).
     *
     * @generated from field: ai.scenar.scenario.v1.ClickConfig click_config = 10;
     */
    value: ClickConfig;
    case: "clickConfig";
  } | {
    /**
     * Configuration for type actions.
     *
     * @generated from field: ai.scenar.scenario.v1.TypeConfig type_config = 11;
     */
    value: TypeConfig;
    case: "typeConfig";
  } | {
    /**
     * Configuration for hover actions.
     *
     * @generated from field: ai.scenar.scenario.v1.HoverConfig hover_config = 12;
     */
    value: HoverConfig;
    case: "hoverConfig";
  } | {
    /**
     * Configuration for drag actions.
     *
     * @generated from field: ai.scenar.scenario.v1.DragConfig drag_config = 13;
     */
    value: DragConfig;
    case: "dragConfig";
  } | {
    /**
     * Configuration for scroll_to actions. Currently empty — the
     * scroll target is StepAction.target. Reserved for future scroll
     * options (e.g., scroll direction, offset).
     *
     * @generated from field: ai.scenar.scenario.v1.ScrollToConfig scroll_to_config = 14;
     */
    value: ScrollToConfig;
    case: "scrollToConfig";
  } | {
    /**
     * Configuration for viewport_transition actions.
     *
     * @generated from field: ai.scenar.scenario.v1.ViewportTransitionConfig viewport_transition_config = 15;
     */
    value: ViewportTransitionConfig;
    case: "viewportTransitionConfig";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ai.scenar.scenario.v1.StepAction.
 * Use `create(StepActionSchema)` to create a new message.
 */
export const StepActionSchema: GenMessage<StepAction> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 3);

/**
 * ClickConfig holds configuration for click actions.
 *
 * Currently empty — the click target is specified by StepAction.target.
 * This message exists as an extension point for future click variants
 * (e.g., double-click, right-click, long-press).
 *
 * @generated from message ai.scenar.scenario.v1.ClickConfig
 */
export type ClickConfig = Message<"ai.scenar.scenario.v1.ClickConfig"> & {
};

/**
 * Describes the message ai.scenar.scenario.v1.ClickConfig.
 * Use `create(ClickConfigSchema)` to create a new message.
 */
export const ClickConfigSchema: GenMessage<ClickConfig> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 4);

/**
 * TypeConfig holds configuration for type (text input) actions.
 *
 * The engine moves the cursor to StepAction.target, focuses the input
 * element, and types the text character-by-character with realistic
 * keystroke timing.
 *
 * @generated from message ai.scenar.scenario.v1.TypeConfig
 */
export type TypeConfig = Message<"ai.scenar.scenario.v1.TypeConfig"> & {
  /**
   * Text to type character-by-character into the target input element.
   *
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * Milliseconds between each character. When 0 or unset, the engine
   * uses its built-in default (typically 50ms — fast enough to feel
   * like confident typing, slow enough for each character to be
   * readable in both browser playback and video export).
   *
   * @generated from field: int32 type_delay_ms = 2;
   */
  typeDelayMs: number;
};

/**
 * Describes the message ai.scenar.scenario.v1.TypeConfig.
 * Use `create(TypeConfigSchema)` to create a new message.
 */
export const TypeConfigSchema: GenMessage<TypeConfig> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 5);

/**
 * HoverConfig holds configuration for hover (tooltip/state reveal) actions.
 *
 * The engine moves the cursor to StepAction.target, dispatches pointer/mouse
 * enter events, holds for the configured duration, then dispatches leave
 * events. The cursor does not show a click ripple during hover.
 *
 * @generated from message ai.scenar.scenario.v1.HoverConfig
 */
export type HoverConfig = Message<"ai.scenar.scenario.v1.HoverConfig"> & {
  /**
   * Milliseconds to hold the cursor over the target between enter and
   * leave events. When 0 or unset, the engine uses its built-in
   * default (typically 1500ms — enough time for viewers to notice a
   * tooltip or hover-state change).
   *
   * @generated from field: int32 hover_duration_ms = 1;
   */
  hoverDurationMs: number;
};

/**
 * Describes the message ai.scenar.scenario.v1.HoverConfig.
 * Use `create(HoverConfigSchema)` to create a new message.
 */
export const HoverConfigSchema: GenMessage<HoverConfig> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 6);

/**
 * DragConfig holds configuration for drag (drag-and-drop) actions.
 *
 * StepAction.target identifies the drag source element. This config
 * specifies the drag destination. The engine moves the cursor to the
 * source, presses, animates to the destination, and releases.
 *
 * @generated from message ai.scenar.scenario.v1.DragConfig
 */
export type DragConfig = Message<"ai.scenar.scenario.v1.DragConfig"> & {
  /**
   * Target element identifier for the drag destination. Uses the same
   * targeting mechanism as StepAction.target (e.g., data-cursor-target
   * attribute value).
   *
   * @generated from field: string drag_target = 1;
   */
  dragTarget: string;
};

/**
 * Describes the message ai.scenar.scenario.v1.DragConfig.
 * Use `create(DragConfigSchema)` to create a new message.
 */
export const DragConfigSchema: GenMessage<DragConfig> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 7);

/**
 * ScrollToConfig holds configuration for scroll_to actions.
 *
 * Currently empty — the scroll target is specified by StepAction.target,
 * and the engine scrolls it into view within its nearest scrollable
 * ancestor. This message exists as an extension point for future scroll
 * options (e.g., scroll alignment, smooth vs instant).
 *
 * @generated from message ai.scenar.scenario.v1.ScrollToConfig
 */
export type ScrollToConfig = Message<"ai.scenar.scenario.v1.ScrollToConfig"> & {
};

/**
 * Describes the message ai.scenar.scenario.v1.ScrollToConfig.
 * Use `create(ScrollToConfigSchema)` to create a new message.
 */
export const ScrollToConfigSchema: GenMessage<ScrollToConfig> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 8);

/**
 * ViewportTransitionConfig holds configuration for viewport zoom/pan
 * transitions.
 *
 * The engine computes a CSS transform (scale + translate) that centers
 * the target element in the viewport at the specified zoom level. The
 * transform persists across subsequent steps until explicitly reset.
 *
 * @generated from message ai.scenar.scenario.v1.ViewportTransitionConfig
 */
export type ViewportTransitionConfig = Message<"ai.scenar.scenario.v1.ViewportTransitionConfig"> & {
  /**
   * Zoom scale factor. Values > 1 zoom in (e.g., 2.0 = 200% magnification),
   * values < 1 zoom out. Ignored when viewport_reset is true.
   *
   * When 0 or unset, defaults to 1.5 (a moderate zoom that provides
   * detail without losing spatial context).
   *
   * @generated from field: float viewport_zoom = 1;
   */
  viewportZoom: number;

  /**
   * When true, resets the viewport to the identity transform (scale 1,
   * no translation). The target and viewport_zoom fields are ignored.
   * Use this to return to the full view after a zoom sequence.
   *
   * @generated from field: bool viewport_reset = 2;
   */
  viewportReset: boolean;
};

/**
 * Describes the message ai.scenar.scenario.v1.ViewportTransitionConfig.
 * Use `create(ViewportTransitionConfigSchema)` to create a new message.
 */
export const ViewportTransitionConfigSchema: GenMessage<ViewportTransitionConfig> = /*@__PURE__*/
  messageDesc(file_ai_scenar_scenario_v1_spec, 9);

