// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/tenancy/organization/v1/command.proto

package organizationv1

import (
	apiresource "github.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ai_scenar_tenancy_organization_v1_command_proto protoreflect.FileDescriptor

const file_ai_scenar_tenancy_organization_v1_command_proto_rawDesc = "" +
	"\n" +
	"/ai/scenar/tenancy/organization/v1/command.proto\x12!ai.scenar.tenancy.organization.v1\x1a&ai/scenar/commons/apiresource/io.proto\x1a7ai/scenar/commons/apiresource/rpc_service_options.proto\x1a+ai/scenar/tenancy/organization/v1/api.proto2\xda\x03\n" +
	"\x1dOrganizationCommandController\x12i\n" +
	"\x05apply\x12/.ai.scenar.tenancy.organization.v1.Organization\x1a/.ai.scenar.tenancy.organization.v1.Organization\x12j\n" +
	"\x06create\x12/.ai.scenar.tenancy.organization.v1.Organization\x1a/.ai.scenar.tenancy.organization.v1.Organization\x12j\n" +
	"\x06update\x12/.ai.scenar.tenancy.organization.v1.Organization\x1a/.ai.scenar.tenancy.organization.v1.Organization\x12p\n" +
	"\x06delete\x125.ai.scenar.commons.apiresource.ApiResourceDeleteInput\x1a/.ai.scenar.tenancy.organization.v1.Organization\x1a\x04\xa0\xff+\x02B\xb8\x02\n" +
	"%com.ai.scenar.tenancy.organization.v1B\fCommandProtoP\x01ZXgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/tenancy/organization/v1;organizationv1\xa2\x02\x04ASTO\xaa\x02!Ai.Scenar.Tenancy.Organization.V1\xca\x02!Ai\\Scenar\\Tenancy\\Organization\\V1\xe2\x02-Ai\\Scenar\\Tenancy\\Organization\\V1\\GPBMetadata\xea\x02%Ai::Scenar::Tenancy::Organization::V1b\x06proto3"

var file_ai_scenar_tenancy_organization_v1_command_proto_goTypes = []any{
	(*Organization)(nil),                       // 0: ai.scenar.tenancy.organization.v1.Organization
	(*apiresource.ApiResourceDeleteInput)(nil), // 1: ai.scenar.commons.apiresource.ApiResourceDeleteInput
}
var file_ai_scenar_tenancy_organization_v1_command_proto_depIdxs = []int32{
	0, // 0: ai.scenar.tenancy.organization.v1.OrganizationCommandController.apply:input_type -> ai.scenar.tenancy.organization.v1.Organization
	0, // 1: ai.scenar.tenancy.organization.v1.OrganizationCommandController.create:input_type -> ai.scenar.tenancy.organization.v1.Organization
	0, // 2: ai.scenar.tenancy.organization.v1.OrganizationCommandController.update:input_type -> ai.scenar.tenancy.organization.v1.Organization
	1, // 3: ai.scenar.tenancy.organization.v1.OrganizationCommandController.delete:input_type -> ai.scenar.commons.apiresource.ApiResourceDeleteInput
	0, // 4: ai.scenar.tenancy.organization.v1.OrganizationCommandController.apply:output_type -> ai.scenar.tenancy.organization.v1.Organization
	0, // 5: ai.scenar.tenancy.organization.v1.OrganizationCommandController.create:output_type -> ai.scenar.tenancy.organization.v1.Organization
	0, // 6: ai.scenar.tenancy.organization.v1.OrganizationCommandController.update:output_type -> ai.scenar.tenancy.organization.v1.Organization
	0, // 7: ai.scenar.tenancy.organization.v1.OrganizationCommandController.delete:output_type -> ai.scenar.tenancy.organization.v1.Organization
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_tenancy_organization_v1_command_proto_init() }
func file_ai_scenar_tenancy_organization_v1_command_proto_init() {
	if File_ai_scenar_tenancy_organization_v1_command_proto != nil {
		return
	}
	file_ai_scenar_tenancy_organization_v1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_tenancy_organization_v1_command_proto_rawDesc), len(file_ai_scenar_tenancy_organization_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_scenar_tenancy_organization_v1_command_proto_goTypes,
		DependencyIndexes: file_ai_scenar_tenancy_organization_v1_command_proto_depIdxs,
	}.Build()
	File_ai_scenar_tenancy_organization_v1_command_proto = out.File
	file_ai_scenar_tenancy_organization_v1_command_proto_goTypes = nil
	file_ai_scenar_tenancy_organization_v1_command_proto_depIdxs = nil
}
