import {
  useEffect,
  useRef,
  useState,
  type ComponentType,
  type ReactNode,
} from "react";
import {
  createMswLifecycle,
  type FixtureHandler,
} from "./msw-bridge.js";

export interface PreviewProviderProps {
  /**
   * The user's app provider chain component.
   * Generated by `scenar preview init` in `.scenar/providers.tsx`.
   */
  readonly providers?: ComponentType<{ children: ReactNode }>;
  /**
   * MSW request handlers for this scenario.
   * These mock the network layer so preview components render with data.
   */
  readonly fixtures?: readonly FixtureHandler[];
  readonly children: ReactNode;
}

/**
 * Runtime wrapper for Scenar preview playback.
 *
 * - Wraps children with the user's provider chain
 * - Sets up / tears down MSW fixture handlers for the scenario lifecycle
 * - Works in both browser (Service Worker) and Node (interceptors) environments
 */
export function PreviewProvider({
  providers: Providers,
  fixtures = [],
  children,
}: PreviewProviderProps) {
  const [ready, setReady] = useState(fixtures.length === 0);
  const lifecycleRef = useRef<Awaited<ReturnType<typeof createMswLifecycle>>>(null);

  useEffect(() => {
    if (fixtures.length === 0) {
      setReady(true);
      return;
    }

    let cancelled = false;

    void createMswLifecycle(fixtures).then(async (lifecycle) => {
      if (cancelled) return;
      lifecycleRef.current = lifecycle;
      if (lifecycle) {
        await lifecycle.start();
      }
      if (!cancelled) {
        setReady(true);
      }
    });

    return () => {
      cancelled = true;
      void lifecycleRef.current?.stop();
      lifecycleRef.current = null;
    };
  }, [fixtures]);

  if (!ready) return null;

  const content = <>{children}</>;
  return Providers ? <Providers>{content}</Providers> : content;
}
