// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/commons/apiresource/enum.proto (package ai.scenar.commons.apiresource, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file ai/scenar/commons/apiresource/enum.proto.
 */
export const file_ai_scenar_commons_apiresource_enum: GenFile = /*@__PURE__*/
  fileDesc("CihhaS9zY2VuYXIvY29tbW9ucy9hcGlyZXNvdXJjZS9lbnVtLnByb3RvEh1haS5zY2VuYXIuY29tbW9ucy5hcGlyZXNvdXJjZSpvChVBcGlSZXNvdXJjZVZpc2liaWxpdHkSJwojYXBpX3Jlc291cmNlX3Zpc2liaWxpdHlfdW5zcGVjaWZpZWQQABIWChJ2aXNpYmlsaXR5X3ByaXZhdGUQARIVChF2aXNpYmlsaXR5X3B1YmxpYxACKlsKFEFwaVJlc291cmNlRXZlbnRUeXBlEg8KC3Vuc3BlY2lmaWVkEAASCwoHY3JlYXRlZBABEgsKB3VwZGF0ZWQQAhILCgdkZWxldGVkEAMSCwoHcmVuYW1lZBAEYgZwcm90bzM");

/**
 * ApiResourceVisibility controls who can access an API resource.
 *
 * Visibility is orthogonal to ownership: ownership (the org on the resource
 * metadata) determines who *manages* a resource, while visibility determines
 * who can *access* it. Every resource belongs to exactly one organization;
 * visibility decides whether principals outside that organization may read it.
 *
 * Scenar supports two levels today (PRIVATE and PUBLIC). PUBLIC exists for
 * embeddable walkthroughs that are meant to be viewed by anyone with the embed
 * URL, while write access still requires org membership. Additional levels
 * (e.g. org-wide) can be appended later without breaking the wire format.
 *
 * The enum value *names* are the contract the platform's neutral metadata
 * reflection adapter keys off — do not rename them. The names intentionally
 * carry a `visibility_` prefix to avoid collisions with reserved keywords in
 * generated Java/Python code.
 *
 * @generated from enum ai.scenar.commons.apiresource.ApiResourceVisibility
 */
export enum ApiResourceVisibility {
  /**
   * Default/unset. The backend infers the effective visibility from context;
   * for newly created resources this resolves to visibility_private.
   *
   * @generated from enum value: api_resource_visibility_unspecified = 0;
   */
  api_resource_visibility_unspecified = 0,

  /**
   * Only members of the owning organization (and explicitly granted
   * principals) can access the resource. This is the default for new
   * resources.
   *
   * @generated from enum value: visibility_private = 1;
   */
  visibility_private = 1,

  /**
   * Anyone can read the resource. Used for published, embeddable scenarios
   * served at a public URL. Write access still requires org membership.
   *
   * @generated from enum value: visibility_public = 2;
   */
  visibility_public = 2,
}

/**
 * Describes the enum ai.scenar.commons.apiresource.ApiResourceVisibility.
 */
export const ApiResourceVisibilitySchema: GenEnum<ApiResourceVisibility> = /*@__PURE__*/
  enumDesc(file_ai_scenar_commons_apiresource_enum, 0);

/**
 * ApiResourceEventType enumerates the lifecycle events emitted by command
 * controllers across all API resources.
 *
 * A single shared enum is used (rather than a per-resource enum) because
 * events are serialized to strings when they cross message-passing
 * boundaries; the resource kind is carried alongside the event separately.
 *
 * @generated from enum ai.scenar.commons.apiresource.ApiResourceEventType
 */
export enum ApiResourceEventType {
  /**
   * Default value when no event type is set.
   *
   * @generated from enum value: unspecified = 0;
   */
  unspecified = 0,

  /**
   * The resource was created.
   *
   * @generated from enum value: created = 1;
   */
  created = 1,

  /**
   * The resource spec or status was updated.
   *
   * @generated from enum value: updated = 2;
   */
  updated = 2,

  /**
   * The resource was deleted.
   *
   * @generated from enum value: deleted = 3;
   */
  deleted = 3,

  /**
   * The resource was renamed (its slug changed).
   *
   * @generated from enum value: renamed = 4;
   */
  renamed = 4,
}

/**
 * Describes the enum ai.scenar.commons.apiresource.ApiResourceEventType.
 */
export const ApiResourceEventTypeSchema: GenEnum<ApiResourceEventType> = /*@__PURE__*/
  enumDesc(file_ai_scenar_commons_apiresource_enum, 1);

