// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=js"
// @generated from file ai/scenar/commons/apiresource/metadata.proto (package ai.scenar.commons.apiresource, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ApiResourceVisibility } from "./enum_pb.js";
import { file_ai_scenar_commons_apiresource_enum } from "./enum_pb.js";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/commons/apiresource/metadata.proto.
 */
export const file_ai_scenar_commons_apiresource_metadata: GenFile = /*@__PURE__*/
  fileDesc("CixhaS9zY2VuYXIvY29tbW9ucy9hcGlyZXNvdXJjZS9tZXRhZGF0YS5wcm90bxIdYWkuc2NlbmFyLmNvbW1vbnMuYXBpcmVzb3VyY2UitAQKE0FwaVJlc291cmNlTWV0YWRhdGESFAoEbmFtZRgBIAEoCUIGukgD2AEBEjMKBHNsdWcYAiABKAlCJbpIItgBAXIdEAIyGV5bYS16XVthLXowLTktXSpbYS16MC05XSQSCgoCaWQYAyABKAkSCwoDb3JnGAQgASgJElIKCnZpc2liaWxpdHkYBSABKA4yNC5haS5zY2VuYXIuY29tbW9ucy5hcGlyZXNvdXJjZS5BcGlSZXNvdXJjZVZpc2liaWxpdHlCCLpIBYIBAhABEk4KBmxhYmVscxgGIAMoCzI+LmFpLnNjZW5hci5jb21tb25zLmFwaXJlc291cmNlLkFwaVJlc291cmNlTWV0YWRhdGEuTGFiZWxzRW50cnkSWAoLYW5ub3RhdGlvbnMYByADKAsyQy5haS5zY2VuYXIuY29tbW9ucy5hcGlyZXNvdXJjZS5BcGlSZXNvdXJjZU1ldGFkYXRhLkFubm90YXRpb25zRW50cnkSDAoEdGFncxgIIAMoCRJKCgd2ZXJzaW9uGAkgASgLMjkuYWkuc2NlbmFyLmNvbW1vbnMuYXBpcmVzb3VyY2UuQXBpUmVzb3VyY2VNZXRhZGF0YVZlcnNpb24aLQoLTGFiZWxzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARoyChBBbm5vdGF0aW9uc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiYwoaQXBpUmVzb3VyY2VNZXRhZGF0YVZlcnNpb24SCgoCaWQYASABKAkSDwoHbWVzc2FnZRgCIAEoCRIbChNwcmV2aW91c192ZXJzaW9uX2lkGAMgASgJEgsKA3RhZxgEIAEoCWIGcHJvdG8z", [file_ai_scenar_commons_apiresource_enum, file_buf_validate_validate]);

/**
 * ApiResourceMetadata carries the standard, kind-independent metadata attached
 * to every Scenar API resource. It is the `metadata` block of the
 * Kubernetes-style resource envelope (api_version / kind / metadata / spec /
 * status).
 *
 * This message is part of Scenar's "commons contract": the Scenar Cloud
 * backend reuses the platform's shared Java libraries, which locate this block
 * reflectively by the field name `metadata` and then read its sub-fields by
 * name (`id`, `slug`, `org`, `name`, `visibility`, `version`). The field
 * *names* below are therefore a contract — renaming any of them breaks the
 * platform's metadata adapter and is rejected at service startup by the
 * platform's metadata contract validator. Field *numbers* are local to Scenar
 * and carry no cross-product meaning.
 *
 * @generated from message ai.scenar.commons.apiresource.ApiResourceMetadata
 */
export type ApiResourceMetadata = Message<"ai.scenar.commons.apiresource.ApiResourceMetadata"> & {
  /**
   * Human-readable display name of the resource.
   *
   * Validation is skipped when empty so that partial messages (server
   * responses that omit the name, patch requests, etc.) remain valid.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * URL-friendly identifier, unique within the owning organization. Combined
   * with `org` it forms the canonical reference `org/slug`.
   *
   * Format: lowercase alphanumeric characters and hyphens (minimum 2
   * characters); must start with a letter and end with a letter or digit.
   * When empty on create, the server derives the slug from `name`.
   *
   * @generated from field: string slug = 2;
   */
  slug: string;

  /**
   * System-generated unique identifier. Assigned by the server on create and
   * immutable thereafter. Prefixed per resource kind (see ApiResourceKindMeta).
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * Organization that owns this resource. Every resource belongs to exactly
   * one organization. Required and enforced by the backend's authorization
   * layer in Cloud mode.
   *
   * @generated from field: string org = 4;
   */
  org: string;

  /**
   * Access-control visibility for the resource. See ApiResourceVisibility.
   * Defaults to visibility_private for new resources.
   *
   * @generated from field: ai.scenar.commons.apiresource.ApiResourceVisibility visibility = 5;
   */
  visibility: ApiResourceVisibility;

  /**
   * Free-form key/value labels for organization and filtering.
   *
   * @generated from field: map<string, string> labels = 6;
   */
  labels: { [key: string]: string };

  /**
   * Free-form key/value annotations for additional, non-identifying metadata.
   *
   * @generated from field: map<string, string> annotations = 7;
   */
  annotations: { [key: string]: string };

  /**
   * Tags for categorization and search.
   *
   * @generated from field: repeated string tags = 8;
   */
  tags: string[];

  /**
   * Version tracking information. Populated only for versioned resource kinds.
   *
   * @generated from field: ai.scenar.commons.apiresource.ApiResourceMetadataVersion version = 9;
   */
  version?: ApiResourceMetadataVersion;
};

/**
 * Describes the message ai.scenar.commons.apiresource.ApiResourceMetadata.
 * Use `create(ApiResourceMetadataSchema)` to create a new message.
 */
export const ApiResourceMetadataSchema: GenMessage<ApiResourceMetadata> = /*@__PURE__*/
  messageDesc(file_ai_scenar_commons_apiresource_metadata, 0);

/**
 * ApiResourceMetadataVersion tracks the version of a versioned resource.
 *
 * For versioned kinds, the backend populates this on every spec-changing
 * create/update, analogous to a git commit: `id` is the content hash of the
 * new version, `message` describes the change, and `previous_version_id`
 * links to the prior version. Non-versioned kinds leave this unset.
 *
 * @generated from message ai.scenar.commons.apiresource.ApiResourceMetadataVersion
 */
export type ApiResourceMetadataVersion = Message<"ai.scenar.commons.apiresource.ApiResourceMetadataVersion"> & {
  /**
   * Unique identifier for this version. For versioned resources this is the
   * SHA-256 content hash of the spec.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-supplied description of what changed in this version, analogous to
   * a git commit message.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Identifier of the previous version, forming a linked history.
   *
   * @generated from field: string previous_version_id = 3;
   */
  previousVersionId: string;

  /**
   * Optional tag assigned to this version at creation time (e.g. "stable",
   * "v1.0", "production"). Only applicable to versioned resources.
   *
   * @generated from field: string tag = 4;
   */
  tag: string;
};

/**
 * Describes the message ai.scenar.commons.apiresource.ApiResourceMetadataVersion.
 * Use `create(ApiResourceMetadataVersionSchema)` to create a new message.
 */
export const ApiResourceMetadataVersionSchema: GenMessage<ApiResourceMetadataVersion> = /*@__PURE__*/
  messageDesc(file_ai_scenar_commons_apiresource_metadata, 1);

