# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/deploy/v1/api.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/deploy/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import metadata_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_metadata__pb2
from ai.scenar.deploy.v1 import spec_pb2 as ai_dot_scenar_dot_deploy_dot_v1_dot_spec__pb2
from ai.scenar.deploy.v1 import status_pb2 as ai_dot_scenar_dot_deploy_dot_v1_dot_status__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61i/scenar/deploy/v1/api.proto\x12\x13\x61i.scenar.deploy.v1\x1a,ai/scenar/commons/apiresource/metadata.proto\x1a\x1e\x61i/scenar/deploy/v1/spec.proto\x1a ai/scenar/deploy/v1/status.proto\x1a\x1b\x62uf/validate/validate.proto\"\xaa\x02\n\x06\x44\x65ploy\x12=\n\x0b\x61pi_version\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\n\x15scenario.scenar.ai/v1R\napiVersion\x12!\n\x04kind\x18\x02 \x01(\tB\r\xbaH\nr\x08\n\x06\x44\x65ployR\x04kind\x12N\n\x08metadata\x18\x03 \x01(\x0b\x32\x32.ai.scenar.commons.apiresource.ApiResourceMetadataR\x08metadata\x12\x33\n\x04spec\x18\x04 \x01(\x0b\x32\x1f.ai.scenar.deploy.v1.DeploySpecR\x04spec\x12\x39\n\x06status\x18\x05 \x01(\x0b\x32!.ai.scenar.deploy.v1.DeployStatusR\x06status\"\x9c\x01\n\nDeployList\x12\x1f\n\x0b\x61pi_version\x18\x01 \x01(\tR\napiVersion\x12\x12\n\x04kind\x18\x02 \x01(\tR\x04kind\x12\x31\n\x05items\x18\x03 \x03(\x0b\x32\x1b.ai.scenar.deploy.v1.DeployR\x05items\x12&\n\x0fnext_page_token\x18\x04 \x01(\tR\rnextPageTokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.deploy.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPLOY'].fields_by_name['api_version']._loaded_options = None
  _globals['_DEPLOY'].fields_by_name['api_version']._serialized_options = b'\272H\031r\027\n\025scenario.scenar.ai/v1'
  _globals['_DEPLOY'].fields_by_name['kind']._loaded_options = None
  _globals['_DEPLOY'].fields_by_name['kind']._serialized_options = b'\272H\nr\010\n\006Deploy'
  _globals['_DEPLOY']._serialized_start=196
  _globals['_DEPLOY']._serialized_end=494
  _globals['_DEPLOYLIST']._serialized_start=497
  _globals['_DEPLOYLIST']._serialized_end=653
# @@protoc_insertion_point(module_scope)
