# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/deploy/v1/status.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/deploy/v1/status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import field_options_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_field__options__pb2
from ai.scenar.commons.apiresource import status_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_status__pb2
from ai.scenar.deploy.v1 import enum_pb2 as ai_dot_scenar_dot_deploy_dot_v1_dot_enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ai/scenar/deploy/v1/status.proto\x12\x13\x61i.scenar.deploy.v1\x1a\x31\x61i/scenar/commons/apiresource/field_options.proto\x1a*ai/scenar/commons/apiresource/status.proto\x1a\x1e\x61i/scenar/deploy/v1/enum.proto\"\x91\x02\n\x0c\x44\x65ployStatus\x12<\n\x05state\x18\x01 \x01(\x0e\x32 .ai.scenar.deploy.v1.DeployStateB\x04\xc8\x85,\x01R\x05state\x12!\n\tembed_url\x18\x02 \x01(\tB\x04\xc8\x85,\x01R\x08\x65mbedUrl\x12\x30\n\x11object_key_prefix\x18\x03 \x01(\tB\x04\xc8\x85,\x01R\x0fobjectKeyPrefix\x12\'\n\x0c\x65rror_reason\x18\x04 \x01(\tB\x04\xc8\x85,\x01R\x0b\x65rrorReason\x12\x45\n\x05\x61udit\x18\x63 \x01(\x0b\x32/.ai.scenar.commons.apiresource.ApiResourceAuditR\x05\x61uditb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.deploy.v1.status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPLOYSTATUS'].fields_by_name['state']._loaded_options = None
  _globals['_DEPLOYSTATUS'].fields_by_name['state']._serialized_options = b'\310\205,\001'
  _globals['_DEPLOYSTATUS'].fields_by_name['embed_url']._loaded_options = None
  _globals['_DEPLOYSTATUS'].fields_by_name['embed_url']._serialized_options = b'\310\205,\001'
  _globals['_DEPLOYSTATUS'].fields_by_name['object_key_prefix']._loaded_options = None
  _globals['_DEPLOYSTATUS'].fields_by_name['object_key_prefix']._serialized_options = b'\310\205,\001'
  _globals['_DEPLOYSTATUS'].fields_by_name['error_reason']._loaded_options = None
  _globals['_DEPLOYSTATUS'].fields_by_name['error_reason']._serialized_options = b'\310\205,\001'
  _globals['_DEPLOYSTATUS']._serialized_start=185
  _globals['_DEPLOYSTATUS']._serialized_end=458
# @@protoc_insertion_point(module_scope)
