# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/commons/rpc/authorization_config.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/commons/rpc/authorization_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource.apiresourcekind import api_resource_kind_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_apiresourcekind_dot_api__resource__kind__pb2
from ai.scenar.iam.v1 import enum_pb2 as ai_dot_scenar_dot_iam_dot_v1_dot_enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0ai/scenar/commons/rpc/authorization_config.proto\x12\x15\x61i.scenar.commons.rpc\x1a\x45\x61i/scenar/commons/apiresource/apiresourcekind/api_resource_kind.proto\x1a\x1b\x61i/scenar/iam/v1/enum.proto\"\xc9\x02\n\x16RpcAuthorizationConfig\x12?\n\npermission\x18\x01 \x01(\x0e\x32\x1f.ai.scenar.iam.v1.IamPermissionR\npermission\x12\x63\n\rresource_kind\x18\x02 \x01(\x0e\x32>.ai.scenar.commons.apiresource.apiresourcekind.ApiResourceKindR\x0cresourceKind\x12,\n\x12resource_kind_path\x18\x03 \x01(\tR\x10resourceKindPath\x12\x1d\n\nfield_path\x18\x04 \x01(\tR\tfieldPath\x12\x1b\n\terror_msg\x18\x05 \x01(\tR\x08\x65rrorMsg\x12\x1f\n\x0bresource_id\x18\x06 \x01(\tR\nresourceIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.commons.rpc.authorization_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPCAUTHORIZATIONCONFIG']._serialized_start=176
  _globals['_RPCAUTHORIZATIONCONFIG']._serialized_end=505
# @@protoc_insertion_point(module_scope)
