# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/commons/rpc/method_options.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/commons/rpc/method_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.rpc import authorization_config_pb2 as ai_dot_scenar_dot_commons_dot_rpc_dot_authorization__config__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*ai/scenar/commons/rpc/method_options.proto\x12\x15\x61i.scenar.commons.rpc\x1a\x30\x61i/scenar/commons/rpc/authorization_config.proto\x1a google/protobuf/descriptor.proto:g\n\x06\x63onfig\x12\x1e.google.protobuf.MethodOptions\x18\x88\x87\x03 \x01(\x0b\x32-.ai.scenar.commons.rpc.RpcAuthorizationConfigR\x06\x63onfig:=\n\tis_public\x12\x1e.google.protobuf.MethodOptions\x18\x89\x87\x03 \x01(\x08R\x08isPublic:T\n\x15is_skip_authorization\x12\x1e.google.protobuf.MethodOptions\x18\x8a\x87\x03 \x01(\x08R\x13isSkipAuthorizationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.commons.rpc.method_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
