// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/iam/identityaccount/v1/command.proto (package ai.scenar.iam.identityaccount.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_ai_scenar_commons_apiresource_rpc_service_options } from "../../../commons/apiresource/rpc_service_options_pb";
import type { IdentityAccountSchema } from "./api_pb";
import { file_ai_scenar_iam_identityaccount_v1_api } from "./api_pb";

/**
 * Describes the file ai/scenar/iam/identityaccount/v1/command.proto.
 */
export const file_ai_scenar_iam_identityaccount_v1_command: GenFile = /*@__PURE__*/
  fileDesc("Ci5haS9zY2VuYXIvaWFtL2lkZW50aXR5YWNjb3VudC92MS9jb21tYW5kLnByb3RvEiBhaS5zY2VuYXIuaWFtLmlkZW50aXR5YWNjb3VudC52MTKYAQogSWRlbnRpdHlBY2NvdW50Q29tbWFuZENvbnRyb2xsZXISbgoGY3JlYXRlEjEuYWkuc2NlbmFyLmlhbS5pZGVudGl0eWFjY291bnQudjEuSWRlbnRpdHlBY2NvdW50GjEuYWkuc2NlbmFyLmlhbS5pZGVudGl0eWFjY291bnQudjEuSWRlbnRpdHlBY2NvdW50GgSg/ysLYgZwcm90bzM", [file_ai_scenar_commons_apiresource_rpc_service_options, file_ai_scenar_iam_identityaccount_v1_api]);

/**
 * IdentityAccountCommandController provides the write operations for identity
 * account resources — the principals every authorization decision is made
 * about. It is the contract the Scenar Cloud backend implements when accounts
 * are provisioned.
 *
 * These RPCs are internal, in-process calls made by the Cloud backend itself
 * (the authentication/provisioning flow and the day-0 bootstrap migration),
 * never exposed to external clients. The controller therefore carries only the
 * one write operation the backend consumes today:
 *
 *   - create: provision a new identity account (the principal-creation path).
 *
 * The federated-account write operations from the platform's full surface
 * (createFederatedAccount / updateFederatedAccount / deprovisionFederatedAccount)
 * are intentionally omitted until a federated-provisioning flow exists, keeping
 * the OSS contract free of unused RPC surface — the same discipline the apikey
 * and iampolicy controllers apply to their omitted operations. Their request
 * messages already live in io.proto; only the service surface is deferred.
 *
 * Authorization note: as with the apikey and iampolicy controllers, per-RPC
 * authorization options are intentionally absent until Scenar adopts a neutral
 * method-level auth contract. These RPCs carry only the service-level
 * resource-kind tag; the Cloud backend enforces authorization in its handlers.
 * create is a special case with no FGA authorize step at all: it is called only
 * over the system channel, and the account being created is itself the
 * principal — there is no tuple to authorize against until it exists (the same
 * bootstrap problem bootstrapPolicy solves on the iampolicy side).
 *
 * @generated from service ai.scenar.iam.identityaccount.v1.IdentityAccountCommandController
 */
export const IdentityAccountCommandController: GenService<{
  /**
   * Provision a new identity account. The caller supplies the spec (idp_id and,
   * for human accounts, profile fields); the backend generates the id, stamps
   * metadata/audit, persists to MongoDB, and writes the account's initial
   * authorization tuple — the self-owner grant — via bootstrapPolicy
   * (identity_account is owner-only scope with self ownership, so there is no
   * platform or org link). The account being created is the principal, so this
   * carries no FGA authorize step and is restricted to the system channel.
   * See IdentityAccount.
   *
   * @generated from rpc ai.scenar.iam.identityaccount.v1.IdentityAccountCommandController.create
   */
  create: {
    methodKind: "unary";
    input: typeof IdentityAccountSchema;
    output: typeof IdentityAccountSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ai_scenar_iam_identityaccount_v1_command, 0);

