// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=js"
// @generated from file ai/scenar/iam/identityaccount/v1/query.proto (package ai.scenar.iam.identityaccount.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_ai_scenar_commons_apiresource_rpc_service_options } from "../../../commons/apiresource/rpc_service_options_pb.js";
import type { IdentityAccountSchema } from "./api_pb.js";
import { file_ai_scenar_iam_identityaccount_v1_api } from "./api_pb.js";
import type { CurrentSessionSchema, IdentityAccountEmailSchema, IdentityAccountIdSchema, IdpIdSchema } from "./io_pb.js";
import { file_ai_scenar_iam_identityaccount_v1_io } from "./io_pb.js";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file ai/scenar/iam/identityaccount/v1/query.proto.
 */
export const file_ai_scenar_iam_identityaccount_v1_query: GenFile = /*@__PURE__*/
  fileDesc("CixhaS9zY2VuYXIvaWFtL2lkZW50aXR5YWNjb3VudC92MS9xdWVyeS5wcm90bxIgYWkuc2NlbmFyLmlhbS5pZGVudGl0eWFjY291bnQudjEy0AMKHklkZW50aXR5QWNjb3VudFF1ZXJ5Q29udHJvbGxlchJxCgdnZXRCeUlkEjMuYWkuc2NlbmFyLmlhbS5pZGVudGl0eWFjY291bnQudjEuSWRlbnRpdHlBY2NvdW50SWQaMS5haS5zY2VuYXIuaWFtLmlkZW50aXR5YWNjb3VudC52MS5JZGVudGl0eUFjY291bnQSaAoKZ2V0QnlJZHBJZBInLmFpLnNjZW5hci5pYW0uaWRlbnRpdHlhY2NvdW50LnYxLklkcElkGjEuYWkuc2NlbmFyLmlhbS5pZGVudGl0eWFjY291bnQudjEuSWRlbnRpdHlBY2NvdW50EncKCmdldEJ5RW1haWwSNi5haS5zY2VuYXIuaWFtLmlkZW50aXR5YWNjb3VudC52MS5JZGVudGl0eUFjY291bnRFbWFpbBoxLmFpLnNjZW5hci5pYW0uaWRlbnRpdHlhY2NvdW50LnYxLklkZW50aXR5QWNjb3VudBJSCgZ3aG9BbUkSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaMC5haS5zY2VuYXIuaWFtLmlkZW50aXR5YWNjb3VudC52MS5DdXJyZW50U2Vzc2lvbhoEoP8rC2IGcHJvdG8z", [file_ai_scenar_commons_apiresource_rpc_service_options, file_ai_scenar_iam_identityaccount_v1_api, file_ai_scenar_iam_identityaccount_v1_io, file_google_protobuf_empty]);

/**
 * IdentityAccountQueryController provides the read operations for identity
 * account resources. It serves two distinct audiences:
 *
 *   - getById / getByIdpId / getByEmail are internal, in-process calls the
 *     backend makes to resolve accounts at authentication time (idp_id / email
 *     lookups) and for cache-proxy fallbacks (id lookups).
 *   - whoAmI is the one client-facing read on this controller: the web console
 *     calls it across the network to learn who the authenticated caller is.
 *
 * The lookup trio carries the three resolutions the backend consumes:
 *
 *   - getById    : resolve by system id (metadata.id) — the cache-miss path.
 *   - getByIdpId : resolve by identity-provider subject (Auth0 user_id /
 *                  client_id) — the authentication path.
 *   - getByEmail : resolve by email address.
 *
 * There is no getActorInfo RPC: the lightweight actor projection (id + avatar)
 * is derived client-side from getById in the repo implementation, so the audit
 * surface stays free of a redundant RPC.
 *
 * Authorization note: per-RPC authorization options are intentionally absent
 * until Scenar adopts a neutral method-level auth contract. The lookup trio
 * enforces a dual check in its handler — owner can_view on the specific
 * identity_account, falling back to platform-operator
 * can_manage_identity_accounts on the platform singleton — so both self-access
 * and system-level resolution (over the system channel) are permitted. whoAmI
 * is self-scoped: it acts only on the authenticated caller, so it requires
 * authentication but no FGA authorization step.
 *
 * @generated from service ai.scenar.iam.identityaccount.v1.IdentityAccountQueryController
 */
export const IdentityAccountQueryController: GenService<{
  /**
   * Get an identity account by its system-generated id (metadata.id). The
   * cache-miss resolution path for actor/identity proxies. See IdentityAccountId.
   *
   * @generated from rpc ai.scenar.iam.identityaccount.v1.IdentityAccountQueryController.getById
   */
  getById: {
    methodKind: "unary";
    input: typeof IdentityAccountIdSchema;
    output: typeof IdentityAccountSchema;
  },
  /**
   * Resolve an identity account by its identity-provider id — the Auth0 subject
   * (user_id for humans, client_id@clients for machine accounts). This is the
   * authentication-time lookup. See IdpId.
   *
   * @generated from rpc ai.scenar.iam.identityaccount.v1.IdentityAccountQueryController.getByIdpId
   */
  getByIdpId: {
    methodKind: "unary";
    input: typeof IdpIdSchema;
    output: typeof IdentityAccountSchema;
  },
  /**
   * Resolve an identity account by email address. See IdentityAccountEmail.
   *
   * @generated from rpc ai.scenar.iam.identityaccount.v1.IdentityAccountQueryController.getByEmail
   */
  getByEmail: {
    methodKind: "unary";
    input: typeof IdentityAccountEmailSchema;
    output: typeof IdentityAccountSchema;
  },
  /**
   * Resolve the authenticated caller to its own session — the identity account
   * plus the organizations it can act in. The web console calls this on load to
   * decide what to render.
   *
   * Identity comes entirely from the authenticated request context (the verified
   * JWT subject); there is no request payload. Returns NOT_FOUND when the caller
   * has authenticated but has no identity account yet — the signal the console
   * uses to call provisionMyAccount (first login). See CurrentSession.
   *
   * @generated from rpc ai.scenar.iam.identityaccount.v1.IdentityAccountQueryController.whoAmI
   */
  whoAmI: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof CurrentSessionSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ai_scenar_iam_identityaccount_v1_query, 0);

