// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/scenario/v1/api.proto

package scenariov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	resource "github.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/commons/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scenario is the top-level resource representing a declarative demo
// definition. It follows a Kubernetes-inspired resource pattern with
// api_version, kind, metadata, spec, and status fields.
//
// A Scenario fully describes a visual walkthrough: the ordered sequence
// of component views, the cursor choreography within each step, viewport
// configuration, and narration scripts. The same Scenario definition
// drives both interactive web embeds (browser playback) and pixel-perfect
// MP4 video exports (Remotion pipeline).
//
// Scenarios are authored in YAML or TypeScript (using generated types)
// and validated against this proto schema. The ScenarioSpec is the core —
// it defines what the viewer sees. Metadata provides identity and
// categorization. Status tracks build-time state.
//
// Example YAML:
//
//	apiVersion: scenar.ai/v1
//	kind: Scenario
//	metadata:
//	  name: API Key Setup
//	  slug: api-key-setup
//	  visibility: visibility_public
//	  tags: [quickstart, authentication]
//	spec:
//	  viewport:
//	    width: 896
//	    height: 540
//	  steps:
//	    - view: new-session
//	      delay_ms: 0
//	      caption: "Start here"
//	    - view: settings-api-keys
//	      delay_ms: 1500
//	      caption: "Your API keys"
//	      interactions:
//	        - at_percent: 0.3
//	          type: hover
//	          target: create-api-key
type Scenario struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version for this resource type.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Resource kind identifier.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Standard resource metadata including name, slug, id, visibility,
	// labels, annotations, tags, and version information.
	Metadata *resource.ResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The scenario definition — steps, interactions, and viewport config.
	Spec *ScenarioSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// System-managed build state and audit trail. Populated by the
	// engine/pipeline, not by the scenario author.
	Status        *ScenarioStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_ai_scenar_scenario_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Scenario) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Scenario) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Scenario) GetMetadata() *resource.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Scenario) GetSpec() *ScenarioSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Scenario) GetStatus() *ScenarioStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ScenarioStatus contains system-managed state for a Scenario resource.
// Populated by the engine or hosting service — not authored directly.
//
// Combines domain-specific fields (rendering state, validation) with
// the standard audit trail (who created/updated and when).
type ScenarioStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard audit trail tracking creation and modification.
	Audit *resource.ResourceAudit `protobuf:"bytes,99,opt,name=audit,proto3" json:"audit,omitempty"`
	// Timestamp of the most recent render (interactive embed build or
	// video export). Used for cache invalidation and staleness detection.
	LastRenderedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_rendered_at,json=lastRenderedAt,proto3" json:"last_rendered_at,omitempty"`
	// Whether this scenario has been validated against the engine's
	// runtime requirements (all view identifiers resolve, interaction
	// targets exist, timing budgets are satisfied).
	Validated     bool `protobuf:"varint,2,opt,name=validated,proto3" json:"validated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioStatus) Reset() {
	*x = ScenarioStatus{}
	mi := &file_ai_scenar_scenario_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioStatus) ProtoMessage() {}

func (x *ScenarioStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioStatus.ProtoReflect.Descriptor instead.
func (*ScenarioStatus) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ScenarioStatus) GetAudit() *resource.ResourceAudit {
	if x != nil {
		return x.Audit
	}
	return nil
}

func (x *ScenarioStatus) GetLastRenderedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRenderedAt
	}
	return nil
}

func (x *ScenarioStatus) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

var File_ai_scenar_scenario_v1_api_proto protoreflect.FileDescriptor

const file_ai_scenar_scenario_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x1fai/scenar/scenario/v1/api.proto\x12\x15ai.scenar.scenario.v1\x1a)ai/scenar/commons/resource/metadata.proto\x1a'ai/scenar/commons/resource/status.proto\x1a ai/scenar/scenario/v1/spec.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\bScenario\x124\n" +
	"\vapi_version\x18\x01 \x01(\tB\x13\xbaH\x10r\x0e\n" +
	"\fscenar.ai/v1R\n" +
	"apiVersion\x12#\n" +
	"\x04kind\x18\x02 \x01(\tB\x0f\xbaH\fr\n" +
	"\n" +
	"\bScenarioR\x04kind\x12H\n" +
	"\bmetadata\x18\x03 \x01(\v2,.ai.scenar.commons.resource.ResourceMetadataR\bmetadata\x12?\n" +
	"\x04spec\x18\x04 \x01(\v2#.ai.scenar.scenario.v1.ScenarioSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12=\n" +
	"\x06status\x18\x05 \x01(\v2%.ai.scenar.scenario.v1.ScenarioStatusR\x06status\"\xb5\x01\n" +
	"\x0eScenarioStatus\x12?\n" +
	"\x05audit\x18c \x01(\v2).ai.scenar.commons.resource.ResourceAuditR\x05audit\x12D\n" +
	"\x10last_rendered_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastRenderedAt\x12\x1c\n" +
	"\tvalidated\x18\x02 \x01(\bR\tvalidatedB\xe8\x01\n" +
	"\x19com.ai.scenar.scenario.v1B\bApiProtoP\x01ZJgithub.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/scenario/v1;scenariov1\xa2\x02\x03ASS\xaa\x02\x15Ai.Scenar.Scenario.V1\xca\x02\x15Ai\\Scenar\\Scenario\\V1\xe2\x02!Ai\\Scenar\\Scenario\\V1\\GPBMetadata\xea\x02\x18Ai::Scenar::Scenario::V1b\x06proto3"

var (
	file_ai_scenar_scenario_v1_api_proto_rawDescOnce sync.Once
	file_ai_scenar_scenario_v1_api_proto_rawDescData []byte
)

func file_ai_scenar_scenario_v1_api_proto_rawDescGZIP() []byte {
	file_ai_scenar_scenario_v1_api_proto_rawDescOnce.Do(func() {
		file_ai_scenar_scenario_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_api_proto_rawDesc), len(file_ai_scenar_scenario_v1_api_proto_rawDesc)))
	})
	return file_ai_scenar_scenario_v1_api_proto_rawDescData
}

var file_ai_scenar_scenario_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_scenar_scenario_v1_api_proto_goTypes = []any{
	(*Scenario)(nil),                  // 0: ai.scenar.scenario.v1.Scenario
	(*ScenarioStatus)(nil),            // 1: ai.scenar.scenario.v1.ScenarioStatus
	(*resource.ResourceMetadata)(nil), // 2: ai.scenar.commons.resource.ResourceMetadata
	(*ScenarioSpec)(nil),              // 3: ai.scenar.scenario.v1.ScenarioSpec
	(*resource.ResourceAudit)(nil),    // 4: ai.scenar.commons.resource.ResourceAudit
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_ai_scenar_scenario_v1_api_proto_depIdxs = []int32{
	2, // 0: ai.scenar.scenario.v1.Scenario.metadata:type_name -> ai.scenar.commons.resource.ResourceMetadata
	3, // 1: ai.scenar.scenario.v1.Scenario.spec:type_name -> ai.scenar.scenario.v1.ScenarioSpec
	1, // 2: ai.scenar.scenario.v1.Scenario.status:type_name -> ai.scenar.scenario.v1.ScenarioStatus
	4, // 3: ai.scenar.scenario.v1.ScenarioStatus.audit:type_name -> ai.scenar.commons.resource.ResourceAudit
	5, // 4: ai.scenar.scenario.v1.ScenarioStatus.last_rendered_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ai_scenar_scenario_v1_api_proto_init() }
func file_ai_scenar_scenario_v1_api_proto_init() {
	if File_ai_scenar_scenario_v1_api_proto != nil {
		return
	}
	file_ai_scenar_scenario_v1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_api_proto_rawDesc), len(file_ai_scenar_scenario_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_scenario_v1_api_proto_goTypes,
		DependencyIndexes: file_ai_scenar_scenario_v1_api_proto_depIdxs,
		MessageInfos:      file_ai_scenar_scenario_v1_api_proto_msgTypes,
	}.Build()
	File_ai_scenar_scenario_v1_api_proto = out.File
	file_ai_scenar_scenario_v1_api_proto_goTypes = nil
	file_ai_scenar_scenario_v1_api_proto_depIdxs = nil
}
