// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ai/scenar/scenario/v1/command.proto

package scenariov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScenarioCommandController_Create_FullMethodName = "/ai.scenar.scenario.v1.ScenarioCommandController/create"
	ScenarioCommandController_Update_FullMethodName = "/ai.scenar.scenario.v1.ScenarioCommandController/update"
	ScenarioCommandController_Delete_FullMethodName = "/ai.scenar.scenario.v1.ScenarioCommandController/delete"
	ScenarioCommandController_Render_FullMethodName = "/ai.scenar.scenario.v1.ScenarioCommandController/render"
)

// ScenarioCommandControllerClient is the client API for ScenarioCommandController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScenarioCommandController provides write operations for scenario resources.
//
// This service defines the API surface for a future hosted Scenar service.
// In the initial local/build-time usage, scenarios are authored as YAML or
// TypeScript files and processed by the Scenar CLI and SDK — these RPCs
// are not called directly. The service contract is forward-looking so that
// the transition from local tooling to a hosted platform is seamless.
//
// No authorization annotations are defined initially. When Scenar becomes
// a hosted service, auth configuration will be added per-RPC.
type ScenarioCommandControllerClient interface {
	// Create a new scenario.
	//
	// Accepts a full Scenario resource and returns the created resource
	// with system-populated fields (metadata.id, status).
	Create(ctx context.Context, in *Scenario, opts ...grpc.CallOption) (*Scenario, error)
	// Update an existing scenario.
	//
	// Accepts a full Scenario resource with the target metadata.id set.
	// Returns the updated resource. Only the spec and mutable metadata
	// fields (name, description, tags) can be changed.
	Update(ctx context.Context, in *Scenario, opts ...grpc.CallOption) (*Scenario, error)
	// Delete a scenario by its identifier.
	//
	// Returns the deleted resource for confirmation. Deletion is
	// permanent — there is no soft-delete or trash mechanism.
	Delete(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Scenario, error)
	// Render a scenario into the specified output format.
	//
	// For interactive_embed: produces a deployable web component bundle.
	// For mp4_video: produces a pixel-perfect video via the Remotion pipeline.
	//
	// This is a potentially long-running operation — video rendering
	// may take seconds to minutes depending on scenario length and
	// complexity. In a hosted service, this would return a job/operation
	// resource for polling. The initial contract uses a simple
	// request/response for simplicity.
	Render(ctx context.Context, in *RenderInput, opts ...grpc.CallOption) (*RenderOutput, error)
}

type scenarioCommandControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewScenarioCommandControllerClient(cc grpc.ClientConnInterface) ScenarioCommandControllerClient {
	return &scenarioCommandControllerClient{cc}
}

func (c *scenarioCommandControllerClient) Create(ctx context.Context, in *Scenario, opts ...grpc.CallOption) (*Scenario, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scenario)
	err := c.cc.Invoke(ctx, ScenarioCommandController_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioCommandControllerClient) Update(ctx context.Context, in *Scenario, opts ...grpc.CallOption) (*Scenario, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scenario)
	err := c.cc.Invoke(ctx, ScenarioCommandController_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioCommandControllerClient) Delete(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Scenario, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scenario)
	err := c.cc.Invoke(ctx, ScenarioCommandController_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioCommandControllerClient) Render(ctx context.Context, in *RenderInput, opts ...grpc.CallOption) (*RenderOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderOutput)
	err := c.cc.Invoke(ctx, ScenarioCommandController_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScenarioCommandControllerServer is the server API for ScenarioCommandController service.
// All implementations should embed UnimplementedScenarioCommandControllerServer
// for forward compatibility.
//
// ScenarioCommandController provides write operations for scenario resources.
//
// This service defines the API surface for a future hosted Scenar service.
// In the initial local/build-time usage, scenarios are authored as YAML or
// TypeScript files and processed by the Scenar CLI and SDK — these RPCs
// are not called directly. The service contract is forward-looking so that
// the transition from local tooling to a hosted platform is seamless.
//
// No authorization annotations are defined initially. When Scenar becomes
// a hosted service, auth configuration will be added per-RPC.
type ScenarioCommandControllerServer interface {
	// Create a new scenario.
	//
	// Accepts a full Scenario resource and returns the created resource
	// with system-populated fields (metadata.id, status).
	Create(context.Context, *Scenario) (*Scenario, error)
	// Update an existing scenario.
	//
	// Accepts a full Scenario resource with the target metadata.id set.
	// Returns the updated resource. Only the spec and mutable metadata
	// fields (name, description, tags) can be changed.
	Update(context.Context, *Scenario) (*Scenario, error)
	// Delete a scenario by its identifier.
	//
	// Returns the deleted resource for confirmation. Deletion is
	// permanent — there is no soft-delete or trash mechanism.
	Delete(context.Context, *ScenarioId) (*Scenario, error)
	// Render a scenario into the specified output format.
	//
	// For interactive_embed: produces a deployable web component bundle.
	// For mp4_video: produces a pixel-perfect video via the Remotion pipeline.
	//
	// This is a potentially long-running operation — video rendering
	// may take seconds to minutes depending on scenario length and
	// complexity. In a hosted service, this would return a job/operation
	// resource for polling. The initial contract uses a simple
	// request/response for simplicity.
	Render(context.Context, *RenderInput) (*RenderOutput, error)
}

// UnimplementedScenarioCommandControllerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScenarioCommandControllerServer struct{}

func (UnimplementedScenarioCommandControllerServer) Create(context.Context, *Scenario) (*Scenario, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedScenarioCommandControllerServer) Update(context.Context, *Scenario) (*Scenario, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedScenarioCommandControllerServer) Delete(context.Context, *ScenarioId) (*Scenario, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedScenarioCommandControllerServer) Render(context.Context, *RenderInput) (*RenderOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedScenarioCommandControllerServer) testEmbeddedByValue() {}

// UnsafeScenarioCommandControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScenarioCommandControllerServer will
// result in compilation errors.
type UnsafeScenarioCommandControllerServer interface {
	mustEmbedUnimplementedScenarioCommandControllerServer()
}

func RegisterScenarioCommandControllerServer(s grpc.ServiceRegistrar, srv ScenarioCommandControllerServer) {
	// If the following call pancis, it indicates UnimplementedScenarioCommandControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScenarioCommandController_ServiceDesc, srv)
}

func _ScenarioCommandController_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Scenario)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioCommandControllerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioCommandController_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioCommandControllerServer).Create(ctx, req.(*Scenario))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioCommandController_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Scenario)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioCommandControllerServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioCommandController_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioCommandControllerServer).Update(ctx, req.(*Scenario))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioCommandController_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioCommandControllerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioCommandController_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioCommandControllerServer).Delete(ctx, req.(*ScenarioId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioCommandController_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioCommandControllerServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioCommandController_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioCommandControllerServer).Render(ctx, req.(*RenderInput))
	}
	return interceptor(ctx, in, info, handler)
}

// ScenarioCommandController_ServiceDesc is the grpc.ServiceDesc for ScenarioCommandController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScenarioCommandController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.scenar.scenario.v1.ScenarioCommandController",
	HandlerType: (*ScenarioCommandControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _ScenarioCommandController_Create_Handler,
		},
		{
			MethodName: "update",
			Handler:    _ScenarioCommandController_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _ScenarioCommandController_Delete_Handler,
		},
		{
			MethodName: "render",
			Handler:    _ScenarioCommandController_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai/scenar/scenario/v1/command.proto",
}
