// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/scenario/v1/command.proto

package scenariov1

import (
	_ "github.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/commons/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ai_scenar_scenario_v1_command_proto protoreflect.FileDescriptor

const file_ai_scenar_scenario_v1_command_proto_rawDesc = "" +
	"\n" +
	"#ai/scenar/scenario/v1/command.proto\x12\x15ai.scenar.scenario.v1\x1a4ai/scenar/commons/resource/rpc_service_options.proto\x1a\x1fai/scenar/scenario/v1/api.proto\x1a\x1eai/scenar/scenario/v1/io.proto2\xda\x02\n" +
	"\x19ScenarioCommandController\x12J\n" +
	"\x06create\x12\x1f.ai.scenar.scenario.v1.Scenario\x1a\x1f.ai.scenar.scenario.v1.Scenario\x12J\n" +
	"\x06update\x12\x1f.ai.scenar.scenario.v1.Scenario\x1a\x1f.ai.scenar.scenario.v1.Scenario\x12L\n" +
	"\x06delete\x12!.ai.scenar.scenario.v1.ScenarioId\x1a\x1f.ai.scenar.scenario.v1.Scenario\x12Q\n" +
	"\x06render\x12\".ai.scenar.scenario.v1.RenderInput\x1a#.ai.scenar.scenario.v1.RenderOutput\x1a\x04\xe0\xbd,\x01B\xec\x01\n" +
	"\x19com.ai.scenar.scenario.v1B\fCommandProtoP\x01ZJgithub.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/scenario/v1;scenariov1\xa2\x02\x03ASS\xaa\x02\x15Ai.Scenar.Scenario.V1\xca\x02\x15Ai\\Scenar\\Scenario\\V1\xe2\x02!Ai\\Scenar\\Scenario\\V1\\GPBMetadata\xea\x02\x18Ai::Scenar::Scenario::V1b\x06proto3"

var file_ai_scenar_scenario_v1_command_proto_goTypes = []any{
	(*Scenario)(nil),     // 0: ai.scenar.scenario.v1.Scenario
	(*ScenarioId)(nil),   // 1: ai.scenar.scenario.v1.ScenarioId
	(*RenderInput)(nil),  // 2: ai.scenar.scenario.v1.RenderInput
	(*RenderOutput)(nil), // 3: ai.scenar.scenario.v1.RenderOutput
}
var file_ai_scenar_scenario_v1_command_proto_depIdxs = []int32{
	0, // 0: ai.scenar.scenario.v1.ScenarioCommandController.create:input_type -> ai.scenar.scenario.v1.Scenario
	0, // 1: ai.scenar.scenario.v1.ScenarioCommandController.update:input_type -> ai.scenar.scenario.v1.Scenario
	1, // 2: ai.scenar.scenario.v1.ScenarioCommandController.delete:input_type -> ai.scenar.scenario.v1.ScenarioId
	2, // 3: ai.scenar.scenario.v1.ScenarioCommandController.render:input_type -> ai.scenar.scenario.v1.RenderInput
	0, // 4: ai.scenar.scenario.v1.ScenarioCommandController.create:output_type -> ai.scenar.scenario.v1.Scenario
	0, // 5: ai.scenar.scenario.v1.ScenarioCommandController.update:output_type -> ai.scenar.scenario.v1.Scenario
	0, // 6: ai.scenar.scenario.v1.ScenarioCommandController.delete:output_type -> ai.scenar.scenario.v1.Scenario
	3, // 7: ai.scenar.scenario.v1.ScenarioCommandController.render:output_type -> ai.scenar.scenario.v1.RenderOutput
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_scenario_v1_command_proto_init() }
func file_ai_scenar_scenario_v1_command_proto_init() {
	if File_ai_scenar_scenario_v1_command_proto != nil {
		return
	}
	file_ai_scenar_scenario_v1_api_proto_init()
	file_ai_scenar_scenario_v1_io_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_command_proto_rawDesc), len(file_ai_scenar_scenario_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_scenar_scenario_v1_command_proto_goTypes,
		DependencyIndexes: file_ai_scenar_scenario_v1_command_proto_depIdxs,
	}.Build()
	File_ai_scenar_scenario_v1_command_proto = out.File
	file_ai_scenar_scenario_v1_command_proto_goTypes = nil
	file_ai_scenar_scenario_v1_command_proto_depIdxs = nil
}
