// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/scenario/v1/enum.proto

package scenariov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionType defines the kinds of timed interactions the Scenar engine
// can perform within a scenario step.
//
// Each action type maps to a distinct cursor/UI behaviour:
//   - Cursor positioning: set_cursor, clear_cursor
//   - UI triggers: click, type, hover, drag
//   - Viewport control: scroll_to, viewport_transition
//
// The engine executes actions at the time specified by StepAction.at_percent,
// applying action-specific configuration from the StepAction.config oneof.
type ActionType int32

const (
	// Default value. Must not be used in scenario definitions.
	ActionType_unspecified ActionType = 0
	// Move the cursor to the target element. The cursor animates smoothly
	// from its current position (or fades in if previously hidden). No
	// click or other interaction is dispatched — this is purely visual
	// positioning to draw the viewer's attention.
	ActionType_set_cursor ActionType = 1
	// Hide the cursor. Use after an interaction sequence completes to
	// return the viewport to a clean state. The target field on StepAction
	// is ignored for this action type.
	ActionType_clear_cursor ActionType = 2
	// Move the cursor to the target element, then dispatch a DOM click
	// event. The click fires after the cursor's arrival animation settles,
	// so the viewer sees the cursor land before the UI reacts.
	//
	// No additional configuration required — the click target is
	// StepAction.target. Use ClickConfig only if future click options
	// are needed.
	ActionType_click ActionType = 3
	// Move the cursor to the target element (an input or textarea), then
	// type text character-by-character. Produces realistic keystroke
	// timing so the viewer can follow along.
	//
	// Requires TypeConfig with the text to type. Optional type_delay_ms
	// overrides the engine's default per-character interval.
	ActionType_type ActionType = 4
	// Move the cursor to the target element and dispatch pointer/mouse
	// enter events. The cursor dwells on the target for a configurable
	// duration (default: engine decides), then dispatches leave events.
	// Useful for revealing tooltips, dropdown previews, or hover states.
	//
	// The cursor does NOT show a click ripple during hover — it simply
	// rests on the target. Optional HoverConfig.hover_duration_ms
	// overrides the default dwell time.
	ActionType_hover ActionType = 5
	// Move the cursor to the source element, press, drag to the
	// destination element, and release. The cursor icon switches to a
	// grab/closed-hand visual during the drag motion.
	//
	// StepAction.target identifies the drag source. DragConfig.drag_target
	// identifies the drag destination. Both use the same targeting
	// mechanism (e.g., data-cursor-target attributes in the DOM).
	ActionType_drag ActionType = 6
	// Scroll the target element into view within its nearest scrollable
	// ancestor. No cursor movement — this is a viewport-level operation
	// that ensures subsequent interactions target visible elements.
	//
	// No additional configuration required — the scroll target is
	// StepAction.target. Use ScrollToConfig only if future scroll
	// options are needed.
	ActionType_scroll_to ActionType = 7
	// Apply a zoom/pan transform to the viewport, centering on the
	// target element at the specified zoom level. Persists across
	// subsequent steps until explicitly reset.
	//
	// ViewportTransitionConfig.viewport_zoom sets the scale factor
	// (> 1 zooms in, < 1 zooms out). Set viewport_reset to true to
	// return to the identity transform (scale 1, no translation).
	ActionType_viewport_transition ActionType = 8
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "unspecified",
		1: "set_cursor",
		2: "clear_cursor",
		3: "click",
		4: "type",
		5: "hover",
		6: "drag",
		7: "scroll_to",
		8: "viewport_transition",
	}
	ActionType_value = map[string]int32{
		"unspecified":         0,
		"set_cursor":          1,
		"clear_cursor":        2,
		"click":               3,
		"type":                4,
		"hover":               5,
		"drag":                6,
		"scroll_to":           7,
		"viewport_transition": 8,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_scenar_scenario_v1_enum_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_ai_scenar_scenario_v1_enum_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_enum_proto_rawDescGZIP(), []int{0}
}

var File_ai_scenar_scenario_v1_enum_proto protoreflect.FileDescriptor

const file_ai_scenar_scenario_v1_enum_proto_rawDesc = "" +
	"\n" +
	" ai/scenar/scenario/v1/enum.proto\x12\x15ai.scenar.scenario.v1*\x91\x01\n" +
	"\n" +
	"ActionType\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\x0e\n" +
	"\n" +
	"set_cursor\x10\x01\x12\x10\n" +
	"\fclear_cursor\x10\x02\x12\t\n" +
	"\x05click\x10\x03\x12\b\n" +
	"\x04type\x10\x04\x12\t\n" +
	"\x05hover\x10\x05\x12\b\n" +
	"\x04drag\x10\x06\x12\r\n" +
	"\tscroll_to\x10\a\x12\x17\n" +
	"\x13viewport_transition\x10\bB\xe9\x01\n" +
	"\x19com.ai.scenar.scenario.v1B\tEnumProtoP\x01ZJgithub.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/scenario/v1;scenariov1\xa2\x02\x03ASS\xaa\x02\x15Ai.Scenar.Scenario.V1\xca\x02\x15Ai\\Scenar\\Scenario\\V1\xe2\x02!Ai\\Scenar\\Scenario\\V1\\GPBMetadata\xea\x02\x18Ai::Scenar::Scenario::V1b\x06proto3"

var (
	file_ai_scenar_scenario_v1_enum_proto_rawDescOnce sync.Once
	file_ai_scenar_scenario_v1_enum_proto_rawDescData []byte
)

func file_ai_scenar_scenario_v1_enum_proto_rawDescGZIP() []byte {
	file_ai_scenar_scenario_v1_enum_proto_rawDescOnce.Do(func() {
		file_ai_scenar_scenario_v1_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_enum_proto_rawDesc), len(file_ai_scenar_scenario_v1_enum_proto_rawDesc)))
	})
	return file_ai_scenar_scenario_v1_enum_proto_rawDescData
}

var file_ai_scenar_scenario_v1_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_scenar_scenario_v1_enum_proto_goTypes = []any{
	(ActionType)(0), // 0: ai.scenar.scenario.v1.ActionType
}
var file_ai_scenar_scenario_v1_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_scenario_v1_enum_proto_init() }
func file_ai_scenar_scenario_v1_enum_proto_init() {
	if File_ai_scenar_scenario_v1_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_enum_proto_rawDesc), len(file_ai_scenar_scenario_v1_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_scenario_v1_enum_proto_goTypes,
		DependencyIndexes: file_ai_scenar_scenario_v1_enum_proto_depIdxs,
		EnumInfos:         file_ai_scenar_scenario_v1_enum_proto_enumTypes,
	}.Build()
	File_ai_scenar_scenario_v1_enum_proto = out.File
	file_ai_scenar_scenario_v1_enum_proto_goTypes = nil
	file_ai_scenar_scenario_v1_enum_proto_depIdxs = nil
}
