// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/scenario/v1/io.proto

package scenariov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	rpc "github.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/commons/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScenarioOutputFormat specifies the output format for scenario rendering.
type ScenarioOutputFormat int32

const (
	// Default value. The service chooses the appropriate format.
	ScenarioOutputFormat_output_format_unspecified ScenarioOutputFormat = 0
	// Interactive web embed — a live React component tree that the viewer
	// can play, pause, and scrub through. This is the primary format for
	// documentation sites and landing pages.
	ScenarioOutputFormat_interactive_embed ScenarioOutputFormat = 1
	// Pixel-perfect MP4 video produced by the Remotion pipeline. Suitable
	// for social media, presentations, and contexts where interactive
	// embeds are not supported.
	ScenarioOutputFormat_mp4_video ScenarioOutputFormat = 2
)

// Enum value maps for ScenarioOutputFormat.
var (
	ScenarioOutputFormat_name = map[int32]string{
		0: "output_format_unspecified",
		1: "interactive_embed",
		2: "mp4_video",
	}
	ScenarioOutputFormat_value = map[string]int32{
		"output_format_unspecified": 0,
		"interactive_embed":         1,
		"mp4_video":                 2,
	}
)

func (x ScenarioOutputFormat) Enum() *ScenarioOutputFormat {
	p := new(ScenarioOutputFormat)
	*p = x
	return p
}

func (x ScenarioOutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScenarioOutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_scenar_scenario_v1_io_proto_enumTypes[0].Descriptor()
}

func (ScenarioOutputFormat) Type() protoreflect.EnumType {
	return &file_ai_scenar_scenario_v1_io_proto_enumTypes[0]
}

func (x ScenarioOutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScenarioOutputFormat.Descriptor instead.
func (ScenarioOutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_io_proto_rawDescGZIP(), []int{0}
}

// ScenarioId identifies a scenario by its unique identifier.
type ScenarioId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the scenario resource.
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioId) Reset() {
	*x = ScenarioId{}
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioId) ProtoMessage() {}

func (x *ScenarioId) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioId.ProtoReflect.Descriptor instead.
func (*ScenarioId) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_io_proto_rawDescGZIP(), []int{0}
}

func (x *ScenarioId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Scenarios contains a list of scenario resources.
type Scenarios struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scenario entries.
	Entries       []*Scenario `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenarios) Reset() {
	*x = Scenarios{}
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenarios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenarios) ProtoMessage() {}

func (x *Scenarios) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenarios.ProtoReflect.Descriptor instead.
func (*Scenarios) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_io_proto_rawDescGZIP(), []int{1}
}

func (x *Scenarios) GetEntries() []*Scenario {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ListScenariosInput specifies filters for listing scenarios.
type ListScenariosInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by tags. When non-empty, only scenarios matching ALL
	// specified tags are returned (AND semantics).
	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// Pagination parameters.
	Page          *rpc.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosInput) Reset() {
	*x = ListScenariosInput{}
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosInput) ProtoMessage() {}

func (x *ListScenariosInput) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosInput.ProtoReflect.Descriptor instead.
func (*ListScenariosInput) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_io_proto_rawDescGZIP(), []int{2}
}

func (x *ListScenariosInput) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListScenariosInput) GetPage() *rpc.PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// RenderInput specifies which scenario to render and in what format.
type RenderInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the scenario to render.
	ScenarioId string `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	// Desired output format.
	Format        ScenarioOutputFormat `protobuf:"varint,2,opt,name=format,proto3,enum=ai.scenar.scenario.v1.ScenarioOutputFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderInput) Reset() {
	*x = RenderInput{}
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderInput) ProtoMessage() {}

func (x *RenderInput) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderInput.ProtoReflect.Descriptor instead.
func (*RenderInput) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_io_proto_rawDescGZIP(), []int{3}
}

func (x *RenderInput) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *RenderInput) GetFormat() ScenarioOutputFormat {
	if x != nil {
		return x.Format
	}
	return ScenarioOutputFormat_output_format_unspecified
}

// RenderOutput contains the result of a render operation.
type RenderOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL of the rendered artifact (e.g., a hosted interactive embed
	// or an MP4 video file).
	ArtifactUrl string `protobuf:"bytes,1,opt,name=artifact_url,json=artifactUrl,proto3" json:"artifact_url,omitempty"`
	// The format of the rendered artifact.
	Format        ScenarioOutputFormat `protobuf:"varint,2,opt,name=format,proto3,enum=ai.scenar.scenario.v1.ScenarioOutputFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderOutput) Reset() {
	*x = RenderOutput{}
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderOutput) ProtoMessage() {}

func (x *RenderOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderOutput.ProtoReflect.Descriptor instead.
func (*RenderOutput) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_io_proto_rawDescGZIP(), []int{4}
}

func (x *RenderOutput) GetArtifactUrl() string {
	if x != nil {
		return x.ArtifactUrl
	}
	return ""
}

func (x *RenderOutput) GetFormat() ScenarioOutputFormat {
	if x != nil {
		return x.Format
	}
	return ScenarioOutputFormat_output_format_unspecified
}

var File_ai_scenar_scenario_v1_io_proto protoreflect.FileDescriptor

const file_ai_scenar_scenario_v1_io_proto_rawDesc = "" +
	"\n" +
	"\x1eai/scenar/scenario/v1/io.proto\x12\x15ai.scenar.scenario.v1\x1a&ai/scenar/commons/rpc/pagination.proto\x1a\x1fai/scenar/scenario/v1/api.proto\x1a\x1bbuf/validate/validate.proto\"+\n" +
	"\n" +
	"ScenarioId\x12\x1d\n" +
	"\x05value\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05value\"F\n" +
	"\tScenarios\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.ai.scenar.scenario.v1.ScenarioR\aentries\"]\n" +
	"\x12ListScenariosInput\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x123\n" +
	"\x04page\x18\x02 \x01(\v2\x1f.ai.scenar.commons.rpc.PageInfoR\x04page\"\x86\x01\n" +
	"\vRenderInput\x12(\n" +
	"\vscenario_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"scenarioId\x12M\n" +
	"\x06format\x18\x02 \x01(\x0e2+.ai.scenar.scenario.v1.ScenarioOutputFormatB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06format\"v\n" +
	"\fRenderOutput\x12!\n" +
	"\fartifact_url\x18\x01 \x01(\tR\vartifactUrl\x12C\n" +
	"\x06format\x18\x02 \x01(\x0e2+.ai.scenar.scenario.v1.ScenarioOutputFormatR\x06format*[\n" +
	"\x14ScenarioOutputFormat\x12\x1d\n" +
	"\x19output_format_unspecified\x10\x00\x12\x15\n" +
	"\x11interactive_embed\x10\x01\x12\r\n" +
	"\tmp4_video\x10\x02B\xe7\x01\n" +
	"\x19com.ai.scenar.scenario.v1B\aIoProtoP\x01ZJgithub.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/scenario/v1;scenariov1\xa2\x02\x03ASS\xaa\x02\x15Ai.Scenar.Scenario.V1\xca\x02\x15Ai\\Scenar\\Scenario\\V1\xe2\x02!Ai\\Scenar\\Scenario\\V1\\GPBMetadata\xea\x02\x18Ai::Scenar::Scenario::V1b\x06proto3"

var (
	file_ai_scenar_scenario_v1_io_proto_rawDescOnce sync.Once
	file_ai_scenar_scenario_v1_io_proto_rawDescData []byte
)

func file_ai_scenar_scenario_v1_io_proto_rawDescGZIP() []byte {
	file_ai_scenar_scenario_v1_io_proto_rawDescOnce.Do(func() {
		file_ai_scenar_scenario_v1_io_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_io_proto_rawDesc), len(file_ai_scenar_scenario_v1_io_proto_rawDesc)))
	})
	return file_ai_scenar_scenario_v1_io_proto_rawDescData
}

var file_ai_scenar_scenario_v1_io_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_scenar_scenario_v1_io_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_scenar_scenario_v1_io_proto_goTypes = []any{
	(ScenarioOutputFormat)(0),  // 0: ai.scenar.scenario.v1.ScenarioOutputFormat
	(*ScenarioId)(nil),         // 1: ai.scenar.scenario.v1.ScenarioId
	(*Scenarios)(nil),          // 2: ai.scenar.scenario.v1.Scenarios
	(*ListScenariosInput)(nil), // 3: ai.scenar.scenario.v1.ListScenariosInput
	(*RenderInput)(nil),        // 4: ai.scenar.scenario.v1.RenderInput
	(*RenderOutput)(nil),       // 5: ai.scenar.scenario.v1.RenderOutput
	(*Scenario)(nil),           // 6: ai.scenar.scenario.v1.Scenario
	(*rpc.PageInfo)(nil),       // 7: ai.scenar.commons.rpc.PageInfo
}
var file_ai_scenar_scenario_v1_io_proto_depIdxs = []int32{
	6, // 0: ai.scenar.scenario.v1.Scenarios.entries:type_name -> ai.scenar.scenario.v1.Scenario
	7, // 1: ai.scenar.scenario.v1.ListScenariosInput.page:type_name -> ai.scenar.commons.rpc.PageInfo
	0, // 2: ai.scenar.scenario.v1.RenderInput.format:type_name -> ai.scenar.scenario.v1.ScenarioOutputFormat
	0, // 3: ai.scenar.scenario.v1.RenderOutput.format:type_name -> ai.scenar.scenario.v1.ScenarioOutputFormat
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_scenar_scenario_v1_io_proto_init() }
func file_ai_scenar_scenario_v1_io_proto_init() {
	if File_ai_scenar_scenario_v1_io_proto != nil {
		return
	}
	file_ai_scenar_scenario_v1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_io_proto_rawDesc), len(file_ai_scenar_scenario_v1_io_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_scenario_v1_io_proto_goTypes,
		DependencyIndexes: file_ai_scenar_scenario_v1_io_proto_depIdxs,
		EnumInfos:         file_ai_scenar_scenario_v1_io_proto_enumTypes,
		MessageInfos:      file_ai_scenar_scenario_v1_io_proto_msgTypes,
	}.Build()
	File_ai_scenar_scenario_v1_io_proto = out.File
	file_ai_scenar_scenario_v1_io_proto_goTypes = nil
	file_ai_scenar_scenario_v1_io_proto_depIdxs = nil
}
