// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/scenario/v1/io.proto

package scenariov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListScenariosRequest is the input for the scenario list query. It scopes the
// listing to a single organization and pages results with an opaque cursor.
//
// Pagination is defined per-resource here (rather than in commons) until the
// platform settles on a shared pagination contract; the field shape
// (page_size / page_token / next_page_token) is the conventional cursor model
// and is intended to migrate to commons unchanged when that contract lands.
type ListScenariosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization whose scenarios to list. Required — listings are always
	// scoped to a single owning org.
	Org string `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	// Maximum number of scenarios to return in one page. When 0 or unset, the
	// server applies its default page size. The server may return fewer items
	// than requested.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor identifying the page to return. Empty fetches the first
	// page. Pass the next_page_token from the previous ScenarioList to continue.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosRequest) Reset() {
	*x = ListScenariosRequest{}
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosRequest) ProtoMessage() {}

func (x *ListScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_io_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListScenariosRequest) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_io_proto_rawDescGZIP(), []int{0}
}

func (x *ListScenariosRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ListScenariosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListScenariosRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

var File_ai_scenar_scenario_v1_io_proto protoreflect.FileDescriptor

const file_ai_scenar_scenario_v1_io_proto_rawDesc = "" +
	"\n" +
	"\x1eai/scenar/scenario/v1/io.proto\x12\x15ai.scenar.scenario.v1\x1a\x1bbuf/validate/validate.proto\"u\n" +
	"\x14ListScenariosRequest\x12\x18\n" +
	"\x03org\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03org\x12$\n" +
	"\tpage_size\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageTokenB\xe5\x01\n" +
	"\x19com.ai.scenar.scenario.v1B\aIoProtoP\x01ZHgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/scenario/v1;scenariov1\xa2\x02\x03ASS\xaa\x02\x15Ai.Scenar.Scenario.V1\xca\x02\x15Ai\\Scenar\\Scenario\\V1\xe2\x02!Ai\\Scenar\\Scenario\\V1\\GPBMetadata\xea\x02\x18Ai::Scenar::Scenario::V1b\x06proto3"

var (
	file_ai_scenar_scenario_v1_io_proto_rawDescOnce sync.Once
	file_ai_scenar_scenario_v1_io_proto_rawDescData []byte
)

func file_ai_scenar_scenario_v1_io_proto_rawDescGZIP() []byte {
	file_ai_scenar_scenario_v1_io_proto_rawDescOnce.Do(func() {
		file_ai_scenar_scenario_v1_io_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_io_proto_rawDesc), len(file_ai_scenar_scenario_v1_io_proto_rawDesc)))
	})
	return file_ai_scenar_scenario_v1_io_proto_rawDescData
}

var file_ai_scenar_scenario_v1_io_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_scenar_scenario_v1_io_proto_goTypes = []any{
	(*ListScenariosRequest)(nil), // 0: ai.scenar.scenario.v1.ListScenariosRequest
}
var file_ai_scenar_scenario_v1_io_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_scenario_v1_io_proto_init() }
func file_ai_scenar_scenario_v1_io_proto_init() {
	if File_ai_scenar_scenario_v1_io_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_io_proto_rawDesc), len(file_ai_scenar_scenario_v1_io_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_scenario_v1_io_proto_goTypes,
		DependencyIndexes: file_ai_scenar_scenario_v1_io_proto_depIdxs,
		MessageInfos:      file_ai_scenar_scenario_v1_io_proto_msgTypes,
	}.Build()
	File_ai_scenar_scenario_v1_io_proto = out.File
	file_ai_scenar_scenario_v1_io_proto_goTypes = nil
	file_ai_scenar_scenario_v1_io_proto_depIdxs = nil
}
