// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ai/scenar/scenario/v1/query.proto

package scenariov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScenarioQueryController_Get_FullMethodName  = "/ai.scenar.scenario.v1.ScenarioQueryController/get"
	ScenarioQueryController_List_FullMethodName = "/ai.scenar.scenario.v1.ScenarioQueryController/list"
)

// ScenarioQueryControllerClient is the client API for ScenarioQueryController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScenarioQueryController provides read operations for scenario resources.
//
// Like ScenarioCommandController, this service is forward-looking for a
// future hosted Scenar platform. In local/build-time usage, scenario
// lookup is handled by the SDK's scenario registry.
type ScenarioQueryControllerClient interface {
	// Get a scenario by its unique identifier.
	Get(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Scenario, error)
	// List scenarios with optional tag filtering and pagination.
	List(ctx context.Context, in *ListScenariosInput, opts ...grpc.CallOption) (*Scenarios, error)
}

type scenarioQueryControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewScenarioQueryControllerClient(cc grpc.ClientConnInterface) ScenarioQueryControllerClient {
	return &scenarioQueryControllerClient{cc}
}

func (c *scenarioQueryControllerClient) Get(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Scenario, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scenario)
	err := c.cc.Invoke(ctx, ScenarioQueryController_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioQueryControllerClient) List(ctx context.Context, in *ListScenariosInput, opts ...grpc.CallOption) (*Scenarios, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scenarios)
	err := c.cc.Invoke(ctx, ScenarioQueryController_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScenarioQueryControllerServer is the server API for ScenarioQueryController service.
// All implementations should embed UnimplementedScenarioQueryControllerServer
// for forward compatibility.
//
// ScenarioQueryController provides read operations for scenario resources.
//
// Like ScenarioCommandController, this service is forward-looking for a
// future hosted Scenar platform. In local/build-time usage, scenario
// lookup is handled by the SDK's scenario registry.
type ScenarioQueryControllerServer interface {
	// Get a scenario by its unique identifier.
	Get(context.Context, *ScenarioId) (*Scenario, error)
	// List scenarios with optional tag filtering and pagination.
	List(context.Context, *ListScenariosInput) (*Scenarios, error)
}

// UnimplementedScenarioQueryControllerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScenarioQueryControllerServer struct{}

func (UnimplementedScenarioQueryControllerServer) Get(context.Context, *ScenarioId) (*Scenario, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedScenarioQueryControllerServer) List(context.Context, *ListScenariosInput) (*Scenarios, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedScenarioQueryControllerServer) testEmbeddedByValue() {}

// UnsafeScenarioQueryControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScenarioQueryControllerServer will
// result in compilation errors.
type UnsafeScenarioQueryControllerServer interface {
	mustEmbedUnimplementedScenarioQueryControllerServer()
}

func RegisterScenarioQueryControllerServer(s grpc.ServiceRegistrar, srv ScenarioQueryControllerServer) {
	// If the following call pancis, it indicates UnimplementedScenarioQueryControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScenarioQueryController_ServiceDesc, srv)
}

func _ScenarioQueryController_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioQueryControllerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioQueryController_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioQueryControllerServer).Get(ctx, req.(*ScenarioId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScenarioQueryController_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioQueryControllerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScenarioQueryController_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioQueryControllerServer).List(ctx, req.(*ListScenariosInput))
	}
	return interceptor(ctx, in, info, handler)
}

// ScenarioQueryController_ServiceDesc is the grpc.ServiceDesc for ScenarioQueryController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScenarioQueryController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.scenar.scenario.v1.ScenarioQueryController",
	HandlerType: (*ScenarioQueryControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _ScenarioQueryController_Get_Handler,
		},
		{
			MethodName: "list",
			Handler:    _ScenarioQueryController_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai/scenar/scenario/v1/query.proto",
}
