// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/scenario/v1/spec.proto

package scenariov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScenarioSpec defines the complete choreography of a scenario — the ordered
// sequence of visual steps, timed cursor interactions within each step, and
// the viewport dimensions for deterministic rendering.
//
// This is the core of Scenar. A ScenarioSpec fully describes what the viewer
// sees: which component renders at each point in time, what the cursor does,
// what text gets typed, and how the viewport transforms. The same spec drives
// both interactive web embeds and pixel-perfect MP4 video exports.
//
// Example YAML:
//
//	viewport:
//	  width: 896
//	  height: 540
//	steps:
//	  - view: new-session
//	    delay_ms: 0
//	    caption: "Start here"
//	    narration_text: "Let's walk through the setup."
//	  - view: settings-api-keys
//	    delay_ms: 1500
//	    caption: "Your API keys"
//	    interactions:
//	      - at_percent: 0.3
//	        type: hover
//	        target: create-api-key
//	  - view: create-form
//	    delay_ms: 2500
//	    caption: "Name your key"
//	    interactions:
//	      - at_percent: 0.15
//	        type: type
//	        target: apikey-name-input
//	        type_config:
//	          text: "quickstart-key"
type ScenarioSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical viewport dimensions for deterministic rendering.
	// When omitted, the engine uses its built-in defaults.
	Viewport *ViewportConfig `protobuf:"bytes,1,opt,name=viewport,proto3" json:"viewport,omitempty"`
	// Ordered sequence of visual steps in the scenario timeline.
	// Step 0 is the initial state. Each subsequent step transitions
	// after its delay_ms elapses (or after the previous step's
	// narration audio completes, whichever is longer).
	Steps         []*Step `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioSpec) Reset() {
	*x = ScenarioSpec{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioSpec) ProtoMessage() {}

func (x *ScenarioSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioSpec.ProtoReflect.Descriptor instead.
func (*ScenarioSpec) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *ScenarioSpec) GetViewport() *ViewportConfig {
	if x != nil {
		return x.Viewport
	}
	return nil
}

func (x *ScenarioSpec) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

// ViewportConfig defines the canonical pixel dimensions at which the scenario
// renders internally. The engine applies CSS zoom to scale this fixed layout
// into the available container width, guaranteeing that cursor positions,
// scroll offsets, and interaction targets resolve against stable coordinates
// regardless of the actual browser viewport.
//
// For video export, these dimensions define the virtual viewport within the
// composition frame.
type ViewportConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical width in pixels. The engine renders all content at this
	// width and applies CSS zoom to fit the container.
	//
	// Typical value: 896 (matches Tailwind max-w-4xl at 16px base).
	Width int32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	// Canonical height in pixels. Controls the shell/container height
	// for content layout.
	//
	// Typical values: 540 for video (16:9 at 960x540), 380 for
	// interactive docs embeds.
	Height        int32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewportConfig) Reset() {
	*x = ViewportConfig{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportConfig) ProtoMessage() {}

func (x *ViewportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportConfig.ProtoReflect.Descriptor instead.
func (*ViewportConfig) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *ViewportConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ViewportConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Step represents a single point in the scenario timeline — a visual state
// (which component renders) plus optional timed interactions (cursor actions,
// typing, hovering, etc.) that occur while this step is active.
//
// Steps are rendered in order. The engine transitions to step N+1 after
// max(step[N+1].delay_ms, narration_duration[N]) milliseconds. The first
// step (index 0) renders immediately.
//
// The view field identifies which React component to render. The mapping
// from view name to component is defined by the scenario author in their
// render function — the engine treats it as an opaque string identifier.
type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component identifier for this step. Maps to a React component via
	// the scenario's render function (e.g., "new-session", "settings-api-keys",
	// "create-form").
	//
	// The engine does not interpret this value — it passes it through to the
	// scenario's render function, which switches on it to render the
	// appropriate UI.
	View string `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	// Milliseconds to wait before transitioning to this step from the
	// previous one. Step 0 should use delay_ms: 0 (renders immediately).
	//
	// When narration is enabled, the actual transition time is
	// max(delay_ms, previous_step_narration_duration) — narration always
	// plays to completion before the next step begins.
	DelayMs int32 `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	// Short label displayed below the demo content describing the current
	// action (e.g., "Click your profile", "Copy your API key"). Shown in
	// both interactive embeds and video exports.
	Caption string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	// Narration script for text-to-speech generation. Consumed by the
	// build script to produce audio files — not rendered at runtime.
	//
	// When narration audio exists for this step, the engine uses the
	// audio clip duration (instead of the next step's delay_ms) for
	// step timing, ensuring the narration plays to completion.
	NarrationText string `protobuf:"bytes,4,opt,name=narration_text,json=narrationText,proto3" json:"narration_text,omitempty"`
	// Opaque component-specific properties passed to the render function.
	// The engine does not inspect this value — it is forwarded as-is to
	// the React component identified by the view field.
	//
	// Use this for step-specific data that the component needs beyond
	// the view identifier (e.g., fixture data variations, UI state flags).
	// Most steps only need the view field and leave props empty.
	Props *structpb.Struct `protobuf:"bytes,5,opt,name=props,proto3" json:"props,omitempty"`
	// Timed interactions to execute while this step is active. Each
	// interaction fires at a specific point during the step's duration
	// (controlled by StepAction.at_percent).
	//
	// Interactions are executed in order. When multiple interactions
	// share the same at_percent, they fire in array order.
	//
	// To position the cursor when a step starts, add a set_cursor
	// interaction at at_percent: 0.0 — this keeps all cursor choreography
	// declarative and in one place.
	Interactions  []*StepAction `protobuf:"bytes,6,rep,name=interactions,proto3" json:"interactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *Step) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *Step) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *Step) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Step) GetNarrationText() string {
	if x != nil {
		return x.NarrationText
	}
	return ""
}

func (x *Step) GetProps() *structpb.Struct {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Step) GetInteractions() []*StepAction {
	if x != nil {
		return x.Interactions
	}
	return nil
}

// StepAction defines a single timed interaction within a step — what the
// cursor does, when it does it, and any action-specific configuration.
//
// The at_percent field controls timing: 0.0 fires at step start, 1.0 at
// step end, 0.5 at the midpoint. The actual millisecond time is computed
// from the step's duration (narration clip length or next step's delay_ms).
//
// The target field identifies the DOM element for cursor-based actions.
// The engine resolves targets via data attributes (e.g., data-cursor-target
// for cursor actions, data-scroll-target for scroll actions). The target
// string is the attribute value, not a CSS selector.
//
// Example — hover at 30% of step duration:
//
//	at_percent: 0.3
//	type: hover
//	target: "create-api-key"
//	hover_config:
//	  hover_duration_ms: 1500
type StepAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When to fire this action, as a fraction of the step's duration.
	//
	// 0.0 = step start, 1.0 = step end. The engine computes the real
	// millisecond time from the step's narration duration (if available)
	// or the next step's delay_ms (as fallback).
	//
	// Actions within a step are processed in order. When multiple actions
	// share the same at_percent, they fire sequentially in array order.
	AtPercent float32 `protobuf:"fixed32,1,opt,name=at_percent,json=atPercent,proto3" json:"at_percent,omitempty"`
	// The type of interaction to perform.
	Type ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=ai.scenar.scenario.v1.ActionType" json:"type,omitempty"`
	// Target element identifier for cursor-based actions. The engine
	// resolves this to a DOM element via data attributes.
	//
	// Required for: set_cursor, click, type, hover, drag (source),
	// scroll_to, viewport_transition.
	// Ignored for: clear_cursor.
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// Action-specific configuration. Only action types that require
	// additional parameters use the config oneof — simple actions
	// (set_cursor, clear_cursor, click, scroll_to) leave it unset.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*StepAction_ClickConfig
	//	*StepAction_TypeConfig
	//	*StepAction_HoverConfig
	//	*StepAction_DragConfig
	//	*StepAction_ScrollToConfig
	//	*StepAction_ViewportTransitionConfig
	Config        isStepAction_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepAction) Reset() {
	*x = StepAction{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepAction) ProtoMessage() {}

func (x *StepAction) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepAction.ProtoReflect.Descriptor instead.
func (*StepAction) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *StepAction) GetAtPercent() float32 {
	if x != nil {
		return x.AtPercent
	}
	return 0
}

func (x *StepAction) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_unspecified
}

func (x *StepAction) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StepAction) GetConfig() isStepAction_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StepAction) GetClickConfig() *ClickConfig {
	if x != nil {
		if x, ok := x.Config.(*StepAction_ClickConfig); ok {
			return x.ClickConfig
		}
	}
	return nil
}

func (x *StepAction) GetTypeConfig() *TypeConfig {
	if x != nil {
		if x, ok := x.Config.(*StepAction_TypeConfig); ok {
			return x.TypeConfig
		}
	}
	return nil
}

func (x *StepAction) GetHoverConfig() *HoverConfig {
	if x != nil {
		if x, ok := x.Config.(*StepAction_HoverConfig); ok {
			return x.HoverConfig
		}
	}
	return nil
}

func (x *StepAction) GetDragConfig() *DragConfig {
	if x != nil {
		if x, ok := x.Config.(*StepAction_DragConfig); ok {
			return x.DragConfig
		}
	}
	return nil
}

func (x *StepAction) GetScrollToConfig() *ScrollToConfig {
	if x != nil {
		if x, ok := x.Config.(*StepAction_ScrollToConfig); ok {
			return x.ScrollToConfig
		}
	}
	return nil
}

func (x *StepAction) GetViewportTransitionConfig() *ViewportTransitionConfig {
	if x != nil {
		if x, ok := x.Config.(*StepAction_ViewportTransitionConfig); ok {
			return x.ViewportTransitionConfig
		}
	}
	return nil
}

type isStepAction_Config interface {
	isStepAction_Config()
}

type StepAction_ClickConfig struct {
	// Configuration for click actions. Currently empty — the click
	// target is StepAction.target. Reserved for future click options
	// (e.g., double-click, right-click).
	ClickConfig *ClickConfig `protobuf:"bytes,10,opt,name=click_config,json=clickConfig,proto3,oneof"`
}

type StepAction_TypeConfig struct {
	// Configuration for type actions.
	TypeConfig *TypeConfig `protobuf:"bytes,11,opt,name=type_config,json=typeConfig,proto3,oneof"`
}

type StepAction_HoverConfig struct {
	// Configuration for hover actions.
	HoverConfig *HoverConfig `protobuf:"bytes,12,opt,name=hover_config,json=hoverConfig,proto3,oneof"`
}

type StepAction_DragConfig struct {
	// Configuration for drag actions.
	DragConfig *DragConfig `protobuf:"bytes,13,opt,name=drag_config,json=dragConfig,proto3,oneof"`
}

type StepAction_ScrollToConfig struct {
	// Configuration for scroll_to actions. Currently empty — the
	// scroll target is StepAction.target. Reserved for future scroll
	// options (e.g., scroll direction, offset).
	ScrollToConfig *ScrollToConfig `protobuf:"bytes,14,opt,name=scroll_to_config,json=scrollToConfig,proto3,oneof"`
}

type StepAction_ViewportTransitionConfig struct {
	// Configuration for viewport_transition actions.
	ViewportTransitionConfig *ViewportTransitionConfig `protobuf:"bytes,15,opt,name=viewport_transition_config,json=viewportTransitionConfig,proto3,oneof"`
}

func (*StepAction_ClickConfig) isStepAction_Config() {}

func (*StepAction_TypeConfig) isStepAction_Config() {}

func (*StepAction_HoverConfig) isStepAction_Config() {}

func (*StepAction_DragConfig) isStepAction_Config() {}

func (*StepAction_ScrollToConfig) isStepAction_Config() {}

func (*StepAction_ViewportTransitionConfig) isStepAction_Config() {}

// ClickConfig holds configuration for click actions.
//
// Currently empty — the click target is specified by StepAction.target.
// This message exists as an extension point for future click variants
// (e.g., double-click, right-click, long-press).
type ClickConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickConfig) Reset() {
	*x = ClickConfig{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickConfig) ProtoMessage() {}

func (x *ClickConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickConfig.ProtoReflect.Descriptor instead.
func (*ClickConfig) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{4}
}

// TypeConfig holds configuration for type (text input) actions.
//
// The engine moves the cursor to StepAction.target, focuses the input
// element, and types the text character-by-character with realistic
// keystroke timing.
type TypeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text to type character-by-character into the target input element.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Milliseconds between each character. When 0 or unset, the engine
	// uses its built-in default (typically 50ms — fast enough to feel
	// like confident typing, slow enough for each character to be
	// readable in both browser playback and video export).
	TypeDelayMs   int32 `protobuf:"varint,2,opt,name=type_delay_ms,json=typeDelayMs,proto3" json:"type_delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeConfig) Reset() {
	*x = TypeConfig{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeConfig) ProtoMessage() {}

func (x *TypeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeConfig.ProtoReflect.Descriptor instead.
func (*TypeConfig) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{5}
}

func (x *TypeConfig) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TypeConfig) GetTypeDelayMs() int32 {
	if x != nil {
		return x.TypeDelayMs
	}
	return 0
}

// HoverConfig holds configuration for hover (tooltip/state reveal) actions.
//
// The engine moves the cursor to StepAction.target, dispatches pointer/mouse
// enter events, holds for the configured duration, then dispatches leave
// events. The cursor does not show a click ripple during hover.
type HoverConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Milliseconds to hold the cursor over the target between enter and
	// leave events. When 0 or unset, the engine uses its built-in
	// default (typically 1500ms — enough time for viewers to notice a
	// tooltip or hover-state change).
	HoverDurationMs int32 `protobuf:"varint,1,opt,name=hover_duration_ms,json=hoverDurationMs,proto3" json:"hover_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HoverConfig) Reset() {
	*x = HoverConfig{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoverConfig) ProtoMessage() {}

func (x *HoverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoverConfig.ProtoReflect.Descriptor instead.
func (*HoverConfig) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{6}
}

func (x *HoverConfig) GetHoverDurationMs() int32 {
	if x != nil {
		return x.HoverDurationMs
	}
	return 0
}

// DragConfig holds configuration for drag (drag-and-drop) actions.
//
// StepAction.target identifies the drag source element. This config
// specifies the drag destination. The engine moves the cursor to the
// source, presses, animates to the destination, and releases.
type DragConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target element identifier for the drag destination. Uses the same
	// targeting mechanism as StepAction.target (e.g., data-cursor-target
	// attribute value).
	DragTarget    string `protobuf:"bytes,1,opt,name=drag_target,json=dragTarget,proto3" json:"drag_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DragConfig) Reset() {
	*x = DragConfig{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DragConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragConfig) ProtoMessage() {}

func (x *DragConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragConfig.ProtoReflect.Descriptor instead.
func (*DragConfig) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{7}
}

func (x *DragConfig) GetDragTarget() string {
	if x != nil {
		return x.DragTarget
	}
	return ""
}

// ScrollToConfig holds configuration for scroll_to actions.
//
// Currently empty — the scroll target is specified by StepAction.target,
// and the engine scrolls it into view within its nearest scrollable
// ancestor. This message exists as an extension point for future scroll
// options (e.g., scroll alignment, smooth vs instant).
type ScrollToConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollToConfig) Reset() {
	*x = ScrollToConfig{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollToConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollToConfig) ProtoMessage() {}

func (x *ScrollToConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollToConfig.ProtoReflect.Descriptor instead.
func (*ScrollToConfig) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{8}
}

// ViewportTransitionConfig holds configuration for viewport zoom/pan
// transitions.
//
// The engine computes a CSS transform (scale + translate) that centers
// the target element in the viewport at the specified zoom level. The
// transform persists across subsequent steps until explicitly reset.
type ViewportTransitionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zoom scale factor. Values > 1 zoom in (e.g., 2.0 = 200% magnification),
	// values < 1 zoom out. Ignored when viewport_reset is true.
	//
	// When 0 or unset, defaults to 1.5 (a moderate zoom that provides
	// detail without losing spatial context).
	ViewportZoom float32 `protobuf:"fixed32,1,opt,name=viewport_zoom,json=viewportZoom,proto3" json:"viewport_zoom,omitempty"`
	// When true, resets the viewport to the identity transform (scale 1,
	// no translation). The target and viewport_zoom fields are ignored.
	// Use this to return to the full view after a zoom sequence.
	ViewportReset bool `protobuf:"varint,2,opt,name=viewport_reset,json=viewportReset,proto3" json:"viewport_reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewportTransitionConfig) Reset() {
	*x = ViewportTransitionConfig{}
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportTransitionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportTransitionConfig) ProtoMessage() {}

func (x *ViewportTransitionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_scenario_v1_spec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportTransitionConfig.ProtoReflect.Descriptor instead.
func (*ViewportTransitionConfig) Descriptor() ([]byte, []int) {
	return file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP(), []int{9}
}

func (x *ViewportTransitionConfig) GetViewportZoom() float32 {
	if x != nil {
		return x.ViewportZoom
	}
	return 0
}

func (x *ViewportTransitionConfig) GetViewportReset() bool {
	if x != nil {
		return x.ViewportReset
	}
	return false
}

var File_ai_scenar_scenario_v1_spec_proto protoreflect.FileDescriptor

const file_ai_scenar_scenario_v1_spec_proto_rawDesc = "" +
	"\n" +
	" ai/scenar/scenario/v1/spec.proto\x12\x15ai.scenar.scenario.v1\x1a ai/scenar/scenario/v1/enum.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x01\n" +
	"\fScenarioSpec\x12A\n" +
	"\bviewport\x18\x01 \x01(\v2%.ai.scenar.scenario.v1.ViewportConfigR\bviewport\x12;\n" +
	"\x05steps\x18\x02 \x03(\v2\x1b.ai.scenar.scenario.v1.StepB\b\xbaH\x05\x92\x01\x02\b\x01R\x05steps\"P\n" +
	"\x0eViewportConfig\x12\x1d\n" +
	"\x05width\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05width\x12\x1f\n" +
	"\x06height\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06height\"\xfe\x01\n" +
	"\x04Step\x12\x1b\n" +
	"\x04view\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04view\x12\"\n" +
	"\bdelay_ms\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\adelayMs\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12%\n" +
	"\x0enarration_text\x18\x04 \x01(\tR\rnarrationText\x12-\n" +
	"\x05props\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05props\x12E\n" +
	"\finteractions\x18\x06 \x03(\v2!.ai.scenar.scenario.v1.StepActionR\finteractions\"\x81\x05\n" +
	"\n" +
	"StepAction\x12.\n" +
	"\n" +
	"at_percent\x18\x01 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\tatPercent\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2!.ai.scenar.scenario.v1.ActionTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04type\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12G\n" +
	"\fclick_config\x18\n" +
	" \x01(\v2\".ai.scenar.scenario.v1.ClickConfigH\x00R\vclickConfig\x12D\n" +
	"\vtype_config\x18\v \x01(\v2!.ai.scenar.scenario.v1.TypeConfigH\x00R\n" +
	"typeConfig\x12G\n" +
	"\fhover_config\x18\f \x01(\v2\".ai.scenar.scenario.v1.HoverConfigH\x00R\vhoverConfig\x12D\n" +
	"\vdrag_config\x18\r \x01(\v2!.ai.scenar.scenario.v1.DragConfigH\x00R\n" +
	"dragConfig\x12Q\n" +
	"\x10scroll_to_config\x18\x0e \x01(\v2%.ai.scenar.scenario.v1.ScrollToConfigH\x00R\x0escrollToConfig\x12o\n" +
	"\x1aviewport_transition_config\x18\x0f \x01(\v2/.ai.scenar.scenario.v1.ViewportTransitionConfigH\x00R\x18viewportTransitionConfigB\b\n" +
	"\x06config\"\r\n" +
	"\vClickConfig\"V\n" +
	"\n" +
	"TypeConfig\x12\x1b\n" +
	"\x04text\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04text\x12+\n" +
	"\rtype_delay_ms\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\vtypeDelayMs\"B\n" +
	"\vHoverConfig\x123\n" +
	"\x11hover_duration_ms\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x0fhoverDurationMs\"6\n" +
	"\n" +
	"DragConfig\x12(\n" +
	"\vdrag_target\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"dragTarget\"\x10\n" +
	"\x0eScrollToConfig\"f\n" +
	"\x18ViewportTransitionConfig\x12#\n" +
	"\rviewport_zoom\x18\x01 \x01(\x02R\fviewportZoom\x12%\n" +
	"\x0eviewport_reset\x18\x02 \x01(\bR\rviewportResetB\xe9\x01\n" +
	"\x19com.ai.scenar.scenario.v1B\tSpecProtoP\x01ZJgithub.com/scenar-ai/scenar/apis/stubs/go/ai/scenar/scenario/v1;scenariov1\xa2\x02\x03ASS\xaa\x02\x15Ai.Scenar.Scenario.V1\xca\x02\x15Ai\\Scenar\\Scenario\\V1\xe2\x02!Ai\\Scenar\\Scenario\\V1\\GPBMetadata\xea\x02\x18Ai::Scenar::Scenario::V1b\x06proto3"

var (
	file_ai_scenar_scenario_v1_spec_proto_rawDescOnce sync.Once
	file_ai_scenar_scenario_v1_spec_proto_rawDescData []byte
)

func file_ai_scenar_scenario_v1_spec_proto_rawDescGZIP() []byte {
	file_ai_scenar_scenario_v1_spec_proto_rawDescOnce.Do(func() {
		file_ai_scenar_scenario_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_spec_proto_rawDesc), len(file_ai_scenar_scenario_v1_spec_proto_rawDesc)))
	})
	return file_ai_scenar_scenario_v1_spec_proto_rawDescData
}

var file_ai_scenar_scenario_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ai_scenar_scenario_v1_spec_proto_goTypes = []any{
	(*ScenarioSpec)(nil),             // 0: ai.scenar.scenario.v1.ScenarioSpec
	(*ViewportConfig)(nil),           // 1: ai.scenar.scenario.v1.ViewportConfig
	(*Step)(nil),                     // 2: ai.scenar.scenario.v1.Step
	(*StepAction)(nil),               // 3: ai.scenar.scenario.v1.StepAction
	(*ClickConfig)(nil),              // 4: ai.scenar.scenario.v1.ClickConfig
	(*TypeConfig)(nil),               // 5: ai.scenar.scenario.v1.TypeConfig
	(*HoverConfig)(nil),              // 6: ai.scenar.scenario.v1.HoverConfig
	(*DragConfig)(nil),               // 7: ai.scenar.scenario.v1.DragConfig
	(*ScrollToConfig)(nil),           // 8: ai.scenar.scenario.v1.ScrollToConfig
	(*ViewportTransitionConfig)(nil), // 9: ai.scenar.scenario.v1.ViewportTransitionConfig
	(*structpb.Struct)(nil),          // 10: google.protobuf.Struct
	(ActionType)(0),                  // 11: ai.scenar.scenario.v1.ActionType
}
var file_ai_scenar_scenario_v1_spec_proto_depIdxs = []int32{
	1,  // 0: ai.scenar.scenario.v1.ScenarioSpec.viewport:type_name -> ai.scenar.scenario.v1.ViewportConfig
	2,  // 1: ai.scenar.scenario.v1.ScenarioSpec.steps:type_name -> ai.scenar.scenario.v1.Step
	10, // 2: ai.scenar.scenario.v1.Step.props:type_name -> google.protobuf.Struct
	3,  // 3: ai.scenar.scenario.v1.Step.interactions:type_name -> ai.scenar.scenario.v1.StepAction
	11, // 4: ai.scenar.scenario.v1.StepAction.type:type_name -> ai.scenar.scenario.v1.ActionType
	4,  // 5: ai.scenar.scenario.v1.StepAction.click_config:type_name -> ai.scenar.scenario.v1.ClickConfig
	5,  // 6: ai.scenar.scenario.v1.StepAction.type_config:type_name -> ai.scenar.scenario.v1.TypeConfig
	6,  // 7: ai.scenar.scenario.v1.StepAction.hover_config:type_name -> ai.scenar.scenario.v1.HoverConfig
	7,  // 8: ai.scenar.scenario.v1.StepAction.drag_config:type_name -> ai.scenar.scenario.v1.DragConfig
	8,  // 9: ai.scenar.scenario.v1.StepAction.scroll_to_config:type_name -> ai.scenar.scenario.v1.ScrollToConfig
	9,  // 10: ai.scenar.scenario.v1.StepAction.viewport_transition_config:type_name -> ai.scenar.scenario.v1.ViewportTransitionConfig
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ai_scenar_scenario_v1_spec_proto_init() }
func file_ai_scenar_scenario_v1_spec_proto_init() {
	if File_ai_scenar_scenario_v1_spec_proto != nil {
		return
	}
	file_ai_scenar_scenario_v1_enum_proto_init()
	file_ai_scenar_scenario_v1_spec_proto_msgTypes[3].OneofWrappers = []any{
		(*StepAction_ClickConfig)(nil),
		(*StepAction_TypeConfig)(nil),
		(*StepAction_HoverConfig)(nil),
		(*StepAction_DragConfig)(nil),
		(*StepAction_ScrollToConfig)(nil),
		(*StepAction_ViewportTransitionConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_scenario_v1_spec_proto_rawDesc), len(file_ai_scenar_scenario_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_scenario_v1_spec_proto_goTypes,
		DependencyIndexes: file_ai_scenar_scenario_v1_spec_proto_depIdxs,
		MessageInfos:      file_ai_scenar_scenario_v1_spec_proto_msgTypes,
	}.Build()
	File_ai_scenar_scenario_v1_spec_proto = out.File
	file_ai_scenar_scenario_v1_spec_proto_goTypes = nil
	file_ai_scenar_scenario_v1_spec_proto_depIdxs = nil
}
