# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/tenancy/organization/v1/command.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/tenancy/organization/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import io_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_io__pb2
from ai.scenar.commons.apiresource import rpc_service_options_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from ai.scenar.tenancy.organization.v1 import api_pb2 as ai_dot_scenar_dot_tenancy_dot_organization_dot_v1_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ai/scenar/tenancy/organization/v1/command.proto\x12!ai.scenar.tenancy.organization.v1\x1a&ai/scenar/commons/apiresource/io.proto\x1a\x37\x61i/scenar/commons/apiresource/rpc_service_options.proto\x1a+ai/scenar/tenancy/organization/v1/api.proto2\xda\x03\n\x1dOrganizationCommandController\x12i\n\x05\x61pply\x12/.ai.scenar.tenancy.organization.v1.Organization\x1a/.ai.scenar.tenancy.organization.v1.Organization\x12j\n\x06\x63reate\x12/.ai.scenar.tenancy.organization.v1.Organization\x1a/.ai.scenar.tenancy.organization.v1.Organization\x12j\n\x06update\x12/.ai.scenar.tenancy.organization.v1.Organization\x1a/.ai.scenar.tenancy.organization.v1.Organization\x12p\n\x06\x64\x65lete\x12\x35.ai.scenar.commons.apiresource.ApiResourceDeleteInput\x1a/.ai.scenar.tenancy.organization.v1.Organization\x1a\x04\xa0\xff+\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.tenancy.organization.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORGANIZATIONCOMMANDCONTROLLER']._loaded_options = None
  _globals['_ORGANIZATIONCOMMANDCONTROLLER']._serialized_options = b'\240\377+\002'
  _globals['_ORGANIZATIONCOMMANDCONTROLLER']._serialized_start=229
  _globals['_ORGANIZATIONCOMMANDCONTROLLER']._serialized_end=703
# @@protoc_insertion_point(module_scope)
