# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/tenancy/organization/v1/query.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/tenancy/organization/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import io_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_io__pb2
from ai.scenar.commons.apiresource import rpc_service_options_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from ai.scenar.tenancy.organization.v1 import api_pb2 as ai_dot_scenar_dot_tenancy_dot_organization_dot_v1_dot_api__pb2
from ai.scenar.tenancy.organization.v1 import io_pb2 as ai_dot_scenar_dot_tenancy_dot_organization_dot_v1_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-ai/scenar/tenancy/organization/v1/query.proto\x12!ai.scenar.tenancy.organization.v1\x1a&ai/scenar/commons/apiresource/io.proto\x1a\x37\x61i/scenar/commons/apiresource/rpc_service_options.proto\x1a+ai/scenar/tenancy/organization/v1/api.proto\x1a*ai/scenar/tenancy/organization/v1/io.proto2\x83\x02\n\x1bOrganizationQueryController\x12\x64\n\x03get\x12,.ai.scenar.commons.apiresource.ApiResourceId\x1a/.ai.scenar.tenancy.organization.v1.Organization\x12x\n\x04list\x12;.ai.scenar.tenancy.organization.v1.ListOrganizationsRequest\x1a\x33.ai.scenar.tenancy.organization.v1.OrganizationList\x1a\x04\xa0\xff+\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.tenancy.organization.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORGANIZATIONQUERYCONTROLLER']._loaded_options = None
  _globals['_ORGANIZATIONQUERYCONTROLLER']._serialized_options = b'\240\377+\002'
  _globals['_ORGANIZATIONQUERYCONTROLLER']._serialized_start=271
  _globals['_ORGANIZATIONQUERYCONTROLLER']._serialized_end=530
# @@protoc_insertion_point(module_scope)
