# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/tenancy/organization/v1/status.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/tenancy/organization/v1/status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import field_options_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_field__options__pb2
from ai.scenar.commons.apiresource import status_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ai/scenar/tenancy/organization/v1/status.proto\x12!ai.scenar.tenancy.organization.v1\x1a\x31\x61i/scenar/commons/apiresource/field_options.proto\x1a*ai/scenar/commons/apiresource/status.proto\"\x84\x01\n\x12OrganizationStatus\x12\'\n\x0cmember_count\x18\x01 \x01(\x05\x42\x04\xc8\x85,\x01R\x0bmemberCount\x12\x45\n\x05\x61udit\x18\x63 \x01(\x0b\x32/.ai.scenar.commons.apiresource.ApiResourceAuditR\x05\x61uditb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.tenancy.organization.v1.status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORGANIZATIONSTATUS'].fields_by_name['member_count']._loaded_options = None
  _globals['_ORGANIZATIONSTATUS'].fields_by_name['member_count']._serialized_options = b'\310\205,\001'
  _globals['_ORGANIZATIONSTATUS']._serialized_start=181
  _globals['_ORGANIZATIONSTATUS']._serialized_end=313
# @@protoc_insertion_point(module_scope)
