// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/deploy/v1/command.proto

package deployv1

import (
	_ "github.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ai_scenar_deploy_v1_command_proto protoreflect.FileDescriptor

const file_ai_scenar_deploy_v1_command_proto_rawDesc = "" +
	"\n" +
	"!ai/scenar/deploy/v1/command.proto\x12\x13ai.scenar.deploy.v1\x1a7ai/scenar/commons/apiresource/rpc_service_options.proto\x1a\x1dai/scenar/deploy/v1/api.proto\x1a\x1cai/scenar/deploy/v1/io.proto2\xa1\x02\n" +
	"\x17DeployCommandController\x12\x8a\x01\n" +
	"\x19createDeployUploadSession\x125.ai.scenar.deploy.v1.CreateDeployUploadSessionRequest\x1a6.ai.scenar.deploy.v1.CreateDeployUploadSessionResponse\x12s\n" +
	"\x1bcompleteDeployUploadSession\x127.ai.scenar.deploy.v1.CompleteDeployUploadSessionRequest\x1a\x1b.ai.scenar.deploy.v1.Deploy\x1a\x04\xa0\xff+\x05B\xdc\x01\n" +
	"\x17com.ai.scenar.deploy.v1B\fCommandProtoP\x01ZDgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/deploy/v1;deployv1\xa2\x02\x03ASD\xaa\x02\x13Ai.Scenar.Deploy.V1\xca\x02\x13Ai\\Scenar\\Deploy\\V1\xe2\x02\x1fAi\\Scenar\\Deploy\\V1\\GPBMetadata\xea\x02\x16Ai::Scenar::Deploy::V1b\x06proto3"

var file_ai_scenar_deploy_v1_command_proto_goTypes = []any{
	(*CreateDeployUploadSessionRequest)(nil),   // 0: ai.scenar.deploy.v1.CreateDeployUploadSessionRequest
	(*CompleteDeployUploadSessionRequest)(nil), // 1: ai.scenar.deploy.v1.CompleteDeployUploadSessionRequest
	(*CreateDeployUploadSessionResponse)(nil),  // 2: ai.scenar.deploy.v1.CreateDeployUploadSessionResponse
	(*Deploy)(nil), // 3: ai.scenar.deploy.v1.Deploy
}
var file_ai_scenar_deploy_v1_command_proto_depIdxs = []int32{
	0, // 0: ai.scenar.deploy.v1.DeployCommandController.createDeployUploadSession:input_type -> ai.scenar.deploy.v1.CreateDeployUploadSessionRequest
	1, // 1: ai.scenar.deploy.v1.DeployCommandController.completeDeployUploadSession:input_type -> ai.scenar.deploy.v1.CompleteDeployUploadSessionRequest
	2, // 2: ai.scenar.deploy.v1.DeployCommandController.createDeployUploadSession:output_type -> ai.scenar.deploy.v1.CreateDeployUploadSessionResponse
	3, // 3: ai.scenar.deploy.v1.DeployCommandController.completeDeployUploadSession:output_type -> ai.scenar.deploy.v1.Deploy
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_deploy_v1_command_proto_init() }
func file_ai_scenar_deploy_v1_command_proto_init() {
	if File_ai_scenar_deploy_v1_command_proto != nil {
		return
	}
	file_ai_scenar_deploy_v1_api_proto_init()
	file_ai_scenar_deploy_v1_io_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_deploy_v1_command_proto_rawDesc), len(file_ai_scenar_deploy_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_scenar_deploy_v1_command_proto_goTypes,
		DependencyIndexes: file_ai_scenar_deploy_v1_command_proto_depIdxs,
	}.Build()
	File_ai_scenar_deploy_v1_command_proto = out.File
	file_ai_scenar_deploy_v1_command_proto_goTypes = nil
	file_ai_scenar_deploy_v1_command_proto_depIdxs = nil
}
