// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/deploy/v1/io.proto

package deployv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListDeploysRequest is the input for the deploy list query. It scopes the
// listing to a single parent scenario and pages results with an opaque cursor.
//
// Listing is parent-scoped rather than org-scoped because deploys are children
// of a scenario: the caller is authorized by `can_view` on the parent scenario,
// and every returned deploy belongs to it. Pagination uses the conventional
// cursor model (page_size / page_token / next_page_token), matching
// ListScenariosRequest, and is intended to migrate to a shared commons
// contract unchanged when that lands.
type ListDeploysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent scenario whose deploys to list. Required — deploy listings are
	// always scoped to a single scenario, which is also the authorization parent.
	ScenarioId string `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	// Maximum number of deploys to return in one page. When 0 or unset, the
	// server applies its default page size. The server may return fewer items
	// than requested.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor identifying the page to return. Empty fetches the first page.
	// Pass the next_page_token from the previous DeployList to continue.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploysRequest) Reset() {
	*x = ListDeploysRequest{}
	mi := &file_ai_scenar_deploy_v1_io_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploysRequest) ProtoMessage() {}

func (x *ListDeploysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_deploy_v1_io_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploysRequest.ProtoReflect.Descriptor instead.
func (*ListDeploysRequest) Descriptor() ([]byte, []int) {
	return file_ai_scenar_deploy_v1_io_proto_rawDescGZIP(), []int{0}
}

func (x *ListDeploysRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ListDeploysRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDeploysRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

var File_ai_scenar_deploy_v1_io_proto protoreflect.FileDescriptor

const file_ai_scenar_deploy_v1_io_proto_rawDesc = "" +
	"\n" +
	"\x1cai/scenar/deploy/v1/io.proto\x12\x13ai.scenar.deploy.v1\x1a\x1bbuf/validate/validate.proto\"\x86\x01\n" +
	"\x12ListDeploysRequest\x12+\n" +
	"\vscenario_id\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\n" +
	"scenarioId\x12$\n" +
	"\tpage_size\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageTokenB\xd7\x01\n" +
	"\x17com.ai.scenar.deploy.v1B\aIoProtoP\x01ZDgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/deploy/v1;deployv1\xa2\x02\x03ASD\xaa\x02\x13Ai.Scenar.Deploy.V1\xca\x02\x13Ai\\Scenar\\Deploy\\V1\xe2\x02\x1fAi\\Scenar\\Deploy\\V1\\GPBMetadata\xea\x02\x16Ai::Scenar::Deploy::V1b\x06proto3"

var (
	file_ai_scenar_deploy_v1_io_proto_rawDescOnce sync.Once
	file_ai_scenar_deploy_v1_io_proto_rawDescData []byte
)

func file_ai_scenar_deploy_v1_io_proto_rawDescGZIP() []byte {
	file_ai_scenar_deploy_v1_io_proto_rawDescOnce.Do(func() {
		file_ai_scenar_deploy_v1_io_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_deploy_v1_io_proto_rawDesc), len(file_ai_scenar_deploy_v1_io_proto_rawDesc)))
	})
	return file_ai_scenar_deploy_v1_io_proto_rawDescData
}

var file_ai_scenar_deploy_v1_io_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_scenar_deploy_v1_io_proto_goTypes = []any{
	(*ListDeploysRequest)(nil), // 0: ai.scenar.deploy.v1.ListDeploysRequest
}
var file_ai_scenar_deploy_v1_io_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_deploy_v1_io_proto_init() }
func file_ai_scenar_deploy_v1_io_proto_init() {
	if File_ai_scenar_deploy_v1_io_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_deploy_v1_io_proto_rawDesc), len(file_ai_scenar_deploy_v1_io_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_deploy_v1_io_proto_goTypes,
		DependencyIndexes: file_ai_scenar_deploy_v1_io_proto_depIdxs,
		MessageInfos:      file_ai_scenar_deploy_v1_io_proto_msgTypes,
	}.Build()
	File_ai_scenar_deploy_v1_io_proto = out.File
	file_ai_scenar_deploy_v1_io_proto_goTypes = nil
	file_ai_scenar_deploy_v1_io_proto_depIdxs = nil
}
