// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/deploy/v1/query.proto

package deployv1

import (
	apiresource "github.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ai_scenar_deploy_v1_query_proto protoreflect.FileDescriptor

const file_ai_scenar_deploy_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1fai/scenar/deploy/v1/query.proto\x12\x13ai.scenar.deploy.v1\x1a&ai/scenar/commons/apiresource/io.proto\x1a7ai/scenar/commons/apiresource/rpc_service_options.proto\x1a\x1dai/scenar/deploy/v1/api.proto\x1a\x1cai/scenar/deploy/v1/io.proto2\xc1\x01\n" +
	"\x15DeployQueryController\x12P\n" +
	"\x03get\x12,.ai.scenar.commons.apiresource.ApiResourceId\x1a\x1b.ai.scenar.deploy.v1.Deploy\x12P\n" +
	"\x04list\x12'.ai.scenar.deploy.v1.ListDeploysRequest\x1a\x1f.ai.scenar.deploy.v1.DeployList\x1a\x04\xa0\xff+\x05B\xda\x01\n" +
	"\x17com.ai.scenar.deploy.v1B\n" +
	"QueryProtoP\x01ZDgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/deploy/v1;deployv1\xa2\x02\x03ASD\xaa\x02\x13Ai.Scenar.Deploy.V1\xca\x02\x13Ai\\Scenar\\Deploy\\V1\xe2\x02\x1fAi\\Scenar\\Deploy\\V1\\GPBMetadata\xea\x02\x16Ai::Scenar::Deploy::V1b\x06proto3"

var file_ai_scenar_deploy_v1_query_proto_goTypes = []any{
	(*apiresource.ApiResourceId)(nil), // 0: ai.scenar.commons.apiresource.ApiResourceId
	(*ListDeploysRequest)(nil),        // 1: ai.scenar.deploy.v1.ListDeploysRequest
	(*Deploy)(nil),                    // 2: ai.scenar.deploy.v1.Deploy
	(*DeployList)(nil),                // 3: ai.scenar.deploy.v1.DeployList
}
var file_ai_scenar_deploy_v1_query_proto_depIdxs = []int32{
	0, // 0: ai.scenar.deploy.v1.DeployQueryController.get:input_type -> ai.scenar.commons.apiresource.ApiResourceId
	1, // 1: ai.scenar.deploy.v1.DeployQueryController.list:input_type -> ai.scenar.deploy.v1.ListDeploysRequest
	2, // 2: ai.scenar.deploy.v1.DeployQueryController.get:output_type -> ai.scenar.deploy.v1.Deploy
	3, // 3: ai.scenar.deploy.v1.DeployQueryController.list:output_type -> ai.scenar.deploy.v1.DeployList
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_deploy_v1_query_proto_init() }
func file_ai_scenar_deploy_v1_query_proto_init() {
	if File_ai_scenar_deploy_v1_query_proto != nil {
		return
	}
	file_ai_scenar_deploy_v1_api_proto_init()
	file_ai_scenar_deploy_v1_io_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_deploy_v1_query_proto_rawDesc), len(file_ai_scenar_deploy_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_scenar_deploy_v1_query_proto_goTypes,
		DependencyIndexes: file_ai_scenar_deploy_v1_query_proto_depIdxs,
	}.Build()
	File_ai_scenar_deploy_v1_query_proto = out.File
	file_ai_scenar_deploy_v1_query_proto_goTypes = nil
	file_ai_scenar_deploy_v1_query_proto_depIdxs = nil
}
