// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/deploy/v1/status.proto

package deployv1

import (
	apiresource "github.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeployStatus is the observed state of a Deploy resource — the `status` block
// of the envelope (see api.proto). Every field is computed and managed by the
// system; clients never set status. The backend derives these values as it
// creates, verifies, publishes, and serves a deploy.
type DeployStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current lifecycle phase. The serving edge only returns content while this
	// is `active`; the backend's DeployStateMachine governs how it advances.
	State DeployState `protobuf:"varint,1,opt,name=state,proto3,enum=ai.scenar.deploy.v1.DeployState" json:"state,omitempty"`
	// Per-deploy public URL at which this immutable snapshot is served (the
	// d-<deployId> content-domain origin). Computed when the deploy goes
	// `active`. Empty until then.
	EmbedUrl string `protobuf:"bytes,2,opt,name=embed_url,json=embedUrl,proto3" json:"embed_url,omitempty"`
	// Immutable object-store key prefix that holds this deploy's bundle
	// (tenants/<org>/scenarios/<scenario>/deploys/<deploy>/). Computed at
	// creation; a deploy's objects are never written outside this prefix.
	ObjectKeyPrefix string `protobuf:"bytes,3,opt,name=object_key_prefix,json=objectKeyPrefix,proto3" json:"object_key_prefix,omitempty"`
	// Human-readable reason the deploy is not servable when state is a failure or
	// takedown phase (e.g. a failed scan or an abuse takedown note). Empty on the
	// happy path.
	ErrorReason string `protobuf:"bytes,4,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	// Standard creation/modification audit information. The high field number
	// keeps audit at a stable, conventional location and leaves room below for
	// future deploy-specific status fields (e.g. per-transition timestamps added
	// with the publication command surface).
	//
	// Typed as ApiResourceAudit directly (not the ApiResourceAuditStatus
	// wrapper): the platform's audit reflection adapter locates this block by the
	// field name `audit` on the status message and requires its type to be
	// ApiResourceAudit.
	Audit         *apiresource.ApiResourceAudit `protobuf:"bytes,99,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployStatus) Reset() {
	*x = DeployStatus{}
	mi := &file_ai_scenar_deploy_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStatus) ProtoMessage() {}

func (x *DeployStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_deploy_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStatus.ProtoReflect.Descriptor instead.
func (*DeployStatus) Descriptor() ([]byte, []int) {
	return file_ai_scenar_deploy_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *DeployStatus) GetState() DeployState {
	if x != nil {
		return x.State
	}
	return DeployState_deploy_state_unspecified
}

func (x *DeployStatus) GetEmbedUrl() string {
	if x != nil {
		return x.EmbedUrl
	}
	return ""
}

func (x *DeployStatus) GetObjectKeyPrefix() string {
	if x != nil {
		return x.ObjectKeyPrefix
	}
	return ""
}

func (x *DeployStatus) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *DeployStatus) GetAudit() *apiresource.ApiResourceAudit {
	if x != nil {
		return x.Audit
	}
	return nil
}

var File_ai_scenar_deploy_v1_status_proto protoreflect.FileDescriptor

const file_ai_scenar_deploy_v1_status_proto_rawDesc = "" +
	"\n" +
	" ai/scenar/deploy/v1/status.proto\x12\x13ai.scenar.deploy.v1\x1a1ai/scenar/commons/apiresource/field_options.proto\x1a*ai/scenar/commons/apiresource/status.proto\x1a\x1eai/scenar/deploy/v1/enum.proto\"\x91\x02\n" +
	"\fDeployStatus\x12<\n" +
	"\x05state\x18\x01 \x01(\x0e2 .ai.scenar.deploy.v1.DeployStateB\x04ȅ,\x01R\x05state\x12!\n" +
	"\tembed_url\x18\x02 \x01(\tB\x04ȅ,\x01R\bembedUrl\x120\n" +
	"\x11object_key_prefix\x18\x03 \x01(\tB\x04ȅ,\x01R\x0fobjectKeyPrefix\x12'\n" +
	"\ferror_reason\x18\x04 \x01(\tB\x04ȅ,\x01R\verrorReason\x12E\n" +
	"\x05audit\x18c \x01(\v2/.ai.scenar.commons.apiresource.ApiResourceAuditR\x05auditB\xdb\x01\n" +
	"\x17com.ai.scenar.deploy.v1B\vStatusProtoP\x01ZDgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/deploy/v1;deployv1\xa2\x02\x03ASD\xaa\x02\x13Ai.Scenar.Deploy.V1\xca\x02\x13Ai\\Scenar\\Deploy\\V1\xe2\x02\x1fAi\\Scenar\\Deploy\\V1\\GPBMetadata\xea\x02\x16Ai::Scenar::Deploy::V1b\x06proto3"

var (
	file_ai_scenar_deploy_v1_status_proto_rawDescOnce sync.Once
	file_ai_scenar_deploy_v1_status_proto_rawDescData []byte
)

func file_ai_scenar_deploy_v1_status_proto_rawDescGZIP() []byte {
	file_ai_scenar_deploy_v1_status_proto_rawDescOnce.Do(func() {
		file_ai_scenar_deploy_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_deploy_v1_status_proto_rawDesc), len(file_ai_scenar_deploy_v1_status_proto_rawDesc)))
	})
	return file_ai_scenar_deploy_v1_status_proto_rawDescData
}

var file_ai_scenar_deploy_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_scenar_deploy_v1_status_proto_goTypes = []any{
	(*DeployStatus)(nil),                 // 0: ai.scenar.deploy.v1.DeployStatus
	(DeployState)(0),                     // 1: ai.scenar.deploy.v1.DeployState
	(*apiresource.ApiResourceAudit)(nil), // 2: ai.scenar.commons.apiresource.ApiResourceAudit
}
var file_ai_scenar_deploy_v1_status_proto_depIdxs = []int32{
	1, // 0: ai.scenar.deploy.v1.DeployStatus.state:type_name -> ai.scenar.deploy.v1.DeployState
	2, // 1: ai.scenar.deploy.v1.DeployStatus.audit:type_name -> ai.scenar.commons.apiresource.ApiResourceAudit
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_scenar_deploy_v1_status_proto_init() }
func file_ai_scenar_deploy_v1_status_proto_init() {
	if File_ai_scenar_deploy_v1_status_proto != nil {
		return
	}
	file_ai_scenar_deploy_v1_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_deploy_v1_status_proto_rawDesc), len(file_ai_scenar_deploy_v1_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_deploy_v1_status_proto_goTypes,
		DependencyIndexes: file_ai_scenar_deploy_v1_status_proto_depIdxs,
		MessageInfos:      file_ai_scenar_deploy_v1_status_proto_msgTypes,
	}.Build()
	File_ai_scenar_deploy_v1_status_proto = out.File
	file_ai_scenar_deploy_v1_status_proto_goTypes = nil
	file_ai_scenar_deploy_v1_status_proto_depIdxs = nil
}
