import { resolve, join } from "node:path";
import { stat, mkdir, access, writeFile, rm } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { loadBundle, type CliBundle } from "../util/load-bundle.js";
import { resolveSfxAssetPaths } from "../util/soundtrack-assets.js";
import { generateRemotionEntry } from "./generate-entry.js";
import { resolveProvidersPath } from "./resolve-providers.js";
import { detectRenderExport } from "./detect-render-export.js";
import { stageRenderAssets } from "./stage-assets.js";

/** Options for {@link runRender}. Paths may be relative; resolved here. */
export interface RunRenderOptions {
  readonly scenarioDir: string;
  readonly out?: string;
  readonly fps?: number;
  readonly width?: number;
  readonly height?: number;
  readonly compositionId?: string;
  readonly entry?: string;
  readonly webpackOverride?: string;
  /**
   * Burn step captions into the video (each step's `narration` text as a
   * subtitle overlay). Only applies to the auto-generated entry; a custom
   * `--entry` owns its own `<ScenarioComposition>` props.
   */
  readonly captions?: boolean;
  readonly onLog?: (message: string) => void;
}

/** The outcome of a successful render. */
export interface RenderResult {
  readonly scenarioId: string;
  readonly outputPath: string;
  readonly steps: number;
  readonly hasNarration: boolean;
  readonly entryAutoGenerated: boolean;
  readonly fps: number;
  readonly width: number;
  readonly height: number;
}

/**
 * Render a scenario directory to an MP4 via Remotion — the pure orchestration
 * behind `scenar render`, with no process/exit coupling. Throws on any failure
 * (missing directory, missing Remotion peer deps, render error). The caller
 * formats the result/error.
 */
export async function runRender(options: RunRenderOptions): Promise<RenderResult> {
  const onLog = options.onLog ?? (() => {});
  const scenarioDir = resolve(options.scenarioDir);

  const info = await stat(scenarioDir).catch(() => null);
  if (!info) {
    throw new Error(`${options.scenarioDir} does not exist.`);
  }
  if (!info.isDirectory()) {
    throw new Error(
      `${options.scenarioDir} is not a directory. ` +
        "The render command requires a scenario directory (with steps.ts).",
    );
  }

  const fps = options.fps ?? 30;
  const width = options.width ?? 1920;
  const height = options.height ?? 1080;
  const captions = options.captions ?? false;

  // A custom entry owns its own <ScenarioComposition> props, so --captions
  // cannot reach it. Say so instead of silently ignoring the flag.
  if (captions && options.entry) {
    onLog(
      "Warning: --captions has no effect with --entry. " +
        'Pass captions to <ScenarioComposition> in your entry file instead.',
    );
  }

  let tempDir: string | undefined;
  try {
    const bundle = await loadBundle(scenarioDir);
    const scenarioId = bundle.id;
    const compositionId = options.compositionId ?? scenarioId;
    const outputPath = resolveOutputPath(options.out, scenarioId);

    const { entryPoint, generated } = await resolveEntryPoint({
      entryOption: options.entry,
      scenarioDir,
      scenarioId,
      compositionId,
      hasNarration: !!bundle.narrationManifest,
      fps,
      width,
      height,
      captions,
    });
    tempDir = generated?.tempDir;

    const webpackOverride = options.webpackOverride
      ? await loadWebpackOverride(options.webpackOverride)
      : undefined;

    onLog(`Scenario: ${scenarioId}`);
    onLog(`Steps:    ${bundle.steps.length}`);
    onLog(`Audio:    ${bundle.narrationManifest ? "yes (manifest found)" : "none"}`);
    if (bundle.soundtrack) {
      const parts = [
        bundle.soundtrack.musicSrc ? `music (${bundle.soundtrack.musicSrc})` : null,
        bundle.soundtrack.sfx ? "sfx" : null,
      ].filter(Boolean);
      onLog(`Soundtrack: ${parts.length > 0 ? parts.join(" + ") : "configured (silent)"}`);
    }
    if (bundle.titleCards?.intro || bundle.titleCards?.outro) {
      const parts = [
        bundle.titleCards.intro ? "intro" : null,
        bundle.titleCards.outro ? "outro" : null,
      ].filter(Boolean);
      onLog(`Cards:    ${parts.join(" + ")}`);
    }
    if (captions) {
      onLog(`Captions: burned in (from step narration text)`);
    }

    // Stage every local asset into a Remotion public dir so staticFile()
    // resolution finds real bytes — narration clips, the music asset, the
    // built-in SFX set, and title-card logos. Only for the auto-generated
    // entry: a custom --entry project owns its own public dir convention.
    let publicDir: string | undefined;
    if (generated) {
      const candidatePublicDir = join(generated.tempDir, "public");
      const sfxPaths = bundle.soundtrack?.sfx
        ? resolveSfxAssetPaths(scenarioDir)
        : undefined;
      const stagedCount = await stageRenderAssets({
        scenarioDir,
        publicDir: candidatePublicDir,
        hasNarration: !!bundle.narrationManifest,
        soundtrack: bundle.soundtrack,
        sfxPaths,
        titleCards: bundle.titleCards,
      });
      if (stagedCount > 0) {
        publicDir = candidatePublicDir;
        onLog(`Staged:   ${stagedCount} asset file(s) for the render`);
      }
    }
    onLog(`Entry:    ${generated ? "(auto-generated)" : entryPoint}`);
    if (generated?.providersPath) {
      onLog(`Providers: ${generated.providersPath}`);
    }
    if (webpackOverride) {
      onLog("Webpack:  custom override loaded");
    }
    onLog(`Output:   ${outputPath}`);
    onLog(`Config:   ${width}x${height} @ ${fps}fps`);

    await renderScenario({
      bundle,
      entryPoint,
      compositionId,
      outputPath,
      fps,
      width,
      height,
      webpackOverride,
      publicDir,
      onLog,
    });

    return {
      scenarioId,
      outputPath,
      steps: bundle.steps.length,
      hasNarration: !!bundle.narrationManifest,
      entryAutoGenerated: !!generated,
      fps,
      width,
      height,
    };
  } finally {
    if (tempDir) {
      await rm(tempDir, { recursive: true, force: true }).catch(() => {});
    }
  }
}

function resolveOutputPath(outOption: string | undefined, scenarioId: string): string {
  if (!outOption) {
    return resolve(`./${scenarioId}.mp4`);
  }
  if (outOption.endsWith(".mp4")) {
    return resolve(outOption);
  }
  return resolve(join(outOption, `${scenarioId}.mp4`));
}

interface EntryResolutionInput {
  entryOption: string | undefined;
  scenarioDir: string;
  scenarioId: string;
  compositionId: string;
  hasNarration: boolean;
  fps: number;
  width: number;
  height: number;
  captions: boolean;
}

interface EntryResolutionResult {
  entryPoint: string;
  generated?: {
    tempDir: string;
    providersPath: string | null;
  };
}

async function resolveEntryPoint(input: EntryResolutionInput): Promise<EntryResolutionResult> {
  // Explicit --entry: use as-is, no generation.
  if (input.entryOption) {
    const resolved = resolve(input.entryOption);
    try {
      await access(resolved);
    } catch {
      throw new Error(`Remotion entry point not found: ${input.entryOption}`);
    }
    return { entryPoint: resolved };
  }

  // Auto-generate: detect renderStep export, find providers, write temp entry.
  const renderFilePath = await detectRenderExport(input.scenarioDir);
  const providersPath = await resolveProvidersPath(input.scenarioDir);

  const entrySource = generateRemotionEntry({
    scenarioDir: input.scenarioDir,
    renderFilePath,
    scenarioId: input.scenarioId,
    hasNarration: input.hasNarration,
    providersPath,
    fps: input.fps,
    width: input.width,
    height: input.height,
    compositionId: input.compositionId,
    captions: input.captions,
  });

  // Write the entry inside the scenario directory so webpack's standard
  // node_modules resolution walks up from here into the consumer project.
  // A /tmp/ location would fail because no node_modules exist there.
  const tempDir = join(input.scenarioDir, ".scenar-render");
  await mkdir(tempDir, { recursive: true });

  const entryPath = join(tempDir, "index.tsx");
  await writeFile(entryPath, entrySource, "utf-8");

  return { entryPoint: entryPath, generated: { tempDir, providersPath } };
}

async function loadWebpackOverride(overridePath: string): Promise<(config: unknown) => unknown> {
  const resolved = resolve(overridePath);
  try {
    await access(resolved);
  } catch {
    throw new Error(`Webpack override file not found: ${overridePath}`);
  }

  let mod: Record<string, unknown>;
  try {
    mod = (await import(pathToFileURL(resolved).href)) as Record<string, unknown>;
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to import webpack override from ${overridePath}:\n${detail}`);
  }

  const override = (mod.default ?? mod.webpackOverride) as unknown;
  if (typeof override !== "function") {
    throw new Error(
      `${overridePath} does not export a webpack override function.\n\n` +
        "Expected a default export or named 'webpackOverride' export:\n\n" +
        '  import type { WebpackOverrideFn } from "@remotion/bundler";\n\n' +
        "  const webpackOverride: WebpackOverrideFn = (config) => ({\n" +
        "    ...config,\n" +
        "    // your overrides\n" +
        "  });\n\n" +
        "  export default webpackOverride;\n",
    );
  }

  return override as (config: unknown) => unknown;
}

interface RenderConfig {
  bundle: CliBundle;
  entryPoint: string;
  compositionId: string;
  outputPath: string;
  fps: number;
  width: number;
  height: number;
  webpackOverride?: (config: unknown) => unknown;
  /** Staged audio dir for Remotion's staticFile() resolution, if any. */
  publicDir?: string;
  onLog: (message: string) => void;
}

async function renderScenario(config: RenderConfig): Promise<void> {
  const bundler = await import("@remotion/bundler").catch(() => {
    throw new Error(
      "Could not load @remotion/bundler.\nInstall it: pnpm add @remotion/bundler@4.0.448",
    );
  });

  const renderer = await import("@remotion/renderer").catch(() => {
    throw new Error(
      "Could not load @remotion/renderer.\nInstall it: pnpm add @remotion/renderer@4.0.448",
    );
  });

  config.onLog("Bundling Remotion project...");

  const bundleOptions: Record<string, unknown> = { entryPoint: config.entryPoint };
  if (config.webpackOverride) {
    bundleOptions.webpackOverride = config.webpackOverride;
  }
  if (config.publicDir) {
    bundleOptions.publicDir = config.publicDir;
  }
  const serveUrl = await (bundler.bundle as (opts: Record<string, unknown>) => Promise<string>)(
    bundleOptions,
  );

  config.onLog(`Selecting composition: ${config.compositionId}`);
  const composition = await renderer.selectComposition({
    serveUrl,
    id: config.compositionId,
  });

  config.onLog(
    `Composition: ${composition.width}x${composition.height} @ ${composition.fps}fps, ` +
      `${composition.durationInFrames} frames ` +
      `(${(composition.durationInFrames / composition.fps).toFixed(1)}s)`,
  );

  const outDir = resolve(config.outputPath, "..");
  await mkdir(outDir, { recursive: true });

  config.onLog("Rendering...");
  await renderer.renderMedia({
    composition,
    serveUrl,
    codec: "h264" as const,
    outputLocation: config.outputPath,
    onProgress: ({ progress }: { progress: number }) => {
      const pct = Math.round(progress * 100);
      config.onLog(`  Progress: ${pct}%`);
    },
  });
}
