// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/iam/apikey/v1/api.proto

package apikeyv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	apiresource "github.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiKey is a credential for programmatic access to the Scenar Cloud API — for
// example, a CLI authenticating a deploy. It follows the Kubernetes-style
// envelope shared by every Scenar resource — api_version / kind / metadata /
// spec / status — so the Scenar Cloud backend can manage keys through the
// platform's generic resource machinery.
//
// Each key is owned by exactly one organization (metadata.org) and authenticates
// as that organization. The raw key value is generated server-side and returned
// only once, in the create response, via status.plaintext_key; only its hash and
// fingerprint are persisted (see ApiKeySpec).
type ApiKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version of this resource, in `<group-domain>/<version>` form. Pinned to
	// the iam group's domain so the value is self-describing and routable by the
	// platform's resource registry.
	//
	// Must be exactly "iam.scenar.ai/v1".
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Resource kind discriminator. Pairs with api_version to uniquely identify
	// the resource type within a multi-kind document stream.
	//
	// Must be exactly "ApiKey".
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Standard resource metadata: name, slug, owning org, visibility, labels,
	// annotations, and tags. Required — every key must carry identity and name
	// the organization that owns it. See
	// ai.scenar.commons.apiresource.ApiResourceMetadata.
	Metadata *apiresource.ApiResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state: the key's expiration policy. Authored by users on create.
	// The key_hash and fingerprint within are server-computed. See ApiKeySpec.
	Spec *ApiKeySpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// Observed state: system-computed fields such as last-used time and audit,
	// plus the one-time plaintext key on the create response. Populated by the
	// backend; ignored on write. See ApiKeyStatus.
	Status        *ApiKeyStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_ai_scenar_iam_apikey_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_iam_apikey_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_ai_scenar_iam_apikey_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKey) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ApiKey) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApiKey) GetMetadata() *apiresource.ApiResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ApiKey) GetSpec() *ApiKeySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ApiKey) GetStatus() *ApiKeyStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ApiKeyList is the paginated result of a list query over API keys. It mirrors
// the resource envelope (api_version / kind) at the collection level so list
// responses are self-describing.
type ApiKeyList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version of the list envelope. Echoes the resource's api_version.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Kind discriminator for the list envelope (e.g. "ApiKeyList").
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// The page of API keys in this response, in server-defined order. Each entry
	// carries the hash and fingerprint but never the plaintext key.
	Items []*ApiKey `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	// Opaque cursor for fetching the next page. Empty when this is the last page.
	// Pass back as ListApiKeysRequest.page_token to continue iterating.
	NextPageToken string `protobuf:"bytes,4,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyList) Reset() {
	*x = ApiKeyList{}
	mi := &file_ai_scenar_iam_apikey_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyList) ProtoMessage() {}

func (x *ApiKeyList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_iam_apikey_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyList.ProtoReflect.Descriptor instead.
func (*ApiKeyList) Descriptor() ([]byte, []int) {
	return file_ai_scenar_iam_apikey_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ApiKeyList) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ApiKeyList) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApiKeyList) GetItems() []*ApiKey {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ApiKeyList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_ai_scenar_iam_apikey_v1_api_proto protoreflect.FileDescriptor

const file_ai_scenar_iam_apikey_v1_api_proto_rawDesc = "" +
	"\n" +
	"!ai/scenar/iam/apikey/v1/api.proto\x12\x17ai.scenar.iam.apikey.v1\x1a,ai/scenar/commons/apiresource/metadata.proto\x1a\"ai/scenar/iam/apikey/v1/spec.proto\x1a$ai/scenar/iam/apikey/v1/status.proto\x1a\x1bbuf/validate/validate.proto\"\xb5\x02\n" +
	"\x06ApiKey\x128\n" +
	"\vapi_version\x18\x01 \x01(\tB\x17\xbaH\x14r\x12\n" +
	"\x10iam.scenar.ai/v1R\n" +
	"apiVersion\x12!\n" +
	"\x04kind\x18\x02 \x01(\tB\r\xbaH\n" +
	"r\b\n" +
	"\x06ApiKeyR\x04kind\x12V\n" +
	"\bmetadata\x18\x03 \x01(\v22.ai.scenar.commons.apiresource.ApiResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x127\n" +
	"\x04spec\x18\x04 \x01(\v2#.ai.scenar.iam.apikey.v1.ApiKeySpecR\x04spec\x12=\n" +
	"\x06status\x18\x05 \x01(\v2%.ai.scenar.iam.apikey.v1.ApiKeyStatusR\x06status\"\xa0\x01\n" +
	"\n" +
	"ApiKeyList\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x125\n" +
	"\x05items\x18\x03 \x03(\v2\x1f.ai.scenar.iam.apikey.v1.ApiKeyR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x04 \x01(\tR\rnextPageTokenB\xf2\x01\n" +
	"\x1bcom.ai.scenar.iam.apikey.v1B\bApiProtoP\x01ZHgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/iam/apikey/v1;apikeyv1\xa2\x02\x04ASIA\xaa\x02\x17Ai.Scenar.Iam.Apikey.V1\xca\x02\x17Ai\\Scenar\\Iam\\Apikey\\V1\xe2\x02#Ai\\Scenar\\Iam\\Apikey\\V1\\GPBMetadata\xea\x02\x1bAi::Scenar::Iam::Apikey::V1b\x06proto3"

var (
	file_ai_scenar_iam_apikey_v1_api_proto_rawDescOnce sync.Once
	file_ai_scenar_iam_apikey_v1_api_proto_rawDescData []byte
)

func file_ai_scenar_iam_apikey_v1_api_proto_rawDescGZIP() []byte {
	file_ai_scenar_iam_apikey_v1_api_proto_rawDescOnce.Do(func() {
		file_ai_scenar_iam_apikey_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_iam_apikey_v1_api_proto_rawDesc), len(file_ai_scenar_iam_apikey_v1_api_proto_rawDesc)))
	})
	return file_ai_scenar_iam_apikey_v1_api_proto_rawDescData
}

var file_ai_scenar_iam_apikey_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_scenar_iam_apikey_v1_api_proto_goTypes = []any{
	(*ApiKey)(nil),                          // 0: ai.scenar.iam.apikey.v1.ApiKey
	(*ApiKeyList)(nil),                      // 1: ai.scenar.iam.apikey.v1.ApiKeyList
	(*apiresource.ApiResourceMetadata)(nil), // 2: ai.scenar.commons.apiresource.ApiResourceMetadata
	(*ApiKeySpec)(nil),                      // 3: ai.scenar.iam.apikey.v1.ApiKeySpec
	(*ApiKeyStatus)(nil),                    // 4: ai.scenar.iam.apikey.v1.ApiKeyStatus
}
var file_ai_scenar_iam_apikey_v1_api_proto_depIdxs = []int32{
	2, // 0: ai.scenar.iam.apikey.v1.ApiKey.metadata:type_name -> ai.scenar.commons.apiresource.ApiResourceMetadata
	3, // 1: ai.scenar.iam.apikey.v1.ApiKey.spec:type_name -> ai.scenar.iam.apikey.v1.ApiKeySpec
	4, // 2: ai.scenar.iam.apikey.v1.ApiKey.status:type_name -> ai.scenar.iam.apikey.v1.ApiKeyStatus
	0, // 3: ai.scenar.iam.apikey.v1.ApiKeyList.items:type_name -> ai.scenar.iam.apikey.v1.ApiKey
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_scenar_iam_apikey_v1_api_proto_init() }
func file_ai_scenar_iam_apikey_v1_api_proto_init() {
	if File_ai_scenar_iam_apikey_v1_api_proto != nil {
		return
	}
	file_ai_scenar_iam_apikey_v1_spec_proto_init()
	file_ai_scenar_iam_apikey_v1_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_iam_apikey_v1_api_proto_rawDesc), len(file_ai_scenar_iam_apikey_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_iam_apikey_v1_api_proto_goTypes,
		DependencyIndexes: file_ai_scenar_iam_apikey_v1_api_proto_depIdxs,
		MessageInfos:      file_ai_scenar_iam_apikey_v1_api_proto_msgTypes,
	}.Build()
	File_ai_scenar_iam_apikey_v1_api_proto = out.File
	file_ai_scenar_iam_apikey_v1_api_proto_goTypes = nil
	file_ai_scenar_iam_apikey_v1_api_proto_depIdxs = nil
}
