// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/iam/apikey/v1/status.proto

package apikeyv1

import (
	apiresource "github.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiKeyStatus is the observed state of an ApiKey resource — the `status` block
// of the envelope (see api.proto). Every field here is computed and managed by
// the system; clients never set status on create or update.
type ApiKeyStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the most recent successful authentication made with this key.
	// Computed by the backend; unset until the key has been used at least once.
	LastUsedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	// The raw, plaintext key. This is the ONLY moment the secret is ever
	// visible: it is populated solely in the response to
	// ApiKeyCommandController.create and is never persisted, cached, logged, or
	// returned by any other RPC (get, getByKeyHash, list). The backend MUST clear
	// this field before storing the resource's status. Callers must capture it
	// from the create response immediately — it cannot be retrieved again.
	PlaintextKey string `protobuf:"bytes,2,opt,name=plaintext_key,json=plaintextKey,proto3" json:"plaintext_key,omitempty"`
	// Standard creation/modification audit information. The high field number
	// keeps audit at a stable, conventional location and leaves room below for
	// future API-key-specific status fields.
	//
	// Typed as ApiResourceAudit directly (not the ApiResourceAuditStatus
	// wrapper): the platform's audit reflection adapter locates this block by the
	// field name `audit` on the status message and requires its type to be
	// ApiResourceAudit. The wrapper is only used when a resource's entire status
	// field is the audit block.
	Audit         *apiresource.ApiResourceAudit `protobuf:"bytes,99,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyStatus) Reset() {
	*x = ApiKeyStatus{}
	mi := &file_ai_scenar_iam_apikey_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyStatus) ProtoMessage() {}

func (x *ApiKeyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_iam_apikey_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyStatus.ProtoReflect.Descriptor instead.
func (*ApiKeyStatus) Descriptor() ([]byte, []int) {
	return file_ai_scenar_iam_apikey_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKeyStatus) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *ApiKeyStatus) GetPlaintextKey() string {
	if x != nil {
		return x.PlaintextKey
	}
	return ""
}

func (x *ApiKeyStatus) GetAudit() *apiresource.ApiResourceAudit {
	if x != nil {
		return x.Audit
	}
	return nil
}

var File_ai_scenar_iam_apikey_v1_status_proto protoreflect.FileDescriptor

const file_ai_scenar_iam_apikey_v1_status_proto_rawDesc = "" +
	"\n" +
	"$ai/scenar/iam/apikey/v1/status.proto\x12\x17ai.scenar.iam.apikey.v1\x1a1ai/scenar/commons/apiresource/field_options.proto\x1a*ai/scenar/commons/apiresource/status.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x01\n" +
	"\fApiKeyStatus\x12B\n" +
	"\flast_used_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x04ȅ,\x01R\n" +
	"lastUsedAt\x12)\n" +
	"\rplaintext_key\x18\x02 \x01(\tB\x04ȅ,\x01R\fplaintextKey\x12E\n" +
	"\x05audit\x18c \x01(\v2/.ai.scenar.commons.apiresource.ApiResourceAuditR\x05auditB\xf5\x01\n" +
	"\x1bcom.ai.scenar.iam.apikey.v1B\vStatusProtoP\x01ZHgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/iam/apikey/v1;apikeyv1\xa2\x02\x04ASIA\xaa\x02\x17Ai.Scenar.Iam.Apikey.V1\xca\x02\x17Ai\\Scenar\\Iam\\Apikey\\V1\xe2\x02#Ai\\Scenar\\Iam\\Apikey\\V1\\GPBMetadata\xea\x02\x1bAi::Scenar::Iam::Apikey::V1b\x06proto3"

var (
	file_ai_scenar_iam_apikey_v1_status_proto_rawDescOnce sync.Once
	file_ai_scenar_iam_apikey_v1_status_proto_rawDescData []byte
)

func file_ai_scenar_iam_apikey_v1_status_proto_rawDescGZIP() []byte {
	file_ai_scenar_iam_apikey_v1_status_proto_rawDescOnce.Do(func() {
		file_ai_scenar_iam_apikey_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_iam_apikey_v1_status_proto_rawDesc), len(file_ai_scenar_iam_apikey_v1_status_proto_rawDesc)))
	})
	return file_ai_scenar_iam_apikey_v1_status_proto_rawDescData
}

var file_ai_scenar_iam_apikey_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_scenar_iam_apikey_v1_status_proto_goTypes = []any{
	(*ApiKeyStatus)(nil),                 // 0: ai.scenar.iam.apikey.v1.ApiKeyStatus
	(*timestamppb.Timestamp)(nil),        // 1: google.protobuf.Timestamp
	(*apiresource.ApiResourceAudit)(nil), // 2: ai.scenar.commons.apiresource.ApiResourceAudit
}
var file_ai_scenar_iam_apikey_v1_status_proto_depIdxs = []int32{
	1, // 0: ai.scenar.iam.apikey.v1.ApiKeyStatus.last_used_at:type_name -> google.protobuf.Timestamp
	2, // 1: ai.scenar.iam.apikey.v1.ApiKeyStatus.audit:type_name -> ai.scenar.commons.apiresource.ApiResourceAudit
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_scenar_iam_apikey_v1_status_proto_init() }
func file_ai_scenar_iam_apikey_v1_status_proto_init() {
	if File_ai_scenar_iam_apikey_v1_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_iam_apikey_v1_status_proto_rawDesc), len(file_ai_scenar_iam_apikey_v1_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_iam_apikey_v1_status_proto_goTypes,
		DependencyIndexes: file_ai_scenar_iam_apikey_v1_status_proto_depIdxs,
		MessageInfos:      file_ai_scenar_iam_apikey_v1_status_proto_msgTypes,
	}.Build()
	File_ai_scenar_iam_apikey_v1_status_proto = out.File
	file_ai_scenar_iam_apikey_v1_status_proto_goTypes = nil
	file_ai_scenar_iam_apikey_v1_status_proto_depIdxs = nil
}
