// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=js"
// @generated from file ai/scenar/iam/apikey/v1/enum.proto (package ai.scenar.iam.apikey.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file ai/scenar/iam/apikey/v1/enum.proto.
 */
export const file_ai_scenar_iam_apikey_v1_enum: GenFile = /*@__PURE__*/
  fileDesc("CiJhaS9zY2VuYXIvaWFtL2FwaWtleS92MS9lbnVtLnByb3RvEhdhaS5zY2VuYXIuaWFtLmFwaWtleS52MSpSCgtBcGlLZXlTY29wZRIdChlhcGlfa2V5X3Njb3BlX3Vuc3BlY2lmaWVkEAASEQoNZGVwbG95X2NyZWF0ZRABEhEKDWRlcGxveV91cGxvYWQQAmIGcHJvdG8z");

/**
 * ApiKeyScope enumerates the capabilities an ApiKey may be granted. Scopes
 * narrow what a key can do beyond what its owning principal is authorized for:
 * authentication resolves a presented key to its non-human principal, OpenFGA
 * authorizes that principal against the target resource, and the key's scopes
 * further gate which operations the key itself is permitted to perform.
 *
 * Scopes are least-privilege by design — a CLI deploy key carries only the
 * deploy scopes, never broad account access. The set is intentionally small and
 * grows with the operation surface (the deploy scopes below back `scenar
 * deploy`). Scope *enforcement* is applied by the operations that consume a key
 * (the deploy command surface); this enum and ApiKeySpec.scopes are the contract
 * those checks read.
 *
 * @generated from enum ai.scenar.iam.apikey.v1.ApiKeyScope
 */
export enum ApiKeyScope {
  /**
   * Default value. A key with no scopes can authenticate but is authorized for
   * no scoped operation; must not be used to imply "all scopes".
   *
   * @generated from enum value: api_key_scope_unspecified = 0;
   */
  api_key_scope_unspecified = 0,

  /**
   * Create a deploy for a scenario (open a two-phase upload session). Maps to
   * the `deploy:create` capability.
   *
   * @generated from enum value: deploy_create = 1;
   */
  deploy_create = 1,

  /**
   * Upload a deploy's bundle objects (complete an open upload session). Maps to
   * the `deploy:upload` capability.
   *
   * @generated from enum value: deploy_upload = 2;
   */
  deploy_upload = 2,
}

/**
 * Describes the enum ai.scenar.iam.apikey.v1.ApiKeyScope.
 */
export const ApiKeyScopeSchema: GenEnum<ApiKeyScope> = /*@__PURE__*/
  enumDesc(file_ai_scenar_iam_apikey_v1_enum, 0);

