// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file ai/scenar/iam/apikey/v1/spec.proto (package ai.scenar.iam.apikey.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_ai_scenar_commons_apiresource_field_options } from "../../../commons/apiresource/field_options_pb";
import type { ApiKeyScope } from "./enum_pb";
import { file_ai_scenar_iam_apikey_v1_enum } from "./enum_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/scenar/iam/apikey/v1/spec.proto.
 */
export const file_ai_scenar_iam_apikey_v1_spec: GenFile = /*@__PURE__*/
  fileDesc("CiJhaS9zY2VuYXIvaWFtL2FwaWtleS92MS9zcGVjLnByb3RvEhdhaS5zY2VuYXIuaWFtLmFwaWtleS52MSK8AQoKQXBpS2V5U3BlYxIWCghrZXlfaGFzaBgBIAEoCUIEyIUsARIZCgtmaW5nZXJwcmludBgCIAEoCUIEyIUsARIuCgpleHBpcmVzX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIVCg1uZXZlcl9leHBpcmVzGAQgASgIEjQKBnNjb3BlcxgFIAMoDjIkLmFpLnNjZW5hci5pYW0uYXBpa2V5LnYxLkFwaUtleVNjb3BlYgZwcm90bzM", [file_ai_scenar_commons_apiresource_field_options, file_ai_scenar_iam_apikey_v1_enum, file_google_protobuf_timestamp]);

/**
 * ApiKeySpec defines the configuration of an ApiKey resource — the `spec` block
 * of the envelope (see api.proto). It holds the key's identifying material
 * (hash and fingerprint, both server-computed) and its expiration policy.
 *
 * The raw key value never lives in the spec. It exists only transiently in the
 * create response (see ApiKeyStatus.plaintext_key); only its hash and a short
 * fingerprint are persisted here.
 *
 * @generated from message ai.scenar.iam.apikey.v1.ApiKeySpec
 */
export type ApiKeySpec = Message<"ai.scenar.iam.apikey.v1.ApiKeySpec"> & {
  /**
   * SHA-256 hash of the raw key. Computed by the backend at creation time and
   * used to look the key up during authentication (see
   * ApiKeyQueryController.getByKeyHash). The raw key is never recoverable from
   * this value.
   *
   * @generated from field: string key_hash = 1;
   */
  keyHash: string;

  /**
   * Short, non-secret fingerprint of the raw key (its trailing characters),
   * shown in listings and the UI so a user can recognize which key is which
   * without exposing the secret. Computed by the backend at creation time.
   *
   * @generated from field: string fingerprint = 2;
   */
  fingerprint: string;

  /**
   * Absolute moment at which the key stops being valid for authentication.
   * Ignored when never_expires is true. When both expires_at and never_expires
   * are unset, the key does not expire.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  /**
   * When true, the key never expires and expires_at is ignored. Defaults to
   * false.
   *
   * @generated from field: bool never_expires = 4;
   */
  neverExpires: boolean;

  /**
   * Capabilities this key is granted, least-privilege. A key authenticates to
   * its owning principal and is authorized by OpenFGA; its scopes further gate
   * which scoped operations it may perform (e.g. a CLI deploy key carries only
   * the deploy scopes). Set at creation; an empty set authorizes no scoped
   * operation. See ApiKeyScope.
   *
   * @generated from field: repeated ai.scenar.iam.apikey.v1.ApiKeyScope scopes = 5;
   */
  scopes: ApiKeyScope[];
};

/**
 * Describes the message ai.scenar.iam.apikey.v1.ApiKeySpec.
 * Use `create(ApiKeySpecSchema)` to create a new message.
 */
export const ApiKeySpecSchema: GenMessage<ApiKeySpec> = /*@__PURE__*/
  messageDesc(file_ai_scenar_iam_apikey_v1_spec, 0);

