// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/commons/apiresource/field_options.proto

package apiresource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_ai_scenar_commons_apiresource_field_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         90201,
		Name:          "ai.scenar.commons.apiresource.computed",
		Tag:           "varint,90201,opt,name=computed",
		Filename:      "ai/scenar/commons/apiresource/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         90202,
		Name:          "ai.scenar.commons.apiresource.immutable",
		Tag:           "varint,90202,opt,name=immutable",
		Filename:      "ai/scenar/commons/apiresource/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         90203,
		Name:          "ai.scenar.commons.apiresource.id_field",
		Tag:           "varint,90203,opt,name=id_field",
		Filename:      "ai/scenar/commons/apiresource/field_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Marks a field as server-computed / read-only. Clients may not set it on
	// create or update; the backend populates it. Typical for status fields
	// such as generated URLs and audit timestamps.
	//
	// optional bool computed = 90201;
	E_Computed = &file_ai_scenar_commons_apiresource_field_options_proto_extTypes[0]
	// Marks a field as immutable: it may be set once on create but not changed
	// by subsequent updates.
	//
	// optional bool immutable = 90202;
	E_Immutable = &file_ai_scenar_commons_apiresource_field_options_proto_extTypes[1]
	// Marks the field that carries the resource identifier on a reference
	// message. Used by codegen to flatten and resolve references.
	//
	// optional bool id_field = 90203;
	E_IdField = &file_ai_scenar_commons_apiresource_field_options_proto_extTypes[2]
)

var File_ai_scenar_commons_apiresource_field_options_proto protoreflect.FileDescriptor

const file_ai_scenar_commons_apiresource_field_options_proto_rawDesc = "" +
	"\n" +
	"1ai/scenar/commons/apiresource/field_options.proto\x12\x1dai.scenar.commons.apiresource\x1a google/protobuf/descriptor.proto:;\n" +
	"\bcomputed\x12\x1d.google.protobuf.FieldOptions\x18\xd9\xc0\x05 \x01(\bR\bcomputed:=\n" +
	"\timmutable\x12\x1d.google.protobuf.FieldOptions\x18\xda\xc0\x05 \x01(\bR\timmutable::\n" +
	"\bid_field\x12\x1d.google.protobuf.FieldOptions\x18\xdb\xc0\x05 \x01(\bR\aidFieldB\x95\x02\n" +
	"!com.ai.scenar.commons.apiresourceB\x11FieldOptionsProtoP\x01ZEgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource\xa2\x02\x04ASCA\xaa\x02\x1dAi.Scenar.Commons.Apiresource\xca\x02\x1dAi\\Scenar\\Commons\\Apiresource\xe2\x02)Ai\\Scenar\\Commons\\Apiresource\\GPBMetadata\xea\x02 Ai::Scenar::Commons::Apiresourceb\x06proto3"

var file_ai_scenar_commons_apiresource_field_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_ai_scenar_commons_apiresource_field_options_proto_depIdxs = []int32{
	0, // 0: ai.scenar.commons.apiresource.computed:extendee -> google.protobuf.FieldOptions
	0, // 1: ai.scenar.commons.apiresource.immutable:extendee -> google.protobuf.FieldOptions
	0, // 2: ai.scenar.commons.apiresource.id_field:extendee -> google.protobuf.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_commons_apiresource_field_options_proto_init() }
func file_ai_scenar_commons_apiresource_field_options_proto_init() {
	if File_ai_scenar_commons_apiresource_field_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_commons_apiresource_field_options_proto_rawDesc), len(file_ai_scenar_commons_apiresource_field_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_commons_apiresource_field_options_proto_goTypes,
		DependencyIndexes: file_ai_scenar_commons_apiresource_field_options_proto_depIdxs,
		ExtensionInfos:    file_ai_scenar_commons_apiresource_field_options_proto_extTypes,
	}.Build()
	File_ai_scenar_commons_apiresource_field_options_proto = out.File
	file_ai_scenar_commons_apiresource_field_options_proto_goTypes = nil
	file_ai_scenar_commons_apiresource_field_options_proto_depIdxs = nil
}
