// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/commons/apiresource/metadata.proto

package apiresource

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiResourceMetadata carries the standard, kind-independent metadata attached
// to every Scenar API resource. It is the `metadata` block of the
// Kubernetes-style resource envelope (api_version / kind / metadata / spec /
// status).
//
// This message is part of Scenar's "commons contract": the Scenar Cloud
// backend reuses the platform's shared Java libraries, which locate this block
// reflectively by the field name `metadata` and then read its sub-fields by
// name (`id`, `slug`, `org`, `name`, `visibility`, `version`). The field
// *names* below are therefore a contract — renaming any of them breaks the
// platform's metadata adapter and is rejected at service startup by the
// platform's metadata contract validator. Field *numbers* are local to Scenar
// and carry no cross-product meaning.
type ApiResourceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable display name of the resource.
	//
	// Validation is skipped when empty so that partial messages (server
	// responses that omit the name, patch requests, etc.) remain valid.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL-friendly identifier, unique within the owning organization. Combined
	// with `org` it forms the canonical reference `org/slug`.
	//
	// Format: lowercase alphanumeric characters and hyphens (minimum 2
	// characters); must start with a letter and end with a letter or digit.
	// When empty on create, the server derives the slug from `name`.
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	// System-generated unique identifier. Assigned by the server on create and
	// immutable thereafter. Prefixed per resource kind (see ApiResourceKindMeta).
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Organization that owns this resource. Every resource belongs to exactly
	// one organization. Required and enforced by the backend's authorization
	// layer in Cloud mode.
	Org string `protobuf:"bytes,4,opt,name=org,proto3" json:"org,omitempty"`
	// Access-control visibility for the resource. See ApiResourceVisibility.
	// Defaults to visibility_private for new resources.
	Visibility ApiResourceVisibility `protobuf:"varint,5,opt,name=visibility,proto3,enum=ai.scenar.commons.apiresource.ApiResourceVisibility" json:"visibility,omitempty"`
	// Free-form key/value labels for organization and filtering.
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Free-form key/value annotations for additional, non-identifying metadata.
	Annotations map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tags for categorization and search.
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// Version tracking information. Populated only for versioned resource kinds.
	Version       *ApiResourceMetadataVersion `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResourceMetadata) Reset() {
	*x = ApiResourceMetadata{}
	mi := &file_ai_scenar_commons_apiresource_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResourceMetadata) ProtoMessage() {}

func (x *ApiResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_commons_apiresource_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResourceMetadata.ProtoReflect.Descriptor instead.
func (*ApiResourceMetadata) Descriptor() ([]byte, []int) {
	return file_ai_scenar_commons_apiresource_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResourceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiResourceMetadata) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ApiResourceMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiResourceMetadata) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ApiResourceMetadata) GetVisibility() ApiResourceVisibility {
	if x != nil {
		return x.Visibility
	}
	return ApiResourceVisibility_api_resource_visibility_unspecified
}

func (x *ApiResourceMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ApiResourceMetadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ApiResourceMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ApiResourceMetadata) GetVersion() *ApiResourceMetadataVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

// ApiResourceMetadataVersion tracks the version of a versioned resource.
//
// For versioned kinds, the backend populates this on every spec-changing
// create/update, analogous to a git commit: `id` is the content hash of the
// new version, `message` describes the change, and `previous_version_id`
// links to the prior version. Non-versioned kinds leave this unset.
type ApiResourceMetadataVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this version. For versioned resources this is the
	// SHA-256 content hash of the spec.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-supplied description of what changed in this version, analogous to
	// a git commit message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Identifier of the previous version, forming a linked history.
	PreviousVersionId string `protobuf:"bytes,3,opt,name=previous_version_id,json=previousVersionId,proto3" json:"previous_version_id,omitempty"`
	// Optional tag assigned to this version at creation time (e.g. "stable",
	// "v1.0", "production"). Only applicable to versioned resources.
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResourceMetadataVersion) Reset() {
	*x = ApiResourceMetadataVersion{}
	mi := &file_ai_scenar_commons_apiresource_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResourceMetadataVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResourceMetadataVersion) ProtoMessage() {}

func (x *ApiResourceMetadataVersion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_scenar_commons_apiresource_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResourceMetadataVersion.ProtoReflect.Descriptor instead.
func (*ApiResourceMetadataVersion) Descriptor() ([]byte, []int) {
	return file_ai_scenar_commons_apiresource_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResourceMetadataVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiResourceMetadataVersion) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResourceMetadataVersion) GetPreviousVersionId() string {
	if x != nil {
		return x.PreviousVersionId
	}
	return ""
}

func (x *ApiResourceMetadataVersion) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_ai_scenar_commons_apiresource_metadata_proto protoreflect.FileDescriptor

const file_ai_scenar_commons_apiresource_metadata_proto_rawDesc = "" +
	"\n" +
	",ai/scenar/commons/apiresource/metadata.proto\x12\x1dai.scenar.commons.apiresource\x1a(ai/scenar/commons/apiresource/enum.proto\x1a\x1bbuf/validate/validate.proto\"\x91\x05\n" +
	"\x13ApiResourceMetadata\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xd8\x01\x01R\x04name\x129\n" +
	"\x04slug\x18\x02 \x01(\tB%\xbaH\"\xd8\x01\x01r\x1d\x10\x022\x19^[a-z][a-z0-9-]*[a-z0-9]$R\x04slug\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x10\n" +
	"\x03org\x18\x04 \x01(\tR\x03org\x12^\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e24.ai.scenar.commons.apiresource.ApiResourceVisibilityB\b\xbaH\x05\x82\x01\x02\x10\x01R\n" +
	"visibility\x12V\n" +
	"\x06labels\x18\x06 \x03(\v2>.ai.scenar.commons.apiresource.ApiResourceMetadata.LabelsEntryR\x06labels\x12e\n" +
	"\vannotations\x18\a \x03(\v2C.ai.scenar.commons.apiresource.ApiResourceMetadata.AnnotationsEntryR\vannotations\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12S\n" +
	"\aversion\x18\t \x01(\v29.ai.scenar.commons.apiresource.ApiResourceMetadataVersionR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x1aApiResourceMetadataVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x13previous_version_id\x18\x03 \x01(\tR\x11previousVersionId\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tagB\x91\x02\n" +
	"!com.ai.scenar.commons.apiresourceB\rMetadataProtoP\x01ZEgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource\xa2\x02\x04ASCA\xaa\x02\x1dAi.Scenar.Commons.Apiresource\xca\x02\x1dAi\\Scenar\\Commons\\Apiresource\xe2\x02)Ai\\Scenar\\Commons\\Apiresource\\GPBMetadata\xea\x02 Ai::Scenar::Commons::Apiresourceb\x06proto3"

var (
	file_ai_scenar_commons_apiresource_metadata_proto_rawDescOnce sync.Once
	file_ai_scenar_commons_apiresource_metadata_proto_rawDescData []byte
)

func file_ai_scenar_commons_apiresource_metadata_proto_rawDescGZIP() []byte {
	file_ai_scenar_commons_apiresource_metadata_proto_rawDescOnce.Do(func() {
		file_ai_scenar_commons_apiresource_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_scenar_commons_apiresource_metadata_proto_rawDesc), len(file_ai_scenar_commons_apiresource_metadata_proto_rawDesc)))
	})
	return file_ai_scenar_commons_apiresource_metadata_proto_rawDescData
}

var file_ai_scenar_commons_apiresource_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_scenar_commons_apiresource_metadata_proto_goTypes = []any{
	(*ApiResourceMetadata)(nil),        // 0: ai.scenar.commons.apiresource.ApiResourceMetadata
	(*ApiResourceMetadataVersion)(nil), // 1: ai.scenar.commons.apiresource.ApiResourceMetadataVersion
	nil,                                // 2: ai.scenar.commons.apiresource.ApiResourceMetadata.LabelsEntry
	nil,                                // 3: ai.scenar.commons.apiresource.ApiResourceMetadata.AnnotationsEntry
	(ApiResourceVisibility)(0),         // 4: ai.scenar.commons.apiresource.ApiResourceVisibility
}
var file_ai_scenar_commons_apiresource_metadata_proto_depIdxs = []int32{
	4, // 0: ai.scenar.commons.apiresource.ApiResourceMetadata.visibility:type_name -> ai.scenar.commons.apiresource.ApiResourceVisibility
	2, // 1: ai.scenar.commons.apiresource.ApiResourceMetadata.labels:type_name -> ai.scenar.commons.apiresource.ApiResourceMetadata.LabelsEntry
	3, // 2: ai.scenar.commons.apiresource.ApiResourceMetadata.annotations:type_name -> ai.scenar.commons.apiresource.ApiResourceMetadata.AnnotationsEntry
	1, // 3: ai.scenar.commons.apiresource.ApiResourceMetadata.version:type_name -> ai.scenar.commons.apiresource.ApiResourceMetadataVersion
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_scenar_commons_apiresource_metadata_proto_init() }
func file_ai_scenar_commons_apiresource_metadata_proto_init() {
	if File_ai_scenar_commons_apiresource_metadata_proto != nil {
		return
	}
	file_ai_scenar_commons_apiresource_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_commons_apiresource_metadata_proto_rawDesc), len(file_ai_scenar_commons_apiresource_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_scenar_commons_apiresource_metadata_proto_goTypes,
		DependencyIndexes: file_ai_scenar_commons_apiresource_metadata_proto_depIdxs,
		MessageInfos:      file_ai_scenar_commons_apiresource_metadata_proto_msgTypes,
	}.Build()
	File_ai_scenar_commons_apiresource_metadata_proto = out.File
	file_ai_scenar_commons_apiresource_metadata_proto_goTypes = nil
	file_ai_scenar_commons_apiresource_metadata_proto_depIdxs = nil
}
