// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/scenar/iam/iampolicy/v1/command.proto

package iampolicyv1

import (
	_ "github.com/stigmer/scenar/apis/stubs/go/ai/scenar/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ai_scenar_iam_iampolicy_v1_command_proto protoreflect.FileDescriptor

const file_ai_scenar_iam_iampolicy_v1_command_proto_rawDesc = "" +
	"\n" +
	"(ai/scenar/iam/iampolicy/v1/command.proto\x12\x1aai.scenar.iam.iampolicy.v1\x1a7ai/scenar/commons/apiresource/rpc_service_options.proto\x1a$ai/scenar/iam/iampolicy/v1/api.proto\x1a%ai/scenar/iam/iampolicy/v1/spec.proto\x1a\x1bgoogle/protobuf/empty.proto2\xc2\x02\n" +
	"\x1aIamPolicyCommandController\x12c\n" +
	"\x0fbootstrapPolicy\x12).ai.scenar.iam.iampolicy.v1.IamPolicySpec\x1a%.ai.scenar.iam.iampolicy.v1.IamPolicy\x12Z\n" +
	"\x06delete\x12).ai.scenar.iam.iampolicy.v1.IamPolicySpec\x1a%.ai.scenar.iam.iampolicy.v1.IamPolicy\x12]\n" +
	"\x17cleanupResourcePolicies\x12*.ai.scenar.iam.iampolicy.v1.ApiResourceRef\x1a\x16.google.protobuf.Empty\x1a\x04\xa0\xff+\n" +
	"B\x8b\x02\n" +
	"\x1ecom.ai.scenar.iam.iampolicy.v1B\fCommandProtoP\x01ZNgithub.com/stigmer/scenar/apis/stubs/go/ai/scenar/iam/iampolicy/v1;iampolicyv1\xa2\x02\x04ASII\xaa\x02\x1aAi.Scenar.Iam.Iampolicy.V1\xca\x02\x1aAi\\Scenar\\Iam\\Iampolicy\\V1\xe2\x02&Ai\\Scenar\\Iam\\Iampolicy\\V1\\GPBMetadata\xea\x02\x1eAi::Scenar::Iam::Iampolicy::V1b\x06proto3"

var file_ai_scenar_iam_iampolicy_v1_command_proto_goTypes = []any{
	(*IamPolicySpec)(nil),  // 0: ai.scenar.iam.iampolicy.v1.IamPolicySpec
	(*ApiResourceRef)(nil), // 1: ai.scenar.iam.iampolicy.v1.ApiResourceRef
	(*IamPolicy)(nil),      // 2: ai.scenar.iam.iampolicy.v1.IamPolicy
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_ai_scenar_iam_iampolicy_v1_command_proto_depIdxs = []int32{
	0, // 0: ai.scenar.iam.iampolicy.v1.IamPolicyCommandController.bootstrapPolicy:input_type -> ai.scenar.iam.iampolicy.v1.IamPolicySpec
	0, // 1: ai.scenar.iam.iampolicy.v1.IamPolicyCommandController.delete:input_type -> ai.scenar.iam.iampolicy.v1.IamPolicySpec
	1, // 2: ai.scenar.iam.iampolicy.v1.IamPolicyCommandController.cleanupResourcePolicies:input_type -> ai.scenar.iam.iampolicy.v1.ApiResourceRef
	2, // 3: ai.scenar.iam.iampolicy.v1.IamPolicyCommandController.bootstrapPolicy:output_type -> ai.scenar.iam.iampolicy.v1.IamPolicy
	2, // 4: ai.scenar.iam.iampolicy.v1.IamPolicyCommandController.delete:output_type -> ai.scenar.iam.iampolicy.v1.IamPolicy
	3, // 5: ai.scenar.iam.iampolicy.v1.IamPolicyCommandController.cleanupResourcePolicies:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_scenar_iam_iampolicy_v1_command_proto_init() }
func file_ai_scenar_iam_iampolicy_v1_command_proto_init() {
	if File_ai_scenar_iam_iampolicy_v1_command_proto != nil {
		return
	}
	file_ai_scenar_iam_iampolicy_v1_api_proto_init()
	file_ai_scenar_iam_iampolicy_v1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_scenar_iam_iampolicy_v1_command_proto_rawDesc), len(file_ai_scenar_iam_iampolicy_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_scenar_iam_iampolicy_v1_command_proto_goTypes,
		DependencyIndexes: file_ai_scenar_iam_iampolicy_v1_command_proto_depIdxs,
	}.Build()
	File_ai_scenar_iam_iampolicy_v1_command_proto = out.File
	file_ai_scenar_iam_iampolicy_v1_command_proto_goTypes = nil
	file_ai_scenar_iam_iampolicy_v1_command_proto_depIdxs = nil
}
