# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/iam/v1/enum.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/iam/v1/enum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61i/scenar/iam/v1/enum.proto\x12\x10\x61i.scenar.iam.v1*\xf9\x01\n\rIamPermission\x12\x0f\n\x0bunspecified\x10\x00\x12\x0c\n\x08\x63\x61n_view\x10\x01\x12\x0c\n\x08\x63\x61n_edit\x10\x02\x12\x0e\n\ncan_delete\x10\x03\x12\x14\n\x10\x63\x61n_grant_access\x10\x04\x12\x13\n\x0f\x63\x61n_view_access\x10\x05\x12\x17\n\x13\x63\x61n_create_scenario\x10\x06\x12\x14\n\x10\x63\x61n_read_secrets\x10\x10\x12\x15\n\x11\x63\x61n_bootstrap_iam\x10\x11\x12 \n\x1c\x63\x61n_manage_identity_accounts\x10\x12\x12\x18\n\x14login_to_back_office\x10\x14*Q\n\x07IamRole\x12\x18\n\x14iam_role_unspecified\x10\x00\x12\t\n\x05owner\x10\x01\x12\t\n\x05\x61\x64min\x10\x02\x12\n\n\x06member\x10\x03\x12\n\n\x06viewer\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.iam.v1.enum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IAMPERMISSION']._serialized_start=50
  _globals['_IAMPERMISSION']._serialized_end=299
  _globals['_IAMROLE']._serialized_start=301
  _globals['_IAMROLE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
