# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/commons/resource/metadata.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/commons/resource/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.resource import enum_pb2 as ai_dot_scenar_dot_commons_dot_resource_dot_enum__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)ai/scenar/commons/resource/metadata.proto\x12\x1a\x61i.scenar.commons.resource\x1a%ai/scenar/commons/resource/enum.proto\x1a\x1b\x62uf/validate/validate.proto\"\xb5\x04\n\x10ResourceMetadata\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04slug\x18\x02 \x01(\tR\x04slug\x12\x0e\n\x02id\x18\x03 \x01(\tR\x02id\x12X\n\nvisibility\x18\x04 \x01(\x0e\x32..ai.scenar.commons.resource.ResourceVisibilityB\x08\xbaH\x05\x82\x01\x02\x10\x01R\nvisibility\x12P\n\x06labels\x18\x05 \x03(\x0b\x32\x38.ai.scenar.commons.resource.ResourceMetadata.LabelsEntryR\x06labels\x12_\n\x0b\x61nnotations\x18\x06 \x03(\x0b\x32=.ai.scenar.commons.resource.ResourceMetadata.AnnotationsEntryR\x0b\x61nnotations\x12\x12\n\x04tags\x18\x07 \x03(\tR\x04tags\x12M\n\x07version\x18\x08 \x01(\x0b\x32\x33.ai.scenar.commons.resource.ResourceMetadataVersionR\x07version\x1a\x39\n\x0bLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"s\n\x17ResourceMetadataVersion\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12.\n\x13previous_version_id\x18\x03 \x01(\tR\x11previousVersionIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.commons.resource.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCEMETADATA_LABELSENTRY']._loaded_options = None
  _globals['_RESOURCEMETADATA_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_RESOURCEMETADATA_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_RESOURCEMETADATA_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_RESOURCEMETADATA'].fields_by_name['visibility']._loaded_options = None
  _globals['_RESOURCEMETADATA'].fields_by_name['visibility']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_RESOURCEMETADATA']._serialized_start=142
  _globals['_RESOURCEMETADATA']._serialized_end=707
  _globals['_RESOURCEMETADATA_LABELSENTRY']._serialized_start=586
  _globals['_RESOURCEMETADATA_LABELSENTRY']._serialized_end=643
  _globals['_RESOURCEMETADATA_ANNOTATIONSENTRY']._serialized_start=645
  _globals['_RESOURCEMETADATA_ANNOTATIONSENTRY']._serialized_end=707
  _globals['_RESOURCEMETADATAVERSION']._serialized_start=709
  _globals['_RESOURCEMETADATAVERSION']._serialized_end=824
# @@protoc_insertion_point(module_scope)
