# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/commons/resource/status.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/commons/resource/status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ai/scenar/commons/resource/status.proto\x12\x1a\x61i.scenar.commons.resource\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n\x13ResourceAuditStatus\x12?\n\x05\x61udit\x18\x63 \x01(\x0b\x32).ai.scenar.commons.resource.ResourceAuditR\x05\x61udit\"\xaf\x01\n\rResourceAudit\x12L\n\nspec_audit\x18\x01 \x01(\x0b\x32-.ai.scenar.commons.resource.ResourceAuditInfoR\tspecAudit\x12P\n\x0cstatus_audit\x18\x02 \x01(\x0b\x32-.ai.scenar.commons.resource.ResourceAuditInfoR\x0bstatusAudit\"\xbd\x02\n\x11ResourceAuditInfo\x12M\n\ncreated_by\x18\x01 \x01(\x0b\x32..ai.scenar.commons.resource.ResourceAuditActorR\tcreatedBy\x12\x39\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12M\n\nupdated_by\x18\x03 \x01(\x0b\x32..ai.scenar.commons.resource.ResourceAuditActorR\tupdatedBy\x12\x39\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n\x05\x65vent\x18\x05 \x01(\tR\x05\x65vent\"<\n\x12ResourceAuditActor\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06\x61vatar\x18\x02 \x01(\tR\x06\x61vatarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.commons.resource.status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCEAUDITSTATUS']._serialized_start=104
  _globals['_RESOURCEAUDITSTATUS']._serialized_end=190
  _globals['_RESOURCEAUDIT']._serialized_start=193
  _globals['_RESOURCEAUDIT']._serialized_end=368
  _globals['_RESOURCEAUDITINFO']._serialized_start=371
  _globals['_RESOURCEAUDITINFO']._serialized_end=688
  _globals['_RESOURCEAUDITACTOR']._serialized_start=690
  _globals['_RESOURCEAUDITACTOR']._serialized_end=750
# @@protoc_insertion_point(module_scope)
