# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/iam/identityaccount/v1/query.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/iam/identityaccount/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource import rpc_service_options_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from ai.scenar.iam.identityaccount.v1 import api_pb2 as ai_dot_scenar_dot_iam_dot_identityaccount_dot_v1_dot_api__pb2
from ai.scenar.iam.identityaccount.v1 import io_pb2 as ai_dot_scenar_dot_iam_dot_identityaccount_dot_v1_dot_io__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,ai/scenar/iam/identityaccount/v1/query.proto\x12 ai.scenar.iam.identityaccount.v1\x1a\x37\x61i/scenar/commons/apiresource/rpc_service_options.proto\x1a*ai/scenar/iam/identityaccount/v1/api.proto\x1a)ai/scenar/iam/identityaccount/v1/io.proto2\xfc\x02\n\x1eIdentityAccountQueryController\x12q\n\x07getById\x12\x33.ai.scenar.iam.identityaccount.v1.IdentityAccountId\x1a\x31.ai.scenar.iam.identityaccount.v1.IdentityAccount\x12h\n\ngetByIdpId\x12\'.ai.scenar.iam.identityaccount.v1.IdpId\x1a\x31.ai.scenar.iam.identityaccount.v1.IdentityAccount\x12w\n\ngetByEmail\x12\x36.ai.scenar.iam.identityaccount.v1.IdentityAccountEmail\x1a\x31.ai.scenar.iam.identityaccount.v1.IdentityAccount\x1a\x04\xa0\xff+\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.iam.identityaccount.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDENTITYACCOUNTQUERYCONTROLLER']._loaded_options = None
  _globals['_IDENTITYACCOUNTQUERYCONTROLLER']._serialized_options = b'\240\377+\013'
  _globals['_IDENTITYACCOUNTQUERYCONTROLLER']._serialized_start=227
  _globals['_IDENTITYACCOUNTQUERYCONTROLLER']._serialized_end=607
# @@protoc_insertion_point(module_scope)
