# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/commons/apiresource/apiresourcekind/api_resource_group.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/commons/apiresource/apiresourcekind/api_resource_group.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFai/scenar/commons/apiresource/apiresourcekind/api_resource_group.proto\x12-ai.scenar.commons.apiresource.apiresourcekind\x1a google/protobuf/descriptor.proto\"Q\n\x14\x41piResourceGroupMeta\x12\x16\n\x06\x64omain\x18\x01 \x01(\tR\x06\x64omain\x12!\n\x0c\x64isplay_name\x18\x02 \x01(\tR\x0b\x64isplayName*\xb6\x01\n\x10\x41piResourceGroup\x12\"\n\x1e\x61pi_resource_group_unspecified\x10\x00\x12,\n\x06studio\x10\x01\x1a \xea\xbd,\x1c\n\x12scenario.scenar.ai\x12\x06Studio\x12-\n\x07tenancy\x10\x02\x1a \xea\xbd,\x1c\n\x11tenancy.scenar.ai\x12\x07Tenancy\x12!\n\x03iam\x10\x03\x1a\x18\xea\xbd,\x14\n\riam.scenar.ai\x12\x03IAM:\x87\x01\n\ngroup_meta\x12!.google.protobuf.EnumValueOptions\x18\xdd\xc7\x05 \x01(\x0b\x32\x43.ai.scenar.commons.apiresource.apiresourcekind.ApiResourceGroupMetaR\tgroupMetab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.commons.apiresource.apiresourcekind.api_resource_group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APIRESOURCEGROUP'].values_by_name["studio"]._loaded_options = None
  _globals['_APIRESOURCEGROUP'].values_by_name["studio"]._serialized_options = b'\352\275,\034\n\022scenario.scenar.ai\022\006Studio'
  _globals['_APIRESOURCEGROUP'].values_by_name["tenancy"]._loaded_options = None
  _globals['_APIRESOURCEGROUP'].values_by_name["tenancy"]._serialized_options = b'\352\275,\034\n\021tenancy.scenar.ai\022\007Tenancy'
  _globals['_APIRESOURCEGROUP'].values_by_name["iam"]._loaded_options = None
  _globals['_APIRESOURCEGROUP'].values_by_name["iam"]._serialized_options = b'\352\275,\024\n\riam.scenar.ai\022\003IAM'
  _globals['_APIRESOURCEGROUP']._serialized_start=239
  _globals['_APIRESOURCEGROUP']._serialized_end=421
  _globals['_APIRESOURCEGROUPMETA']._serialized_start=155
  _globals['_APIRESOURCEGROUPMETA']._serialized_end=236
# @@protoc_insertion_point(module_scope)
