# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/scenar/commons/apiresource/apiresourcekind/api_resource_kind.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ai/scenar/commons/apiresource/apiresourcekind/api_resource_kind.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.scenar.commons.apiresource.apiresourcekind import api_resource_group_pb2 as ai_dot_scenar_dot_commons_dot_apiresource_dot_apiresourcekind_dot_api__resource__group__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEai/scenar/commons/apiresource/apiresourcekind/api_resource_kind.proto\x12-ai.scenar.commons.apiresource.apiresourcekind\x1a\x46\x61i/scenar/commons/apiresource/apiresourcekind/api_resource_group.proto\x1a google/protobuf/descriptor.proto\"\xc0\x02\n\x13\x41piResourceKindMeta\x12U\n\x05group\x18\x01 \x01(\x0e\x32?.ai.scenar.commons.apiresource.apiresourcekind.ApiResourceGroupR\x05group\x12[\n\x07version\x18\x02 \x01(\x0e\x32\x41.ai.scenar.commons.apiresource.apiresourcekind.ApiResourceVersionR\x07version\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12!\n\x0c\x64isplay_name\x18\x04 \x01(\tR\x0b\x64isplayName\x12\x1b\n\tid_prefix\x18\x05 \x01(\tR\x08idPrefix\x12!\n\x0cis_versioned\x18\x06 \x01(\x08R\x0bisVersioned*B\n\x12\x41piResourceVersion\x12$\n api_resource_version_unspecified\x10\x00\x12\x06\n\x02v1\x10\x01*\xcb\x01\n\x0f\x41piResourceKind\x12\x1d\n\x19\x61pi_resource_kind_unknown\x10\x00\x12/\n\x08scenario\x10\x01\x1a!\xaa\xff+\x1d\x08\x01\x10\x01\x1a\x08Scenario\"\x08Scenario*\x03scn\x12;\n\x0corganization\x10\x02\x1a)\xaa\xff+%\x08\x02\x10\x01\x1a\x0cOrganization\"\x0cOrganization*\x03org\x12+\n\x07\x61pi_key\x10\x03\x1a\x1e\xaa\xff+\x1a\x08\x03\x10\x01\x1a\x06\x41piKey\"\x07\x41PI Key*\x03key:\x84\x01\n\tkind_meta\x12!.google.protobuf.EnumValueOptions\x18\xf5\xbf\x05 \x01(\x0b\x32\x42.ai.scenar.commons.apiresource.apiresourcekind.ApiResourceKindMetaR\x08kindMetab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.scenar.commons.apiresource.apiresourcekind.api_resource_kind_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APIRESOURCEKIND'].values_by_name["scenario"]._loaded_options = None
  _globals['_APIRESOURCEKIND'].values_by_name["scenario"]._serialized_options = b'\252\377+\035\010\001\020\001\032\010Scenario\"\010Scenario*\003scn'
  _globals['_APIRESOURCEKIND'].values_by_name["organization"]._loaded_options = None
  _globals['_APIRESOURCEKIND'].values_by_name["organization"]._serialized_options = b'\252\377+%\010\002\020\001\032\014Organization\"\014Organization*\003org'
  _globals['_APIRESOURCEKIND'].values_by_name["api_key"]._loaded_options = None
  _globals['_APIRESOURCEKIND'].values_by_name["api_key"]._serialized_options = b'\252\377+\032\010\003\020\001\032\006ApiKey\"\007API Key*\003key'
  _globals['_APIRESOURCEVERSION']._serialized_start=549
  _globals['_APIRESOURCEVERSION']._serialized_end=615
  _globals['_APIRESOURCEKIND']._serialized_start=618
  _globals['_APIRESOURCEKIND']._serialized_end=821
  _globals['_APIRESOURCEKINDMETA']._serialized_start=227
  _globals['_APIRESOURCEKINDMETA']._serialized_end=547
# @@protoc_insertion_point(module_scope)
